# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Авито Реклама — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from datetime import date

from ..enums.ads import (
    CampaignPaymentModel,
    CampaignStatus,
    CampaignType,
    ContractAction,
    ContractCounterpartyType,
    ContractSubject,
    ContractType,
    CreativesStatus,
    GroupsStatus,
    LegalRole,
    LegalType,
    Paces,
    UserRole,
)
from ..methods.ads import (
    V1AddUser,
    V1ChangeBudget,
    V1ChangePrice,
    V1CreateAccount,
    V1CreateAdvertiser,
    V1CreateContract,
    V1CreateNonPayerAccount,
    V1DeleteUser,
    V1GetAccountBalanceById,
    V1GetAccountById,
    V1GetAdvertisersList,
    V1GetCampaignsList,
    V1GetCampaignStatistic,
    V1GetChildAccountsList,
    V1GetChildAccountsWithBalancesList,
    V1GetContractsList,
    V1GetCreativesList,
    V1GetCreativesStatistic,
    V1GetGroupsList,
    V1GetGroupsStatistic,
    V1GetUsersListByAccount,
    V1SetUserRole,
    V1TransferBonus,
    V1TransferFunds,
)
from ..models._helpers import _resolve_user_id
from ..models._shared import IdResponse
from ..models.ads import (
    AdvertiserFilter,
    CampaignsFilter,
    ContractsFilter,
    CreativesFilter,
    CreteIntermediaryIn,
    DateRange,
    EmptyResponse,
    GroupsFilter,
    V1CreateAccountContact,
    V1CreateAccountOut,
    V1CreateNonPayerAccountOut,
    V1GetAccountBalanceByIdOut,
    V1GetAccountByIdOut,
    V1GetAdvertisersListOut,
    V1GetCampaignsListOut,
    V1GetCampaignStatisticOut,
    V1GetChildAccountsListOut,
    V1GetChildAccountsWithBalancesListOut,
    V1GetContractsListOut,
    V1GetCreativesListOut,
    V1GetCreativesStatisticOut,
    V1GetGroupsListOut,
    V1GetGroupsStatisticOut,
    V1GetUsersListByAccountOut,
)
from ._base import FacadeBase


class AdsFacade(FacadeBase):
    """``Client`` mixin — Авито Реклама endpoints."""

    async def v1_get_account_by_id(self, account_id: int) -> V1GetAccountByIdOut:
        """Получить аккаунт по ID via ``GET /ads/v1/account/{account_id}``."""
        return await self.execute(V1GetAccountById(account_id=account_id))

    async def v1_create_account(
        self,
        account_id: int,
        name: str,
        phone: str,
        inn: str,
        legal_address: str,
        legal_type: LegalType,
        long_name: str,
        ogrn: str,
        short_name: str,
        actual_address: str | None = None,
        kpp: str | None = None,
    ) -> V1CreateAccountOut:
        """Создать аккаунт в песочнице via ``POST /ads/v1/account/{account_id}``.

        Args:
            actual_address: Фактический адрес. Если не передан, используется legalAddress.
            name: ФИО контактного лица
            phone: Контактный телефон
            inn: ИНН организации или ИП
            kpp: КПП организации
            legal_address: Юридический адрес или адрес регистрации
            long_name: Полное наименование организации или ИП
            ogrn: ОГРН или ОГРНИП
            short_name: Краткое название аккаунта
        """
        return await self.execute(
            V1CreateAccount(
                account_id=account_id,
                actual_address=actual_address,
                contact=V1CreateAccountContact(name=name, phone=phone),
                inn=inn,
                kpp=kpp,
                legal_address=legal_address,
                legal_type=legal_type,
                long_name=long_name,
                ogrn=ogrn,
                short_name=short_name,
            )
        )

    async def v1_add_user(self, account_id: int, role: UserRole, user_id: int) -> EmptyResponse:
        """Добавить пользователя в аккаунт via ``POST /ads/v1/account/{account_id}/add-user``.

        Args:
            user_id: ID пользователя авито
        """
        return await self.execute(V1AddUser(account_id=account_id, role=role, user_id=user_id))

    async def v1_get_advertisers_list(
        self,
        account_id: int,
        limit: int,
        page: int,
        ids: list[int] | None = None,
        inns: list[str] | None = None,
        roles: list[LegalRole] | None = None,
    ) -> V1GetAdvertisersListOut:
        """Получить список рекламодателей по фильтрам via ``POST /ads/v1/account/{account_id}/advertisers``.

        Args:
            ids: Список ID рекламодателей
            inns: Список ИНН рекламодателей
            roles: Список ролей рекламодателей
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self.execute(
            V1GetAdvertisersList(
                account_id=account_id,
                filter=AdvertiserFilter(ids=ids, inns=inns, roles=roles),
                limit=limit,
                page=page,
            )
        )

    async def v1_get_account_balance_by_id(self, account_id: int) -> V1GetAccountBalanceByIdOut:
        """Получить баланс аккаунта по ID via ``GET /ads/v1/account/{account_id}/balance``."""
        return await self.execute(V1GetAccountBalanceById(account_id=account_id))

    async def v1_transfer_bonus(
        self, account_id: int, account_id_to: int, amount: int
    ) -> EmptyResponse:
        """Перевод бонусов между аккаунтом родителем и дочерними на одном договоре via ``POST /ads/v1/account/{account_id}/bonus-transfer``.

        Args:
            account_id_to: accountId на который перевести
            amount: Сумма бонусов, не меньше 1 бонуса
        """
        return await self.execute(
            V1TransferBonus(account_id=account_id, account_id_to=account_id_to, amount=amount)
        )

    async def v1_get_campaigns_list(
        self,
        account_id: int,
        limit: int,
        page: int,
        additional_agreement_ids: list[int] | None = None,
        advertisers: list[int] | None = None,
        campaign_types: list[CampaignType] | None = None,
        contract_ids: list[int] | None = None,
        created_at: DateRange | None = None,
        ids: list[int] | None = None,
        managers: list[int] | None = None,
        payment_models: list[CampaignPaymentModel] | None = None,
        statuses: list[CampaignStatus] | None = None,
        time_frame: DateRange | None = None,
    ) -> V1GetCampaignsListOut:
        """Получить список кампаний по фильтрам via ``POST /ads/v1/account/{account_id}/campaigns``.

        Args:
            additional_agreement_ids: Список ID дополнительных соглашений
            advertisers: Список ID рекламодателей
            campaign_types: Список типов кампаний
            contract_ids: Список ID договоров
            ids: Список ID кампаний
            managers: Список ID менеджеров
            payment_models: Список моделей оплаты
            statuses: Список статусов кампаний
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self.execute(
            V1GetCampaignsList(
                account_id=account_id,
                filter=CampaignsFilter(
                    additional_agreement_ids=additional_agreement_ids,
                    advertisers=advertisers,
                    campaign_types=campaign_types,
                    contract_ids=contract_ids,
                    created_at=created_at,
                    ids=ids,
                    managers=managers,
                    payment_models=payment_models,
                    statuses=statuses,
                    time_frame=time_frame,
                ),
                limit=limit,
                page=page,
            )
        )

    async def v1_get_creatives_statistic(
        self,
        account_id: int,
        campaign_id: int,
        creative_ids: list[int],
        date_from: date,
        date_to: date,
    ) -> V1GetCreativesStatisticOut:
        """Получить статистику по креативам кампании via ``POST /ads/v1/account/{account_id}/campaigns/{campaign_id}/creatives/stats``.

        Args:
            account_id: ID аккаунта
            campaign_id: ID кампании
            creative_ids: Список ID креативов для получения статистики
            date_from: Дата начала периода в формате YYYY-MM-DD
            date_to: Дата окончания периода в формате YYYY-MM-DD
        """
        return await self.execute(
            V1GetCreativesStatistic(
                account_id=account_id,
                campaign_id=campaign_id,
                creative_ids=creative_ids,
                date_from=date_from,
                date_to=date_to,
            )
        )

    async def v1_get_groups_statistic(
        self,
        account_id: int,
        campaign_id: int,
        date_from: date,
        date_to: date,
        group_ids: list[int],
    ) -> V1GetGroupsStatisticOut:
        """Получить статистику по группам кампании via ``POST /ads/v1/account/{account_id}/campaigns/{campaign_id}/groups/stats``.

        Args:
            account_id: ID аккаунта
            campaign_id: ID кампании
            date_from: Дата начала периода в формате YYYY-MM-DD
            date_to: Дата окончания периода в формате YYYY-MM-DD
            group_ids: Список ID групп для получения статистики
        """
        return await self.execute(
            V1GetGroupsStatistic(
                account_id=account_id,
                campaign_id=campaign_id,
                date_from=date_from,
                date_to=date_to,
                group_ids=group_ids,
            )
        )

    async def v1_get_campaign_statistic(
        self, account_id: int, campaign_id: int, date_from: date, date_to: date
    ) -> V1GetCampaignStatisticOut:
        """Получить статистику по кампании via ``POST /ads/v1/account/{account_id}/campaigns/{campaign_id}/stats``.

        Args:
            account_id: ID аккаунта
            campaign_id: ID кампании
            date_from: Дата начала периода в формате YYYY-MM-DD
            date_to: Дата окончания периода в формате YYYY-MM-DD
        """
        return await self.execute(
            V1GetCampaignStatistic(
                account_id=account_id, campaign_id=campaign_id, date_from=date_from, date_to=date_to
            )
        )

    async def v1_get_child_accounts_list(self, account_id: int) -> V1GetChildAccountsListOut:
        """Получить список дочерних аккаунтов via ``GET /ads/v1/account/{account_id}/children``."""
        return await self.execute(V1GetChildAccountsList(account_id=account_id))

    async def v1_get_child_accounts_with_balances_list(
        self, account_id: int
    ) -> V1GetChildAccountsWithBalancesListOut:
        """Получить список дочерних аккаунтов с балансами via ``GET /ads/v1/account/{account_id}/children-with-balances``."""
        return await self.execute(V1GetChildAccountsWithBalancesList(account_id=account_id))

    async def v1_get_contracts_list(
        self,
        account_id: int,
        limit: int,
        page: int,
        clients: AdvertiserFilter | None = None,
        contractors: AdvertiserFilter | None = None,
        ids: list[int] | None = None,
        numbers: list[str] | None = None,
    ) -> V1GetContractsListOut:
        """Получить список договоров по фильтрам via ``POST /ads/v1/account/{account_id}/contracts``.

        Args:
            ids: Список ID договоров
            numbers: Список номеров договоров
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self.execute(
            V1GetContractsList(
                account_id=account_id,
                filter=ContractsFilter(
                    clients=clients, contractors=contractors, ids=ids, numbers=numbers
                ),
                limit=limit,
                page=page,
            )
        )

    async def v1_create_advertiser(
        self,
        account_id: int,
        inn: str,
        legal_address: str,
        legal_role: LegalRole,
        legal_type: LegalType,
        long_name: str,
        ogrn: str,
        short_name: str,
        actual_address: str | None = None,
        kpp: str | None = None,
    ) -> IdResponse:
        """Создать рекламодателя via ``POST /ads/v1/account/{account_id}/create-advertiser``.

        Args:
            actual_address: Фактический адрес. Если не передан, используется legalAddress. Пример корректного адреса: 127015, г. Москва, ул. Лесная, д. 7
            inn: ИНН организации
            kpp: КПП организации
            legal_address: Юридический адрес или адрес регистрации. Пример корректного адреса: 127015, г. Москва, ул. Лесная, д. 7
            long_name: Полное наименование организации или ИП
            ogrn: ОГРН или ОГРНИП
            short_name: Краткое наименование организации или ИП
        """
        return await self.execute(
            V1CreateAdvertiser(
                account_id=account_id,
                actual_address=actual_address,
                inn=inn,
                kpp=kpp,
                legal_address=legal_address,
                legal_role=legal_role,
                legal_type=legal_type,
                long_name=long_name,
                ogrn=ogrn,
                short_name=short_name,
            )
        )

    async def v1_create_contract(
        self,
        account_id: int,
        advertiser_id: int,
        description: ContractCounterpartyType,
        type_: ContractType,
        cid: str | None = None,
        date_: date | None = None,
        actual_address: str | None = None,
        inn: str | None = None,
        kpp: str | None = None,
        legal_address: str | None = None,
        legal_type: LegalType | None = None,
        long_name: str | None = None,
        ogrn: str | None = None,
        short_name: str | None = None,
        is_funds_allocation_to_principal: bool | None = None,
        is_reporting_required: bool | None = None,
        number: str | None = None,
        object: ContractAction | None = None,
        parent_id: int | None = None,
        subject: ContractSubject | None = None,
    ) -> IdResponse:
        """Создание изначального договора via ``POST /ads/v1/account/{account_id}/create-contract``.

        Args:
            advertiser_id: Id рекламодателя. Указываем только рекламодателей которые не являются аккаунтом. Если рекламодатель и аккаунт одно и тоже ЮЛ, договор создавать не надо
            cid: CID внешнего договора, заполняется только для type = external.
            date_: Дата в формате YYYY-MM-DD. Можно не передавать только для type = external.
            actual_address: Почтовый адрес
            inn: ИНН ЮЛ/ИП
            kpp: КПП ЮЛ, для ИП не передаем
            legal_address: Юридически адрес
            long_name: Полное имя ЮЛ/ИП
            ogrn: ОГРНИП для ИП, ОРГН для ЮЛ
            short_name: Короткое имя ЮЛ/ИП
            is_funds_allocation_to_principal: Денежные средства на размещение рекламы идут в сторону принципала
            is_reporting_required: На исполнителе лежит обязанность отчитываться по креативам
            number: Номер договора. Можно не передавать только для type = external.
            parent_id: ID родительского договора для доп. соглашения
        """
        return await self.execute(
            V1CreateContract(
                account_id=account_id,
                advertiser_id=advertiser_id,
                cid=cid,
                date_=date_,
                description=description,
                intermediary=CreteIntermediaryIn(
                    actual_address=actual_address,
                    inn=inn,
                    kpp=kpp,
                    legal_address=legal_address,
                    legal_type=legal_type,
                    long_name=long_name,
                    ogrn=ogrn,
                    short_name=short_name,
                ),
                is_funds_allocation_to_principal=is_funds_allocation_to_principal,
                is_reporting_required=is_reporting_required,
                number=number,
                object=object,
                parent_id=parent_id,
                subject=subject,
                type_=type_,
            )
        )

    async def v1_create_non_payer_account(
        self, account_id: int, is_self_advertising_enabled: bool, short_name: str
    ) -> V1CreateNonPayerAccountOut:
        """Создание дочернего аккаунта на договоре родителя via ``POST /ads/v1/account/{account_id}/create-nonpayer-child-account``.

        Args:
            is_self_advertising_enabled: Флаг разрешающий рекламировать родительский аккаунт. Если вам надо рекламировать нового рекламодателя без возможности рекламировать родителя, выставлять - false
            short_name: Краткое название дочернего аккаунта, меньше 64 символов
        """
        return await self.execute(
            V1CreateNonPayerAccount(
                account_id=account_id,
                is_self_advertising_enabled=is_self_advertising_enabled,
                short_name=short_name,
            )
        )

    async def v1_get_creatives_list(
        self,
        account_id: int,
        limit: int,
        page: int,
        advertisers: list[int] | None = None,
        campaign_ids: list[int] | None = None,
        campaign_types: list[CampaignType] | None = None,
        group_ids: list[int] | None = None,
        ids: list[int] | None = None,
        managers: list[int] | None = None,
        payment_models: list[CampaignPaymentModel] | None = None,
        statuses: list[CreativesStatus] | None = None,
        time_frame: DateRange | None = None,
    ) -> V1GetCreativesListOut:
        """Получить список креативов по фильтрам via ``POST /ads/v1/account/{account_id}/creatives``.

        Args:
            advertisers: Список ID рекламодателей
            campaign_ids: Список ID кампаний
            campaign_types: Список типов кампаний
            group_ids: Список ID групп
            ids: Список ID креативов
            managers: Список ID менеджеров
            payment_models: Список моделей оплаты
            statuses: Список статусов креативов
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self.execute(
            V1GetCreativesList(
                account_id=account_id,
                filter=CreativesFilter(
                    advertisers=advertisers,
                    campaign_ids=campaign_ids,
                    campaign_types=campaign_types,
                    group_ids=group_ids,
                    ids=ids,
                    managers=managers,
                    payment_models=payment_models,
                    statuses=statuses,
                    time_frame=time_frame,
                ),
                limit=limit,
                page=page,
            )
        )

    async def v1_delete_user(self, account_id: int, user_id: int | None = None) -> EmptyResponse:
        """Удалить пользователя из аккаунта via ``DELETE /ads/v1/account/{account_id}/delete-user/{user_id}``."""
        return await self.execute(
            V1DeleteUser(
                account_id=account_id,
                user_id=_resolve_user_id(self) if user_id is None else user_id,
            )
        )

    async def v1_transfer_funds(
        self, account_id: int, account_id_to: int, amount: int
    ) -> EmptyResponse:
        """Перевод денег между аккаунтом родителем и дочерними на одном договоре via ``POST /ads/v1/account/{account_id}/funds-transfer``.

        Args:
            account_id_to: accountId на который перевести
            amount: Сумма перевода в рублях, не меньше 1 рубля
        """
        return await self.execute(
            V1TransferFunds(account_id=account_id, account_id_to=account_id_to, amount=amount)
        )

    async def v1_change_budget(self, account_id: int, group_id: int, budget: int) -> EmptyResponse:
        """Изменить бюджет группы via ``POST /ads/v1/account/{account_id}/group/{group_id}/change-budget``.

        Args:
            budget: Новый бюджет группы в рублях с НДС
        """
        return await self.execute(
            V1ChangeBudget(account_id=account_id, group_id=group_id, budget=budget)
        )

    async def v1_change_price(self, account_id: int, group_id: int, price: int) -> EmptyResponse:
        """Изменить цену группы via ``POST /ads/v1/account/{account_id}/group/{group_id}/change-price``.

        Args:
            price: Новая ставка группы в рублях с НДС
        """
        return await self.execute(
            V1ChangePrice(account_id=account_id, group_id=group_id, price=price)
        )

    async def v1_get_groups_list(
        self,
        account_id: int,
        limit: int,
        page: int,
        advertisers: list[int] | None = None,
        campaign_ids: list[int] | None = None,
        ids: list[int] | None = None,
        managers: list[int] | None = None,
        paces: list[Paces] | None = None,
        payment_models: list[CampaignPaymentModel] | None = None,
        statuses: list[GroupsStatus] | None = None,
        time_frame: DateRange | None = None,
    ) -> V1GetGroupsListOut:
        """Получить список групп по фильтрам via ``POST /ads/v1/account/{account_id}/groups``.

        Args:
            advertisers: Список ID рекламодателей
            campaign_ids: Список ID кампаний
            ids: Список ID групп
            managers: Список ID менеджеров
            paces: Скорости показов
            payment_models: Список моделей оплаты
            statuses: Список статусов групп
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self.execute(
            V1GetGroupsList(
                account_id=account_id,
                filter=GroupsFilter(
                    advertisers=advertisers,
                    campaign_ids=campaign_ids,
                    ids=ids,
                    managers=managers,
                    paces=paces,
                    payment_models=payment_models,
                    statuses=statuses,
                    time_frame=time_frame,
                ),
                limit=limit,
                page=page,
            )
        )

    async def v1_set_user_role(
        self, account_id: int, role: UserRole, user_id: int
    ) -> EmptyResponse:
        """Изменить роль пользователя в аккаунте via ``POST /ads/v1/account/{account_id}/set-user-role``.

        Args:
            user_id: ID пользователя авито
        """
        return await self.execute(V1SetUserRole(account_id=account_id, role=role, user_id=user_id))

    async def v1_get_users_list_by_account(self, account_id: int) -> V1GetUsersListByAccountOut:
        """Получить список пользователей аккаунта via ``GET /ads/v1/account/{account_id}/users``."""
        return await self.execute(V1GetUsersListByAccount(account_id=account_id))
