# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Авито Реклама — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from datetime import date

from ..enums.ads import (
    ContractAction,
    ContractCounterpartyType,
    ContractSubject,
    ContractType,
    LegalRole,
    LegalType,
    UserRole,
)
from ..methods.ads import (
    V1AddUser,
    V1ChangeBudget,
    V1ChangePrice,
    V1CreateAccount,
    V1CreateAdvertiser,
    V1CreateContract,
    V1CreateNonPayerAccount,
    V1DeleteUser,
    V1GetAccountBalanceById,
    V1GetAccountById,
    V1GetAdvertisersList,
    V1GetCampaignsList,
    V1GetCampaignStatistic,
    V1GetChildAccountsList,
    V1GetChildAccountsWithBalancesList,
    V1GetContractsList,
    V1GetCreativesList,
    V1GetCreativesStatistic,
    V1GetGroupsList,
    V1GetGroupsStatistic,
    V1GetUsersListByAccount,
    V1SetUserRole,
    V1TransferBonus,
    V1TransferFunds,
)
from ..models._helpers import _resolve_user_id
from ..models.ads import (
    AdvertiserFilter,
    CampaignsFilter,
    ContractsFilter,
    CreativesFilter,
    CreteIntermediaryIn,
    EmptyResponse,
    GroupsFilter,
    V1CreateAccountContact,
    V1CreateAccountOut,
    V1CreateAdvertiserOut,
    V1CreateContractOut,
    V1CreateNonPayerAccountOut,
    V1GetAccountBalanceByIdOut,
    V1GetAccountByIdOut,
    V1GetAdvertisersListOut,
    V1GetCampaignsListOut,
    V1GetCampaignStatisticOut,
    V1GetChildAccountsListOut,
    V1GetChildAccountsWithBalancesListOut,
    V1GetContractsListOut,
    V1GetCreativesListOut,
    V1GetCreativesStatisticOut,
    V1GetGroupsListOut,
    V1GetGroupsStatisticOut,
    V1GetUsersListByAccountOut,
)
from ._base import FacadeBase


class AdsFacade(FacadeBase):
    """``Client`` mixin — Авито Реклама endpoints."""

    async def v1_get_account_by_id(self, account_id: int) -> V1GetAccountByIdOut:
        """Получить аккаунт по ID via ``GET /ads/v1/account/{account_id}``.

        See: https://developers.avito.ru/api-catalog/ads/documentation
        """
        return await self(V1GetAccountById(account_id=account_id))

    async def v1_create_account(
        self,
        account_id: int,
        contact: V1CreateAccountContact,
        inn: str,
        legal_address: str,
        legal_type: LegalType,
        long_name: str,
        ogrn: str,
        short_name: str,
        actual_address: str | None = None,
        kpp: str | None = None,
    ) -> V1CreateAccountOut:
        """Создать аккаунт в песочнице via ``POST /ads/v1/account/{account_id}``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            actual_address: Фактический адрес. Если не передан, используется legalAddress.
            contact: Контактное лицо
            inn: ИНН организации или ИП
            kpp: КПП организации
            legal_address: Юридический адрес или адрес регистрации
            long_name: Полное наименование организации или ИП
            ogrn: ОГРН или ОГРНИП
            short_name: Краткое название аккаунта
        """
        return await self(
            V1CreateAccount(
                account_id=account_id,
                actual_address=actual_address,
                contact=contact,
                inn=inn,
                kpp=kpp,
                legal_address=legal_address,
                legal_type=legal_type,
                long_name=long_name,
                ogrn=ogrn,
                short_name=short_name,
            )
        )

    async def v1_add_user(self, account_id: int, role: UserRole, user_id: int) -> EmptyResponse:
        """Добавить пользователя в аккаунт via ``POST /ads/v1/account/{account_id}/add-user``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            user_id: ID пользователя авито
        """
        return await self(V1AddUser(account_id=account_id, role=role, user_id=user_id))

    async def v1_get_advertisers_list(
        self, account_id: int, filter: AdvertiserFilter, limit: int, page: int
    ) -> V1GetAdvertisersListOut:
        """Получить список рекламодателей по фильтрам via ``POST /ads/v1/account/{account_id}/advertisers``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self(
            V1GetAdvertisersList(account_id=account_id, filter=filter, limit=limit, page=page)
        )

    async def v1_get_account_balance_by_id(self, account_id: int) -> V1GetAccountBalanceByIdOut:
        """Получить баланс аккаунта по ID via ``GET /ads/v1/account/{account_id}/balance``.

        See: https://developers.avito.ru/api-catalog/ads/documentation
        """
        return await self(V1GetAccountBalanceById(account_id=account_id))

    async def v1_transfer_bonus(
        self, account_id: int, account_id_to: int, amount: int
    ) -> EmptyResponse:
        """Перевод бонусов между аккаунтом родителем и дочерними на одном договоре via ``POST /ads/v1/account/{account_id}/bonus-transfer``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            account_id_to: accountId на который перевести
            amount: Сумма бонусов, не меньше 1 бонуса
        """
        return await self(
            V1TransferBonus(account_id=account_id, account_id_to=account_id_to, amount=amount)
        )

    async def v1_get_campaigns_list(
        self, account_id: int, filter: CampaignsFilter, limit: int, page: int
    ) -> V1GetCampaignsListOut:
        """Получить список кампаний по фильтрам via ``POST /ads/v1/account/{account_id}/campaigns``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self(
            V1GetCampaignsList(account_id=account_id, filter=filter, limit=limit, page=page)
        )

    async def v1_get_creatives_statistic(
        self,
        account_id: int,
        campaign_id: int,
        creative_i_ds: list[int],
        date_from: date,
        date_to: date,
    ) -> V1GetCreativesStatisticOut:
        """Получить статистику по креативам кампании via ``POST /ads/v1/account/{account_id}/campaigns/{campaign_id}/creatives/stats``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            account_id: ID аккаунта
            campaign_id: ID кампании
            creative_i_ds: Список ID креативов для получения статистики
            date_from: Дата начала периода в формате YYYY-MM-DD
            date_to: Дата окончания периода в формате YYYY-MM-DD
        """
        return await self(
            V1GetCreativesStatistic(
                account_id=account_id,
                campaign_id=campaign_id,
                creative_i_ds=creative_i_ds,
                date_from=date_from,
                date_to=date_to,
            )
        )

    async def v1_get_groups_statistic(
        self,
        account_id: int,
        campaign_id: int,
        date_from: date,
        date_to: date,
        group_i_ds: list[int],
    ) -> V1GetGroupsStatisticOut:
        """Получить статистику по группам кампании via ``POST /ads/v1/account/{account_id}/campaigns/{campaign_id}/groups/stats``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            account_id: ID аккаунта
            campaign_id: ID кампании
            date_from: Дата начала периода в формате YYYY-MM-DD
            date_to: Дата окончания периода в формате YYYY-MM-DD
            group_i_ds: Список ID групп для получения статистики
        """
        return await self(
            V1GetGroupsStatistic(
                account_id=account_id,
                campaign_id=campaign_id,
                date_from=date_from,
                date_to=date_to,
                group_i_ds=group_i_ds,
            )
        )

    async def v1_get_campaign_statistic(
        self, account_id: int, campaign_id: int, date_from: date, date_to: date
    ) -> V1GetCampaignStatisticOut:
        """Получить статистику по кампании via ``POST /ads/v1/account/{account_id}/campaigns/{campaign_id}/stats``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            account_id: ID аккаунта
            campaign_id: ID кампании
            date_from: Дата начала периода в формате YYYY-MM-DD
            date_to: Дата окончания периода в формате YYYY-MM-DD
        """
        return await self(
            V1GetCampaignStatistic(
                account_id=account_id, campaign_id=campaign_id, date_from=date_from, date_to=date_to
            )
        )

    async def v1_get_child_accounts_list(self, account_id: int) -> V1GetChildAccountsListOut:
        """Получить список дочерних аккаунтов via ``GET /ads/v1/account/{account_id}/children``.

        See: https://developers.avito.ru/api-catalog/ads/documentation
        """
        return await self(V1GetChildAccountsList(account_id=account_id))

    async def v1_get_child_accounts_with_balances_list(
        self, account_id: int
    ) -> V1GetChildAccountsWithBalancesListOut:
        """Получить список дочерних аккаунтов с балансами via ``GET /ads/v1/account/{account_id}/children-with-balances``.

        See: https://developers.avito.ru/api-catalog/ads/documentation
        """
        return await self(V1GetChildAccountsWithBalancesList(account_id=account_id))

    async def v1_get_contracts_list(
        self, account_id: int, filter: ContractsFilter, limit: int, page: int
    ) -> V1GetContractsListOut:
        """Получить список договоров по фильтрам via ``POST /ads/v1/account/{account_id}/contracts``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self(
            V1GetContractsList(account_id=account_id, filter=filter, limit=limit, page=page)
        )

    async def v1_create_advertiser(
        self,
        account_id: int,
        inn: str,
        legal_address: str,
        legal_role: LegalRole,
        legal_type: LegalType,
        long_name: str,
        ogrn: str,
        short_name: str,
        actual_address: str | None = None,
        kpp: str | None = None,
    ) -> V1CreateAdvertiserOut:
        """Создать рекламодателя via ``POST /ads/v1/account/{account_id}/create-advertiser``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            actual_address: Фактический адрес. Если не передан, используется legalAddress. Пример корректного адреса: 127015, г. Москва, ул. Лесная, д. 7
            inn: ИНН организации
            kpp: КПП организации
            legal_address: Юридический адрес или адрес регистрации. Пример корректного адреса: 127015, г. Москва, ул. Лесная, д. 7
            long_name: Полное наименование организации или ИП
            ogrn: ОГРН или ОГРНИП
            short_name: Краткое наименование организации или ИП
        """
        return await self(
            V1CreateAdvertiser(
                account_id=account_id,
                actual_address=actual_address,
                inn=inn,
                kpp=kpp,
                legal_address=legal_address,
                legal_role=legal_role,
                legal_type=legal_type,
                long_name=long_name,
                ogrn=ogrn,
                short_name=short_name,
            )
        )

    async def v1_create_contract(
        self,
        account_id: int,
        advertiser_id: int,
        description: ContractCounterpartyType,
        type_: ContractType,
        cid: str | None = None,
        date_: date | None = None,
        intermediary: CreteIntermediaryIn | None = None,
        is_funds_allocation_to_principal: bool | None = None,
        is_reporting_required: bool | None = None,
        number: str | None = None,
        object: ContractAction | None = None,
        parent_id: int | None = None,
        subject: ContractSubject | None = None,
    ) -> V1CreateContractOut:
        """Создание изначального договора via ``POST /ads/v1/account/{account_id}/create-contract``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            advertiser_id: Id рекламодателя. Указываем только рекламодателей которые не являются аккаунтом. Если рекламодатель и аккаунт одно и тоже ЮЛ, договор создавать не надо
            cid: CID внешнего договора, заполняется только для type = external.
            date_: Дата в формате YYYY-MM-DD. Можно не передавать только для type = external.
            is_funds_allocation_to_principal: Денежные средства на размещение рекламы идут в сторону принципала
            is_reporting_required: На исполнителе лежит обязанность отчитываться по креативам
            number: Номер договора. Можно не передавать только для type = external.
            parent_id: ID родительского договора для доп. соглашения
        """
        return await self(
            V1CreateContract(
                account_id=account_id,
                advertiser_id=advertiser_id,
                cid=cid,
                date_=date_,
                description=description,
                intermediary=intermediary,
                is_funds_allocation_to_principal=is_funds_allocation_to_principal,
                is_reporting_required=is_reporting_required,
                number=number,
                object=object,
                parent_id=parent_id,
                subject=subject,
                type_=type_,
            )
        )

    async def v1_create_non_payer_account(
        self, account_id: int, is_self_advertising_enabled: bool, short_name: str
    ) -> V1CreateNonPayerAccountOut:
        """Создание дочернего аккаунта на договоре родителя via ``POST /ads/v1/account/{account_id}/create-nonpayer-child-account``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            is_self_advertising_enabled: Флаг разрешающий рекламировать родительский аккаунт. Если вам надо рекламировать нового рекламодателя без возможности рекламировать родителя, выставлять - false
            short_name: Краткое название дочернего аккаунта, меньше 64 символов
        """
        return await self(
            V1CreateNonPayerAccount(
                account_id=account_id,
                is_self_advertising_enabled=is_self_advertising_enabled,
                short_name=short_name,
            )
        )

    async def v1_get_creatives_list(
        self, account_id: int, filter: CreativesFilter, limit: int, page: int
    ) -> V1GetCreativesListOut:
        """Получить список креативов по фильтрам via ``POST /ads/v1/account/{account_id}/creatives``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self(
            V1GetCreativesList(account_id=account_id, filter=filter, limit=limit, page=page)
        )

    async def v1_delete_user(self, account_id: int, user_id: int | None = None) -> EmptyResponse:
        """Удалить пользователя из аккаунта via ``DELETE /ads/v1/account/{account_id}/delete-user/{user_id}``.

        See: https://developers.avito.ru/api-catalog/ads/documentation
        """
        return await self(
            V1DeleteUser(
                account_id=account_id,
                user_id=_resolve_user_id(self) if user_id is None else user_id,
            )
        )

    async def v1_transfer_funds(
        self, account_id: int, account_id_to: int, amount: int
    ) -> EmptyResponse:
        """Перевод денег между аккаунтом родителем и дочерними на одном договоре via ``POST /ads/v1/account/{account_id}/funds-transfer``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            account_id_to: accountId на который перевести
            amount: Сумма перевода в рублях, не меньше 1 рубля
        """
        return await self(
            V1TransferFunds(account_id=account_id, account_id_to=account_id_to, amount=amount)
        )

    async def v1_change_budget(self, account_id: int, group_id: int, budget: int) -> EmptyResponse:
        """Изменить бюджет группы via ``POST /ads/v1/account/{account_id}/group/{group_id}/change-budget``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            budget: Новый бюджет группы в рублях с НДС
        """
        return await self(V1ChangeBudget(account_id=account_id, group_id=group_id, budget=budget))

    async def v1_change_price(self, account_id: int, group_id: int, price: int) -> EmptyResponse:
        """Изменить цену группы via ``POST /ads/v1/account/{account_id}/group/{group_id}/change-price``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            price: Новая ставка группы в рублях с НДС
        """
        return await self(V1ChangePrice(account_id=account_id, group_id=group_id, price=price))

    async def v1_get_groups_list(
        self, account_id: int, filter: GroupsFilter, limit: int, page: int
    ) -> V1GetGroupsListOut:
        """Получить список групп по фильтрам via ``POST /ads/v1/account/{account_id}/groups``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            limit: Количество записей на странице
            page: Номер страницы
        """
        return await self(
            V1GetGroupsList(account_id=account_id, filter=filter, limit=limit, page=page)
        )

    async def v1_set_user_role(
        self, account_id: int, role: UserRole, user_id: int
    ) -> EmptyResponse:
        """Изменить роль пользователя в аккаунте via ``POST /ads/v1/account/{account_id}/set-user-role``.

        See: https://developers.avito.ru/api-catalog/ads/documentation

        Args:
            user_id: ID пользователя авито
        """
        return await self(V1SetUserRole(account_id=account_id, role=role, user_id=user_id))

    async def v1_get_users_list_by_account(self, account_id: int) -> V1GetUsersListByAccountOut:
        """Получить список пользователей аккаунта via ``GET /ads/v1/account/{account_id}/users``.

        See: https://developers.avito.ru/api-catalog/ads/documentation
        """
        return await self(V1GetUsersListByAccount(account_id=account_id))
