# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""CallTracking[КТ] — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..methods.calltracking import GetCallById, GetCalls, GetRecordByCallId
from ..models.calltracking import GetCallByIdResponse, GetCallsResponse
from ._base import FacadeBase


class CalltrackingFacade(FacadeBase):
    """``Client`` mixin — CallTracking[КТ] endpoints."""

    async def get_call_by_id(self, call_id: int) -> GetCallByIdResponse:
        """Звонок по идентификатору via ``POST /calltracking/v1/getCallById/``.

        See: https://developers.avito.ru/api-catalog/calltracking/documentation
        """
        return await self(GetCallById(call_id=call_id))

    async def get_calls(
        self, date_time_from: str, limit: int, offset: int, date_time_to: str | None = None
    ) -> GetCallsResponse:
        """Звонки по времени via ``POST /calltracking/v1/getCalls/``.

        See: https://developers.avito.ru/api-catalog/calltracking/documentation

        Args:
            date_time_from: Время с которого нужно начинать поиск звонков по callTime (строка в формате RFC3339)
            date_time_to: Время до которого нужно искать заонки по callTime (строка в формате RFC3339). Если не указано, используется dateTimeFrom + 1 месяц. Максимально возможное значение - dateTimeFrom + 3 месяца.
            limit: Размер выборки
            offset: Смещение выборки
        """
        return await self(
            GetCalls(
                date_time_from=date_time_from, date_time_to=date_time_to, limit=limit, offset=offset
            )
        )

    async def get_record_by_call_id(self, call_id: int) -> None:
        """Получение аудиозаписи звонка по идентификатору via ``GET /calltracking/v1/getRecordByCallId/``.

        See: https://developers.avito.ru/api-catalog/calltracking/documentation

        Args:
            call_id: Идентификатор звонка
        """
        return await self(GetRecordByCallId(call_id=call_id))
