# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Настройка цены целевого действия — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..methods.cpxpromo import (
    GetBids,
    GetPromotionsByItemIds,
    RemovePromotion2,
    SaveAutoBid,
    SaveManualBid,
)
from ..models.cpxpromo import GetBidsOut, GetPromotionsByItemIdsOut, RemovePromotion2Response
from ._base import FacadeBase


class CpxpromoFacade(FacadeBase):
    """``Client`` mixin — Настройка цены целевого действия endpoints."""

    async def bids(self, item_id: int) -> GetBidsOut:
        """Получение детализированной информации о действующих и доступных ценах за целевые действия и бюджетах via ``GET /cpxpromo/1/getBids/{item_id}``."""
        return await self.execute(GetBids(item_id=item_id))

    async def promotions_by_item_ids(self, item_ids: list[int]) -> GetPromotionsByItemIdsOut:
        """Получение текущих цен за целевое действие и бюджетов по нескольким объявлениям via ``POST /cpxpromo/1/getPromotionsByItemIds``."""
        return await self.execute(GetPromotionsByItemIds(item_ids=item_ids))

    async def remove_promotion2(self, item_id: int) -> RemovePromotion2Response:
        """Остановка продвижения via ``POST /cpxpromo/1/remove``.

        Args:
            item_id: Идентификатор объявления
        """
        return await self.execute(RemovePromotion2(item_id=item_id))

    async def save_auto_bid(
        self, action_type_id: int, budget_penny: int, budget_type: str, item_id: int
    ) -> None:
        """Применение автоматической настройки via ``POST /cpxpromo/1/setAuto``.

        Args:
            action_type_id: Тип события (1 - звонок | 5 - пакет кликов | 7 - мессенджер, передача контакта в чате)
            budget_penny: Текущий бюджет в копейках
            budget_type: Тип бюджета (\"1d\" - дневной | \"7d\" - недельный | \"30d\" - месячный)
            item_id: Идентификатор объявления
        """
        return await self.execute(
            SaveAutoBid(
                action_type_id=action_type_id,
                budget_penny=budget_penny,
                budget_type=budget_type,
                item_id=item_id,
            )
        )

    async def save_manual_bid(
        self, action_type_id: int, bid_penny: int, item_id: int, limit_penny: int | None = None
    ) -> None:
        """Применение ручной настройки via ``POST /cpxpromo/1/setManual``.

        Args:
            action_type_id: Тип события (1 - звонок | 5 - пакет кликов | 7 - мессенджер, передача контакта в чате)
            bid_penny: Текущая цена за целевое действие в копейках
            item_id: Идентификатор объявления
            limit_penny: Дневной лимит в копейках
        """
        return await self.execute(
            SaveManualBid(
                action_type_id=action_type_id,
                bid_penny=bid_penny,
                item_id=item_id,
                limit_penny=limit_penny,
            )
        )
