# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Доставка — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from ..enums.delivery import (
    AddTariffSandboxV2TariffType,
    CancelAnnouncement3PlReason,
    CancelParcelActor,
    ChangeParcelResultStatus,
    ChangeParcelsType,
    CreateAnnouncement3PlAnnouncementType,
    CreateAnnouncementAnnouncementType,
    TrackAnnouncementEvent,
    V1changeParcelType,
    V1createAnnouncementAnnouncementType,
)
from ..methods.delivery import (
    AddAreasSandbox,
    AddSortingCenter,
    AddTagsToSortingCenter,
    AddTariffSandboxV2,
    AddTerminalsSandbox,
    CancelAnnouncement3Pl,
    CancelParcel,
    ChangeParcelResult,
    ChangeParcels,
    CheckConfirmationCode,
    CreateAnnouncement,
    CreateAnnouncement3Pl,
    CreateParcel,
    CreateSandboxParcelV22,
    CustomAreaSchedule,
    GetSortingCenter,
    GetTask,
    ProhibitOrderAcceptance,
    SetOrderProperties,
    SetOrderRealAddress,
    TrackAnnouncement,
    Tracking,
    UpdateTerms,
    V1cancelAnnouncement,
    V1CancelParcel,
    V1changeParcel,
    V1createAnnouncement,
    V1getAnnouncementEvent,
    V1getChangeParcelInfo,
    V1getParcelInfo,
    V1getRegisteredParcelId,
)
from ..models.common import TZDatetime
from ..models.delivery import (
    AddTariffReply,
    AddTaskReply,
    AddTerminalsReply,
    AnnouncementsSuccessResponse,
    CancelParcelReply,
    CancelSandboxParcelOptions,
    CancelSandboxParcelReply,
    ChangeParcelReply,
    ChangeParcelRequestApplication,
    ChangeParcelRequestOptions,
    ChangeParcelResultOptions,
    ChangeParcelResultReply,
    ChangeParcelsApplication,
    ChangeParcelsResponse,
    CheckConfirmationCodeReply,
    CreateParcelClient,
    CreateParcelItem,
    CreateParcelOptions,
    CreateParcelPackage,
    CreateParcelPayment,
    CreateParcelReply,
    CreateParcelResponse,
    CreateSandboxParcelItem,
    CreateSandboxParcelV22Receiver,
    CreateSandboxParcelV22Sender,
    CreateSandboxV2Options,
    DeliveryParams,
    DeliverySetOrderPropertiesReply,
    DeliverySetStatusReply,
    DirectionV2,
    GetChangeParcelInfoReply,
    GetRegisteredParcelIdReply,
    GetSandboxParcelInfoReply,
    GetTaskReply,
    ProhibitOrderAcceptanceReply,
    SandboxCancelAnnouncementOptions,
    SandboxCancelAnnouncementReply,
    SandboxCreateAnnouncementOptions,
    SandboxCreateAnnouncementPackage,
    SandboxCreateAnnouncementParticipant,
    SandboxCreateAnnouncementReply,
    SandboxGetAnnouncementEventReply,
    SetOrderRealAddressAddress,
    SortingCenterGet,
    TariffZone,
    TermsZone,
    TrackingOptions,
    UpdateTermsReply,
)
from ._base import FacadeBase


class DeliveryFacade(FacadeBase):
    """``Client`` mixin — Доставка endpoints."""

    async def cancel_announcement3_pl(
        self, announcement_id: str, reason: CancelAnnouncement3PlReason | None = None
    ) -> AnnouncementsSuccessResponse:
        """Отмена анонса в СД via ``POST /cancelAnnouncement``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            reason: Причина омены анонса
        """
        return await self(CancelAnnouncement3Pl(announcement_id=announcement_id, reason=reason))

    async def create_announcement3_pl(
        self,
        announcement_id: str,
        announcement_type: CreateAnnouncement3PlAnnouncementType,
        barcode: str,
        date_: Any,
        packages: list[Any],
        receiver: Any,
        sender: Any,
    ) -> AnnouncementsSuccessResponse:
        """Создание анонса в СД via ``POST /createAnnouncement``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            announcement_type: Тип анонса
            barcode: Уникальный ШК анонса. Должен быть напечатан на бумажных сопроводительных документах (акте приема передачи). Данный ШК необходимо использовать для установки соответствия принимаемой партии грузомест/посылок с анонсом переданным в электронном виде через инфообмен.
            date_: Дата и время создания анонса в формате RFC 3339 в UTC
            packages: Список грузомест
        """
        return await self(
            CreateAnnouncement3Pl(
                announcement_id=announcement_id,
                announcement_type=announcement_type,
                barcode=barcode,
                date_=date_,
                packages=packages,
                receiver=receiver,
                sender=sender,
            )
        )

    async def create_parcel(
        self,
        items: list[CreateParcelItem],
        order_id: str,
        parcel_id: str,
        payment: CreateParcelPayment,
        receiver: CreateParcelClient,
        sender: CreateParcelClient,
        barcodes: list[str] | None = None,
        direct_order_id: str | None = None,
        options: CreateParcelOptions | None = None,
        package: CreateParcelPackage | None = None,
    ) -> CreateParcelResponse:
        """Создание посылки via ``POST /createParcel``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            barcodes: Штрихкоды посылки.
            direct_order_id: Идентификатор прямого заказа Avito.
            items: Список товаров, которые поедут в посылке. Содержит полное описание каждого отдельно взятого товара.
            order_id: Идентификатор заказа Avito.
            parcel_id: Идентификатор посылки Avito.
        """
        return await self(
            CreateParcel(
                barcodes=barcodes,
                direct_order_id=direct_order_id,
                items=items,
                options=options,
                order_id=order_id,
                package=package,
                parcel_id=parcel_id,
                payment=payment,
                receiver=receiver,
                sender=sender,
            )
        )

    async def create_announcement(
        self,
        announcement_id: str,
        announcement_type: CreateAnnouncementAnnouncementType,
        barcode: str,
        date_: Any,
        packages: list[Any],
        receiver: Any,
        sender: Any,
    ) -> AnnouncementsSuccessResponse:
        """Создание анонса в Avito via ``POST /delivery-sandbox/announcements/create``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            announcement_type: Тип анонса
            barcode: Уникальный ШК анонса. Должен быть напечатан на бумажных сопроводительных документах (акте приема передачи). Данный ШК необходимо использовать для установки соответствия принимаемой партии грузомест/посылок с анонсом переданным в электронном виде через инфообмен
            date_: Дата и время создания анонса в формате RFC 3339 в UTC
            packages: Список грузомест
        """
        return await self(
            CreateAnnouncement(
                announcement_id=announcement_id,
                announcement_type=announcement_type,
                barcode=barcode,
                date_=date_,
                packages=packages,
                receiver=receiver,
                sender=sender,
            )
        )

    async def track_announcement(
        self, announcement_id: str, date_: Any, event: TrackAnnouncementEvent
    ) -> AnnouncementsSuccessResponse:
        """Трекинг анонсов via ``POST /delivery-sandbox/announcements/track``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            date_: Дата события
        """
        return await self(
            TrackAnnouncement(announcement_id=announcement_id, date_=date_, event=event)
        )

    async def custom_area_schedule(self) -> AddTaskReply:
        """Установка графика работы на определённый день via ``POST /delivery-sandbox/areas/custom-schedule``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(CustomAreaSchedule())

    async def cancel_parcel(self, actor: CancelParcelActor, parcel_id: str) -> CancelParcelReply:
        """Отмена посылки via ``POST /delivery-sandbox/cancelParcel``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            actor: Кто отменяет посылку
        """
        return await self(CancelParcel(actor=actor, parcel_id=parcel_id))

    async def check_confirmation_code(
        self, confirm_code: str, parcel_id: str
    ) -> CheckConfirmationCodeReply:
        """Проверка кода подтверждения via ``POST /delivery-sandbox/order/checkConfirmationCode``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(CheckConfirmationCode(confirm_code=confirm_code, parcel_id=parcel_id))

    async def set_order_properties(
        self, order_id: str, properties: DeliveryParams
    ) -> DeliverySetOrderPropertiesReply:
        """Добавление / изменение параметров доставки посылки via ``POST /delivery-sandbox/order/properties``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(SetOrderProperties(order_id=order_id, properties=properties))

    async def set_order_real_address(
        self, address: SetOrderRealAddressAddress, order_id: str
    ) -> DeliverySetOrderPropertiesReply:
        """Фактический адрес приёма / возврата посылки via ``POST /delivery-sandbox/order/realAddress``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(SetOrderRealAddress(address=address, order_id=order_id))

    async def tracking(
        self,
        avito_event_type: str,
        avito_status: Any,
        date_: str,
        location: str,
        order_id: str,
        provider_event_code: str,
        comment: str | None = None,
        options: TrackingOptions | None = None,
    ) -> DeliverySetStatusReply:
        """Трекинг via ``POST /delivery-sandbox/order/tracking``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            avito_event_type: Описание статусов см. [здесь](https://developers.avito.ru/api-catalog/delivery-sandbox/documentation#info/mehanika_raboty_trekinga).
            avito_status: Описание статусов см. [здесь](https://developers.avito.ru/api-catalog/delivery-sandbox/documentation#info/mehanika_raboty_trekinga).
            comment: Комментарий к статусу.
            location: Локация в которой произошло событие (населённый пункт в именительном падеже).
            options: Дополнительные опции к статусу. На данный момент в опциях поддержана передача штрихкода посылки и возвратных номеров. Если номера `returnTrackingNumber` и `returnDispatchNumber` совпадают, то нужно присылать в них одинаковые значения.
            provider_event_code: Код события по версии службы доставки.
        """
        return await self(
            Tracking(
                avito_event_type=avito_event_type,
                avito_status=avito_status,
                comment=comment,
                date_=date_,
                location=location,
                options=options,
                order_id=order_id,
                provider_event_code=provider_event_code,
            )
        )

    async def prohibit_order_acceptance(self, order_id: str) -> ProhibitOrderAcceptanceReply:
        """Запрет приёма посылки от отправителя via ``POST /delivery-sandbox/prohibitOrderAcceptance``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(ProhibitOrderAcceptance(order_id=order_id))

    async def get_sorting_center(self, delivery_providers: str) -> SortingCenterGet:
        """Получить список сортировочных центров via ``GET /delivery-sandbox/sorting-center``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            delivery_providers: Список кодов служб доставки, сортировочные центры которых необходимо вернуть
        """
        return await self(GetSortingCenter(delivery_providers=delivery_providers))

    async def add_sorting_center(self) -> AddTaskReply:
        """Загрузить сортировочные центры via ``POST /delivery-sandbox/tariffs/sorting-center``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(AddSortingCenter())

    async def add_areas_sandbox(self, tariff_id: int) -> AddTariffReply:
        """Загрузить области доставки via ``POST /delivery-sandbox/tariffs/{tariff_id}/areas``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            tariff_id: id тарифа, к которому должны быть прикреплены добавляемые области
        """
        return await self(AddAreasSandbox(tariff_id=tariff_id))

    async def add_tags_to_sorting_center(self, tariff_id: int) -> AddTaskReply:
        """Установка тэгов своим и/или чужим сортировочным центрам via ``POST /delivery-sandbox/tariffs/{tariff_id}/tagged-sorting-centers``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            tariff_id: id своего тарифа, теги которого будут установлены для сортировочных центров
        """
        return await self(AddTagsToSortingCenter(tariff_id=tariff_id))

    async def add_terminals_sandbox(self, tariff_id: int) -> AddTerminalsReply:
        """Загрузить терминалы via ``POST /delivery-sandbox/tariffs/{tariff_id}/terminals``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            tariff_id: id тарифа, к которому должны быть прикреплены добавляемые терминалы
        """
        return await self(AddTerminalsSandbox(tariff_id=tariff_id))

    async def update_terms(self, tariff_id: int) -> UpdateTermsReply:
        """Обновить сроки по тарифу via ``POST /delivery-sandbox/tariffs/{tariff_id}/terms``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            tariff_id: id тарифа, к которому должны быть прикреплены добавляемые области
        """
        return await self(UpdateTerms(tariff_id=tariff_id))

    async def add_tariff_sandbox_v2(
        self,
        delivery_provider_tariff_id: str,
        directions: list[DirectionV2],
        name: str,
        tariff_zones: list[TariffZone],
        terms_zones: list[TermsZone],
        tariff_type: AddTariffSandboxV2TariffType | None = None,
    ) -> AddTaskReply:
        """Загрузить новый тариф v2 via ``POST /delivery-sandbox/tariffsV2``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            delivery_provider_tariff_id: Идентификатор тарифного плана на стороне службы доставки - должен быть уникален.
            directions: Список направлений доставки в тарифном плане
            name: Человекопонятное название тарифного плана
            tariff_type: Тип разделения тарифа по габаритам товаров. - MGT - малогабаритные товары - KGT - крупногабаритные товары Если поле не указано, то тариф должен содержать оба типа разделения (для обратной совместимости со старыми тарифами).
            tariff_zones: Список тарифных зон
            terms_zones: Список зон сроков
        """
        return await self(
            AddTariffSandboxV2(
                delivery_provider_tariff_id=delivery_provider_tariff_id,
                directions=directions,
                name=name,
                tariff_type=tariff_type,
                tariff_zones=tariff_zones,
                terms_zones=terms_zones,
            )
        )

    async def get_task(self, task_id: int) -> GetTaskReply:
        """Получение информации по задаче via ``GET /delivery-sandbox/tasks/{task_id}``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(GetTask(task_id=task_id))

    async def v1cancel_announcement(
        self, announcement_id: str, date_: TZDatetime, options: SandboxCancelAnnouncementOptions
    ) -> SandboxCancelAnnouncementReply:
        """Отправка события об отмене тестового анонса via ``POST /delivery-sandbox/v1/cancelAnnouncement``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            announcement_id: Уникальный идентификатор анонса UUID V4.
            date_: Дата события
        """
        return await self(
            V1cancelAnnouncement(announcement_id=announcement_id, date_=date_, options=options)
        )

    async def v1_cancel_parcel(
        self, parcel_id: str, options: CancelSandboxParcelOptions | None = None
    ) -> CancelSandboxParcelReply:
        """Отмена тестовой посылки via ``POST /delivery-sandbox/v1/cancelParcel``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(V1CancelParcel(options=options, parcel_id=parcel_id))

    async def v1change_parcel(
        self,
        parcel_id: str,
        type_: V1changeParcelType,
        application: ChangeParcelRequestApplication | None = None,
        options: ChangeParcelRequestOptions | None = None,
    ) -> ChangeParcelReply:
        """Создание заявки на изменение данных тестовой посылки via ``POST /delivery-sandbox/v1/changeParcel``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            parcel_id: Идентификатор посылки.
            type_: Тип заявки, которую необходимо зарегистрировать.
        """
        return await self(
            V1changeParcel(
                application=application, options=options, parcel_id=parcel_id, type_=type_
            )
        )

    async def v1create_announcement(
        self,
        announcement_id: str,
        announcement_type: V1createAnnouncementAnnouncementType,
        barcode: str,
        date_: TZDatetime,
        options: SandboxCreateAnnouncementOptions,
        packages: list[SandboxCreateAnnouncementPackage],
        receiver: SandboxCreateAnnouncementParticipant,
        sender: SandboxCreateAnnouncementParticipant,
    ) -> SandboxCreateAnnouncementReply:
        """Создание тестового анонса via ``POST /delivery-sandbox/v1/createAnnouncement``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            announcement_id: Уникальный идентификатор анонса UUID V4.
            announcement_type: Тип анонса.
            barcode: Штрихкод анонса.
            date_: Дата и время создания анонса (UTC).
            packages: Список грузомест.
        """
        return await self(
            V1createAnnouncement(
                announcement_id=announcement_id,
                announcement_type=announcement_type,
                barcode=barcode,
                date_=date_,
                options=options,
                packages=packages,
                receiver=receiver,
                sender=sender,
            )
        )

    async def v1get_announcement_event(
        self, announcement_id: str
    ) -> SandboxGetAnnouncementEventReply:
        """Получение последнего события тестового анонса via ``POST /delivery-sandbox/v1/getAnnouncementEvent``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            announcement_id: Уникальный идентификатор анонса UUID V4.
        """
        return await self(V1getAnnouncementEvent(announcement_id=announcement_id))

    async def v1get_change_parcel_info(self, application_id: str) -> GetChangeParcelInfoReply:
        """Получение информации об изменении тестовой посылки via ``POST /delivery-sandbox/v1/getChangeParcelInfo``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            application_id: Идентификатор заявки на изменение данных посылки
        """
        return await self(V1getChangeParcelInfo(application_id=application_id))

    async def v1get_parcel_info(self, parcel_id: str) -> GetSandboxParcelInfoReply:
        """Получение информации о тестовой посылке via ``POST /delivery-sandbox/v1/getParcelInfo``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(V1getParcelInfo(parcel_id=parcel_id))

    async def v1get_registered_parcel_id(self, order_id: str) -> GetRegisteredParcelIdReply:
        """Получение ID зарегистрированной тестовой посылки via ``POST /delivery-sandbox/v1/getRegisteredParcelID``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(V1getRegisteredParcelId(order_id=order_id))

    async def create_sandbox_parcel_v22(
        self,
        items: list[CreateSandboxParcelItem] | None = None,
        options: CreateSandboxV2Options | None = None,
        receiver: CreateSandboxParcelV22Receiver | None = None,
        sender: CreateSandboxParcelV22Sender | None = None,
        tags: list[str] | None = None,
    ) -> CreateParcelReply:
        """Создание тестовой посылки via ``POST /delivery-sandbox/v2/createParcel``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
        """
        return await self(
            CreateSandboxParcelV22(
                items=items, options=options, receiver=receiver, sender=sender, tags=tags
            )
        )

    async def change_parcel_result(
        self,
        id: str,
        status: ChangeParcelResultStatus,
        options: ChangeParcelResultOptions | None = None,
        reason: str | None = None,
    ) -> ChangeParcelResultReply:
        """Отправка результата исполнения заявки via ``POST /delivery/order/changeParcelResult``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            id: Идентификатор заявки на изменение посылки
            reason: Причина отклонения заявки (заполняется в случае отклонения).
            status: Статус обработки заявки
        """
        return await self(ChangeParcelResult(id=id, options=options, reason=reason, status=status))

    async def change_parcels(
        self, applications: list[ChangeParcelsApplication], type_: ChangeParcelsType
    ) -> ChangeParcelsResponse:
        """Обновление свойств посылок via ``POST /sandbox/changeParcels``.

        See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

        Args:
            type_: Тип заявки. Заявки могут быть следующих типов: - `changeReceiver` - обновить данные о получателе посылки. - `extendParcelStorage` - продлить срок хранения посылки. - `prohibitParcelReceive` - запретить выдачу посылки на ПВЗ вручения. - `prohibitParcelAcceptance` - запретить прием посылки на ПВЗ отправки (в разработке). - `changeReceiverTerminalOnConfirmed` - обновить ПВЗ вручения.
        """
        return await self(ChangeParcels(applications=applications, type_=type_))
