# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Авито.Работа — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..enums.job import (
    ApplyProcessingAdditionalQuestions,
    ApplyProcessingApplyType,
    BonusesValue,
    CitizenshipCriteriaValue,
    ConstructionWorkTypeValue,
    CuisineValue,
    DrivingLicenseCategoryValue,
    EateryTypeValue,
    FacilityTypeValue,
    FoodProductionShopTypeValue,
    Grade,
    MedicalBookVacancy,
    PaidPeriod,
    RegistrationMethodValue,
    ResumeGetItemFields,
    ResumeGetItemParams,
    ResumesGetBusinessTripReadiness,
    ResumesGetDriverLicence,
    ResumesGetDriverLicenceCategory,
    ResumesGetDrivingExperience,
    ResumesGetEducationLevel,
    ResumesGetFields,
    ResumesGetGender,
    ResumesGetMedicalBook,
    ResumesGetOwnTransport,
    ResumesGetRelocationReadiness,
    ResumesGetSchedule,
    RetailEquipmentTypeValue,
    RetailShopTypeValue,
    Taxes,
    ToolsAvailability,
    VacanciesGetByIdsFields,
    VacanciesGetByIdsParams,
    VacancyCreate2AgePreferences,
    VacancyCreate2BillingType,
    VacancyCreate2DeliveryMethod,
    VacancyCreate2Description,
    VacancyCreate2DrivingExperienceId,
    VacancyCreate2ExperienceId,
    VacancyCreate2PayoutFrequencyId,
    VacancyCreate2ScheduleId,
    VacancyCreate2WorkFormat,
    VacancyCreateV2AgePreferences,
    VacancyCreateV2BillingType,
    VacancyCreateV2DeliveryMethod,
    VacancyCreateV2Description,
    VacancyCreateV2DrivingExperience,
    VacancyCreateV2Experience,
    VacancyCreateV2PayoutFrequency,
    VacancyCreateV2Programs,
    VacancyCreateV2Schedule,
    VacancyCreateV2WorkFormat,
    VacancyEducationLevel,
    VacancyGetItemFields,
    VacancyGetItemParams,
    VacancyProlongate2BillingType,
    VacancyUpdate2AgePreferences,
    VacancyUpdate2BillingType,
    VacancyUpdate2DeliveryMethod,
    VacancyUpdate2Description,
    VacancyUpdate2DrivingExperienceId,
    VacancyUpdate2ExperienceId,
    VacancyUpdate2PayoutFrequencyId,
    VacancyUpdate2WorkFormat,
    VacancyUpdateV2AgePreferences,
    VacancyUpdateV2BillingType,
    VacancyUpdateV2DeliveryMethod,
    VacancyUpdateV2Description,
    VacancyUpdateV2DrivingExperience,
    VacancyUpdateV2Experience,
    VacancyUpdateV2PayoutFrequency,
    VacancyUpdateV2Programs,
    VacancyUpdateV2Schedule,
    VacancyUpdateV2WorkFormat,
    WorkerClassValue,
)
from ..methods.job import (
    ApplicationsApplyActions,
    ApplicationsGetByIds,
    ApplicationsGetIds,
    ApplicationsGetStates,
    ApplicationsSetIsViewed,
    ApplicationsWebhookDelete,
    ApplicationsWebhookGet,
    ApplicationsWebhookPut,
    ApplicationsWebhooksGet,
    GetDictById,
    GetDicts,
    ResumeGetContacts,
    ResumeGetItem,
    ResumesGet,
    SearchVacancy,
    VacanciesGetByIds,
    VacancyArchive2,
    VacancyAutoRenewal2,
    VacancyCreate2,
    VacancyCreateV2,
    VacancyGetItem,
    VacancyGetStatuses,
    VacancyProlongate2,
    VacancyUpdate2,
    VacancyUpdateV2,
)
from ..models.common import TZDatetime
from ..models.job import (
    AgeCriteria,
    ApplicationsGetStatesResult,
    ApplicationsSetIsViewedApplies,
    ApplicationsWebhookDeleteResponse,
    ApplyProcessing,
    Contacts,
    Coordinates,
    GetApplicationsByIdsResult,
    GetApplicationsIdsResult,
    LocationAddress,
    Phone,
    Resume20,
    ResumeContacts,
    ResumesGetRadius,
    ResumesGetRadiusPoint,
    ResumesGetResponse,
    SalaryDetail,
    SalaryDetailBase,
    SearchVacancyResponse,
    SetApplicationsIsViewedResult,
    Vacancies20,
    Vacancy20,
    VacancyCreate2DrivingExperience,
    VacancyCreate2Experience,
    VacancyCreate2PayoutFrequency,
    VacancyCreate2SalaryRange,
    VacancyCreate2Schedule,
    VacancyCreateResult,
    VacancyCreateV2Contacts,
    VacancyCreateV2Hierarchy,
    VacancyCreateV2Location,
    VacancyCreateV2Salary,
    VacancyStatusesResult,
    VacancyUpdate2DrivingExperience,
    VacancyUpdate2Experience,
    VacancyUpdate2PayoutFrequency,
    VacancyUpdate2SalaryRange,
    VacancyUpdateV2Contacts,
    VacancyUpdateV2Hierarchy,
    VacancyUpdateV2Location,
    VacancyUpdateV2Salary,
    WebhooksSubscriptionResultList,
    WebhookSubscribeRequestBody,
)
from ._base import FacadeBase


class JobFacade(FacadeBase):
    """``Client`` mixin — Авито.Работа endpoints."""

    async def applications_apply_actions(
        self, action: str, ids: list[str]
    ) -> GetApplicationsIdsResult:
        """Батчевая смена статуса откликов via ``POST /job/v1/applications/apply_actions``.

        Args:
            action: Новый статус отклика, который нужно применить
            ids: Список идентификаторов откликов, к которым нужно применить статус
        """
        return await self(ApplicationsApplyActions(action=action, ids=ids))

    async def applications_get_by_ids(
        self, ids: list[str] | None = None
    ) -> GetApplicationsByIdsResult:
        """Получение списка откликов via ``POST /job/v1/applications/get_by_ids``."""
        return await self(ApplicationsGetByIds(ids=ids))

    async def applications_get_ids(
        self,
        updated_at_from: str | None = None,
        created_at_from: str | None = None,
        cursor: str | None = None,
        vacancy_ids: str | None = None,
        is_viewed: bool | None = None,
        state: str | None = None,
    ) -> GetApplicationsIdsResult:
        """Получение идентификаторов откликов via ``GET /job/v1/applications/get_ids``.

        Args:
            updated_at_from: Фильтр по дате обновления (от). Обязателен, если не указан updatedAtFrom. Формат YYYY-MM-DD.
            created_at_from: Фильтр по дате создания (от). Обязателен, если не указан createdAtFrom. Формат YYYY-MM-DD.
            cursor: Идентификатор последнего отклика из предыдущего запроса Пример использования параметра: Получение первой страницы откликов, с датой обновления от 12 июня 2022 года: GET /job/v1/applications/get_ids?updatedAtFrom=2022-06-12 [ &nbsp{\"id\": \"62e3e7e542c3d9af3d85205e\", }, &nbsp , &nbsp{\"id\": \" 623850d1d3819d935dd02702 \", } ] Получение следующей страницы откликов: GET /job/v1/applications/get_ids?updatedAtFrom=2022-06-12&cursor= 623850d1d3819d935dd02702
            vacancy_ids: Идентификаторы вакансий. Опциональный фильтр (можно указать одно или несколько значений через запятую)
            is_viewed: Отклик просмотрен
            state: Статус отклика. Опциональный фильтр по текущему статусу отклика
        """
        return await self(
            ApplicationsGetIds(
                updated_at_from=updated_at_from,
                created_at_from=created_at_from,
                cursor=cursor,
                vacancy_ids=vacancy_ids,
                is_viewed=is_viewed,
                state=state,
            )
        )

    async def applications_get_states(self) -> ApplicationsGetStatesResult:
        """Получение списка возможных статусов откликов via ``GET /job/v1/applications/get_states``."""
        return await self(ApplicationsGetStates())

    async def applications_set_is_viewed(
        self, applies: list[ApplicationsSetIsViewedApplies] | None = None
    ) -> SetApplicationsIsViewedResult:
        """Изменение статуса отклика via ``POST /job/v1/applications/set_is_viewed``.

        Args:
            applies: Список откликов
        """
        return await self(ApplicationsSetIsViewed(applies=applies))

    async def applications_webhook_delete(
        self, url: str | None = None
    ) -> ApplicationsWebhookDeleteResponse:
        """Отключение уведомлений по откликам (webhook) via ``DELETE /job/v1/applications/webhook``.

        Args:
            url: URL, на который отправляются уведомления
        """
        return await self(ApplicationsWebhookDelete(url=url))

    async def applications_webhook_get(self) -> WebhookSubscribeRequestBody:
        """Получение информации о подписках (webhook) via ``GET /job/v1/applications/webhook``."""
        return await self(ApplicationsWebhookGet())

    async def applications_webhook_put(self, secret: str, url: str) -> WebhookSubscribeRequestBody:
        """Включение уведомлений по откликам (webhook) via ``PUT /job/v1/applications/webhook``.

        Args:
            secret: сгенерированный ключ
            url: URL на который будут отправляться уведомления
        """
        return await self(ApplicationsWebhookPut(secret=secret, url=url))

    async def applications_webhooks_get(self) -> WebhooksSubscriptionResultList:
        """Получение списка подписок (webhook) via ``GET /job/v1/applications/webhooks``."""
        return await self(ApplicationsWebhooksGet())

    async def resumes_get(
        self,
        max_distance: int,
        min_distance: int,
        point: ResumesGetRadiusPoint,
        per_page: int = 25,
        page: int = 1,
        cursor: int | None = None,
        fields: ResumesGetFields | None = None,
        query: str | None = None,
        location: int | None = None,
        metro: int | None = None,
        district: int | None = None,
        specialization: int | None = None,
        schedule: ResumesGetSchedule | None = None,
        business_trip_readiness: ResumesGetBusinessTripReadiness | None = None,
        relocation_readiness: ResumesGetRelocationReadiness | None = None,
        gender: ResumesGetGender | None = None,
        age_min: int = 14,
        age_max: int = 99,
        education_level: ResumesGetEducationLevel | None = None,
        experience_min: int = 0,
        experience_max: int = 50,
        salary_min: int = 0,
        salary_max: int | None = None,
        updated_at: TZDatetime | None = None,
        updated_from: TZDatetime | None = None,
        updated_to: TZDatetime | None = None,
        nationality: int | None = None,
        driver_licence: ResumesGetDriverLicence | None = None,
        driver_licence_category: ResumesGetDriverLicenceCategory | None = None,
        driving_experience: ResumesGetDrivingExperience | None = None,
        own_transport: ResumesGetOwnTransport | None = None,
        medical_book: ResumesGetMedicalBook | None = None,
    ) -> ResumesGetResponse:
        """Поиск резюме via ``GET /job/v1/resumes/``.

        Args:
            per_page: Количество записей на странице (положительное число от 1 до 100)
            page: Номер страницы (положительное число больше 0, произведение page на per_page не должно превышать 5000)
            cursor: Курсор поиска (если не указан, будет начат новый поиск и его курсор будет возвращен в ответе)
            fields: Поля ответа (можно указать несколько значений через запятую)
            query: Поисковая фраза
            location: Идентификатор региона поиска (можно указать несколько значений через запятую) Метод принимает идентификаторы сущностей Region и City из [справочника](https://autoload.avito.ru/format/Locations.xml).
            metro: Идентификатор метро поиска (можно указать несколько значений через запятую) Метод принимает идентификаторы сущности Subway из [справочника](https://autoload.avito.ru/format/Locations.xml).
            district: Идентификатор района поиска (можно указать несколько значений через запятую) Метод принимает идентификаторы сущности District из [справочника](https://autoload.avito.ru/format/Locations.xml).
            max_distance: Максимальное расстояние от центра в метрах, значение от 0 до 100_000
            min_distance: Минимальное расстояние от центра в метрах, значение от 0 до 10_000
            point: Географические координаты (для указания точки на карте), в градусах — десятичные дроби
            specialization: Идентификатор сферы деятельности (можно указать несколько значений через запятую) Возможные значения: - 10166 - IT, интернет, телеком - 10167 - Медицина, фармацевтика - 10168 - Продажи - 10169 - Страхование - 10170 - Транспорт, логистика - 10171 - Образование, наука - 10172 - Строительство - 10173 - Туризм, рестораны - 10174 - Фитнес, салоны красоты - 10175 - Без опыта, студенты - 10180 - Автомобильный бизнес - 10181 - Бухгалтерия, финансы - 10182 - Высший менеджмент - 10183 - Госслужба, НКО - 10184 - ЖКХ, эксплуатация - 10185 - Искусство, развлечения - 10186 - Консультирование - 10187 - Маркетинг, реклама, PR - 10188 - Охрана, безопасность - 10189 - Управление персоналом - 10190 - Юриспруденция - 10191 - Административная работа - 10192 - Банки, инвестиции - 10193 - Производство, сырьё, с/х - 16844 - Домашний персонал - 2804251 - Курьерская доставка - 2804250 - Такси
            schedule: График работы (можно указать несколько значений через запятую) Возможные значения: - partial-day - Неполный рабочий день - full-day - Полный рабочий день - fly-in-fly-out - Вахтовый метод - flexible - Гибкий график - shift - Сменный график - remote - Удаленная работа
            business_trip_readiness: Готовность к командировкам (можно указать несколько значений через запятую) Возможные значения: - ready - Готов - never - Не готов - sometimes - Иногда
            relocation_readiness: Готовность к переезду (можно указать несколько значений через запятую) Возможные значения: - possible - Возможен - never - Невозможен
            gender: Пол (можно указать несколько значений через запятую) Возможные значения: - female - Женщина - male - Мужчина
            age_min: Минимальный возраст (включительно, положительное число от 14 до 99)
            age_max: Максимальный возраст (включительно, положительное число от 18 до 99)
            education_level: Уровень образования (можно указать несколько значений через запятую) Возможные значения: - higher - Высшее - unfinished-higher - Неоконченное высшее - secondary - Среднее - special-secondary - Среднее специальное
            experience_min: Минимальный стаж работы (включительно, положительное число от 0 до 50)
            experience_max: Максимальный стаж работы (включительно, положительное число от 0 до 50)
            salary_min: Минимальный размер заработной платы (включительно, положительное число)
            salary_max: Максимальный размер заработной платы (включительно, положительное число)
            updated_at: Дата последнего обновления (от updated_at до текущей даты)
            updated_from: Дата последнего обновления (от updated_at)
            updated_to: Дата последнего обновления (до updated_at)
            nationality: Идентификатор гражданства(можно указать несколько значений через запятую) см. идентификаторы гражданства в [справочнике](https://www.avito.st/s/openapi/catalog_nationality.xml) Распространенные значения: - 15973 - Россия - 15974 - Украина - 15975 - Белоруссия - 15979 - Азербайджан - 15985 - Армения - 16020 - Грузия - 15976 - Казахстан - 16046 - Киргизия - 16082 - Молдавия - 16129 - Таджикистан - 16140 - Узбекистан
            driver_licence: Водительское удостоверение Возможные значения: - yes - Удостоверение есть - no - Удостоверения нет
            driver_licence_category: Категория водительского удостоверения (можно указать несколько значений через запятую) Возможные значения: - a - b - be - c - ce - d - de - m - tm - tb
            driving_experience: Стаж вождения (можно указать несколько значений через запятую) Возможные значения: - less-than-three-years - Стаж вождения меньше трех лет - more-than-three-years - Стаж вождения больше трех лет
            own_transport: Свой транспорт (можно указать несколько значений через запятую) Возможные значения: - no - Нет - car - Легковое авто - cargo-car - Грузовое авто - bike - Мотоцикл - scooter - Мопед
            medical_book: Медкнижка Возможные значения: - yes - Медкнижка есть - no - Медкнижки нет
        """
        return await self(
            ResumesGet(
                per_page=per_page,
                page=page,
                cursor=cursor,
                fields=fields,
                query=query,
                location=location,
                metro=metro,
                district=district,
                radius=ResumesGetRadius(
                    max_distance=max_distance, min_distance=min_distance, point=point
                ),
                specialization=specialization,
                schedule=schedule,
                business_trip_readiness=business_trip_readiness,
                relocation_readiness=relocation_readiness,
                gender=gender,
                age_min=age_min,
                age_max=age_max,
                education_level=education_level,
                experience_min=experience_min,
                experience_max=experience_max,
                salary_min=salary_min,
                salary_max=salary_max,
                updated_at=updated_at,
                updated_from=updated_from,
                updated_to=updated_to,
                nationality=nationality,
                driver_licence=driver_licence,
                driver_licence_category=driver_licence_category,
                driving_experience=driving_experience,
                own_transport=own_transport,
                medical_book=medical_book,
            )
        )

    async def resume_get_contacts(
        self, resume_id: int, employee_id: int | None = None
    ) -> ResumeContacts:
        """Доступ к контактным данным соискателя via ``GET /job/v1/resumes/{resume_id}/contacts/``.

        Args:
            resume_id: Идентификатор резюме
            employee_id: Идентификатор сотрудника компании в рамках иерархии аккаунтов. Используется для возможности списать контакт с лимита на покупку резюме для указанного сотрудника.
        """
        return await self(ResumeGetContacts(resume_id=resume_id, employee_id=employee_id))

    async def vacancy_create2(
        self,
        billing_type: VacancyCreate2BillingType,
        business_area: int,
        latitude: float,
        longitude: float,
        description: VacancyCreate2Description,
        id: VacancyCreate2DrivingExperienceId,
        employment: str,
        experience_id: VacancyCreate2ExperienceId,
        name: str,
        payout_frequency_id: VacancyCreate2PayoutFrequencyId,
        schedule_id: VacancyCreate2ScheduleId,
        address: str | None = None,
        administrator_organization_type: int | None = None,
        from_: int | None = None,
        to: int | None = None,
        age_preferences: list[VacancyCreate2AgePreferences] | None = None,
        allow_calls: bool | None = None,
        allow_messages: bool | None = None,
        additional_questions: list[ApplyProcessingAdditionalQuestions] | None = None,
        apply_type: ApplyProcessingApplyType | None = None,
        bonuses: list[BonusesValue] | None = None,
        citizenship: list[CitizenshipCriteriaValue] | None = None,
        construction_work_type: list[ConstructionWorkTypeValue] | None = None,
        email: str | None = None,
        contacts_name: str | None = None,
        phone: Phone | None = None,
        cuisine: list[CuisineValue] | None = None,
        custom_employer_name: str | None = None,
        delivery_method: list[VacancyCreate2DeliveryMethod] | None = None,
        driving_license_category: list[DrivingLicenseCategoryValue] | None = None,
        eatery_type: list[EateryTypeValue] | None = None,
        education_level: VacancyEducationLevel | None = None,
        employee_id: int | None = None,
        facility_type: list[FacilityTypeValue] | None = None,
        food_production_shop_type: list[FoodProductionShopTypeValue] | None = None,
        grade: Grade | None = None,
        html_tags: bool | None = None,
        image_url: str | None = None,
        is_company_car: bool | None = None,
        is_side_job: bool | None = None,
        medical_book: MedicalBookVacancy | None = None,
        medical_specialization: list[str] | None = None,
        medical_specialization_ids: list[int] | None = None,
        profession: int | None = None,
        registration_method: list[RegistrationMethodValue] | None = None,
        retail_equipment_type: list[RetailEquipmentTypeValue] | None = None,
        retail_shop_type: list[RetailShopTypeValue] | None = None,
        salary: int | None = None,
        base: SalaryDetailBase | None = None,
        paid_period: PaidPeriod | None = None,
        taxes: Taxes | None = None,
        salary_range_from_: int | None = None,
        salary_range_to: int | None = None,
        shifts: list[int] | None = None,
        tools_availability: ToolsAvailability | None = None,
        vacancy_code: str | None = None,
        vehicle_type: int | None = None,
        work_days_per_week: list[int] | None = None,
        work_format: list[VacancyCreate2WorkFormat] | None = None,
        work_hours_per_day: list[int] | None = None,
        worker_class: list[WorkerClassValue] | None = None,
    ) -> VacancyCreateResult:
        """Публикация вакансии via ``POST /job/v1/vacancies``.

        Args:
            address: Полный адрес объекта (строка длиной от 1 до 256 символов). Обязательное, если не указаны координаты.
            age_preferences: Блок \"в том числе для кандидатов\" (массив строк) Возможные значения элементов массива: - \"olderThan45\" - старше 45 лет; - \"olderThan14\" - от 14 лет; - \"olderThan16\" - от 16 лет; - \"withHealthProblems\" - с нарушениями здоровья; - \"students\" - для студентов; - \"pensioners\" - для пенсионеров.
            allow_messages: Возможность откликнуться на вакансию через сайт. Если передается apply_processing, то значение allow_messages будет игнорироваться и равно true.
            additional_questions: *DEPRECATED* Заполнение поля не влияет на вакансию. Массив со списком дополнительных вопросов, которые задаст ассистент Авито. - `experience` - вопрос про опыт работы. В качестве критерия будет использоваться значение поля `experience`. В результатах опроса ассистент отметит, достаточно у кандидата опыта или нет. - `citizenship` - вопрос про гражданство. В качестве критерия будет использоваться значение поля `citizenship`, если оно заполнено. - `age` - вопрос про возраст. В качестве критерия будет использоваться значение поля `age`, если оно заполнено.
            apply_type: Принимает два значения: - `with_assistant` - на вакансию смогут откликнуться кандидаты с резюме и без. - `only_with_resume` - на вакансию смогут откликаться только кандидаты с резюме. Если у кандидата нет резюме, Авито поможет создать его и откликнуться на вакансию
            billing_type: Вариант платного размещения Возможные значения: - \"package\" - размещение объявления осуществляется только при наличии подходящего пакета размещения - \"packageOrSingle\" - при наличии подходящего пакета оплата размещения объявления произойдет с него; если нет подходящего пакета, но достаточно денег на кошельке Авито, то произойдет разовое размещение - \"single\" - только разовое размещение, произойдет при наличии достаточной суммы на кошельке Авито; если есть подходящий пакет размещения, он будет проигнорирован
            email: Email контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использована почта из Профиля Сотрудника. При публикации от Компании или Пользователя будет использоваться почта из Профиля, переданное значение будет проигнорировано.
            contacts_name: Имя менеджера, контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использовано \"Имя сотрудника, которое видят пользователи при просмотре объявления\". При публикации от Компании или Пользователя не заполняется, переданное значение будет проигнорировано.
            latitude: Широта
            longitude: Долгота
            custom_employer_name: Название компании (строка длиной до 60 символов)
            delivery_method: Способ доставки
            description: Описание вакансии (строка длиной от 1 до 5000 символов) Поддерживает html-тэги `p`, `ul`, `ol`, `li`, `br`, `strong`, `em`
            employee_id: employee_id - Идентификатор сотрудника на Авито. Если этот параметр указан, то вакансия будет закреплена за сотрудником и с его баланса в Avito Pro будет списано размещение. Использовать параметр можно только с billing_type равным package. Сотрудник должен быть активен.
            employment: Занятость Возможные значения: - temporary - Временная - full - Полная - partial - Частичная Если ничего не выбрать то будет автоматически проставляться в зависимости от режима работы: При flexible и partTime, тип занятости - partial. Для всех остальных full. deprecated значение internship будет заменено на temporary
            image_url: URL-адрес логотипа вакансии. Ссылка на файл должна быть прямой | (при переходе не открываются элементы другого сайта (логотипы, кнопки или другие детали интерфейса) и не запрашивается логин и пароль) и доступной для IP 185.89.12.0/22, 146.158.48.0/21, 185.79.237.224/28 и 87.245.204.32/28;
            is_company_car: Предоставляет ли компания автомобиль
            is_side_job: Подработка
            name: Название вакансии (строка длиной от 1 до 50 символов)
            salary: Зарплата, рублей в месяц, если заполнено вместе с salary_range, то приоритет у salary_range
            base: Оклад
            salary_range_from_: Нижняя граница зарплаты, рублей в месяц
            salary_range_to: Верхняя граница зарплаты, рублей в месяц
            vacancy_code: Внутренний идентификатор вакансии или номер заявки на подбор, максимум 150 символов
            work_format: Блок \"Формат работы\" (массив строк) Возможные значения элементов массива: - \"office\" - В офисе или на объекте; - \"remote\" - Удалённо; - \"gibrid\" - Гибрид.
        """
        return await self(
            VacancyCreate2(
                address=address,
                administrator_organization_type=administrator_organization_type,
                age=AgeCriteria(from_=from_, to=to),
                age_preferences=age_preferences,
                allow_calls=allow_calls,
                allow_messages=allow_messages,
                apply_processing=ApplyProcessing(
                    additional_questions=additional_questions, apply_type=apply_type
                ),
                billing_type=billing_type,
                bonuses=bonuses,
                business_area=business_area,
                citizenship=citizenship,
                construction_work_type=construction_work_type,
                contacts=Contacts(email=email, name=contacts_name, phone=phone),
                coordinates=Coordinates(latitude=latitude, longitude=longitude),
                cuisine=cuisine,
                custom_employer_name=custom_employer_name,
                delivery_method=delivery_method,
                description=description,
                driving_experience=VacancyCreate2DrivingExperience(id=id),
                driving_license_category=driving_license_category,
                eatery_type=eatery_type,
                education_level=education_level,
                employee_id=employee_id,
                employment=employment,
                experience=VacancyCreate2Experience(id=experience_id),
                facility_type=facility_type,
                food_production_shop_type=food_production_shop_type,
                grade=grade,
                html_tags=html_tags,
                image_url=image_url,
                is_company_car=is_company_car,
                is_side_job=is_side_job,
                medical_book=medical_book,
                medical_specialization=medical_specialization,
                medical_specialization_ids=medical_specialization_ids,
                name=name,
                payout_frequency=VacancyCreate2PayoutFrequency(id=payout_frequency_id),
                profession=profession,
                registration_method=registration_method,
                retail_equipment_type=retail_equipment_type,
                retail_shop_type=retail_shop_type,
                salary=salary,
                salary_detail=SalaryDetail(base=base, paid_period=paid_period, taxes=taxes),
                salary_range=VacancyCreate2SalaryRange(
                    from_=salary_range_from_, to=salary_range_to
                ),
                schedule=VacancyCreate2Schedule(id=schedule_id),
                shifts=shifts,
                tools_availability=tools_availability,
                vacancy_code=vacancy_code,
                vehicle_type=vehicle_type,
                work_days_per_week=work_days_per_week,
                work_format=work_format,
                work_hours_per_day=work_hours_per_day,
                worker_class=worker_class,
            )
        )

    async def vacancy_archive2(self, vacancy_id: int, employee_id: int | None = None) -> None:
        """Остановка публикации вакансии via ``PUT /job/v1/vacancies/archived/{vacancy_id}``.

        Args:
            vacancy_id: Идентификатор вакансии на сайте
            employee_id: employee_id - Идентификатор сотрудника на Авито. Сотрудник может останавливать только закрепленные за ним вакансии в Avito Pro. Сотрудник должен быть в активен.
        """
        return await self(VacancyArchive2(vacancy_id=vacancy_id, employee_id=employee_id))

    async def vacancy_update2(
        self,
        vacancy_id: int,
        billing_type: VacancyUpdate2BillingType,
        latitude: float,
        longitude: float,
        id: VacancyUpdate2DrivingExperienceId,
        experience_id: VacancyUpdate2ExperienceId,
        payout_frequency_id: VacancyUpdate2PayoutFrequencyId,
        address: str | None = None,
        administrator_organization_type: int | None = None,
        from_: int | None = None,
        to: int | None = None,
        age_preferences: list[VacancyUpdate2AgePreferences] | None = None,
        allow_calls: bool | None = None,
        allow_messages: bool | None = None,
        additional_questions: list[ApplyProcessingAdditionalQuestions] | None = None,
        apply_type: ApplyProcessingApplyType | None = None,
        bonuses: list[BonusesValue] | None = None,
        citizenship: list[CitizenshipCriteriaValue] | None = None,
        construction_work_type: list[ConstructionWorkTypeValue] | None = None,
        email: str | None = None,
        contacts_name: str | None = None,
        phone: Phone | None = None,
        cuisine: list[CuisineValue] | None = None,
        custom_employer_name: str | None = None,
        delivery_method: list[VacancyUpdate2DeliveryMethod] | None = None,
        description: VacancyUpdate2Description | None = None,
        driving_license_category: list[DrivingLicenseCategoryValue] | None = None,
        eatery_type: list[EateryTypeValue] | None = None,
        education_level: VacancyEducationLevel | None = None,
        employee_id: int | None = None,
        facility_type: list[FacilityTypeValue] | None = None,
        food_production_shop_type: list[FoodProductionShopTypeValue] | None = None,
        grade: Grade | None = None,
        html_tags: bool | None = None,
        image_url: str | None = None,
        is_company_car: bool | None = None,
        is_side_job: bool | None = None,
        medical_book: MedicalBookVacancy | None = None,
        medical_specialization: list[str] | None = None,
        medical_specialization_ids: list[int] | None = None,
        name: str | None = None,
        profession: int | None = None,
        registration_method: list[RegistrationMethodValue] | None = None,
        retail_equipment_type: list[RetailEquipmentTypeValue] | None = None,
        retail_shop_type: list[RetailShopTypeValue] | None = None,
        salary: int | None = None,
        base: SalaryDetailBase | None = None,
        paid_period: PaidPeriod | None = None,
        taxes: Taxes | None = None,
        salary_range_from_: int | None = None,
        salary_range_to: int | None = None,
        shifts: list[int] | None = None,
        tools_availability: ToolsAvailability | None = None,
        vacancy_code: str | None = None,
        vehicle_type: int | None = None,
        work_days_per_week: list[int] | None = None,
        work_format: list[VacancyUpdate2WorkFormat] | None = None,
        work_hours_per_day: list[int] | None = None,
        worker_class: list[WorkerClassValue] | None = None,
    ) -> None:
        """Редактирование вакансии via ``PUT /job/v1/vacancies/{vacancy_id}``.

        Args:
            vacancy_id: Идентификатор вакансии на сайте
            address: Полный адрес объекта (строка длиной от 0 до 256 символов)
            allow_messages: Возможность откликнуться на вакансию через сайт. Если передается apply_processing, то значение allow_messages будет игнорироваться и равно true.
            additional_questions: *DEPRECATED* Заполнение поля не влияет на вакансию. Массив со списком дополнительных вопросов, которые задаст ассистент Авито. - `experience` - вопрос про опыт работы. В качестве критерия будет использоваться значение поля `experience`. В результатах опроса ассистент отметит, достаточно у кандидата опыта или нет. - `citizenship` - вопрос про гражданство. В качестве критерия будет использоваться значение поля `citizenship`, если оно заполнено. - `age` - вопрос про возраст. В качестве критерия будет использоваться значение поля `age`, если оно заполнено.
            apply_type: Принимает два значения: - `with_assistant` - на вакансию смогут откликнуться кандидаты с резюме и без. - `only_with_resume` - на вакансию смогут откликаться только кандидаты с резюме. Если у кандидата нет резюме, Авито поможет создать его и откликнуться на вакансию
            billing_type: Вариант платного размещения Возможные значения: - \"package\" - размещение объявления осуществляется только при наличии подходящего пакета размещения - \"packageOrSingle\" - при наличии подходящего пакета оплата размещения объявления произойдет с него; если нет подходящего пакета, но достаточно денег на кошельке Авито, то произойдет разовое размещение - \"single\" - только разовое размещение, произойдет при наличии достаточной суммы на кошельке Авито; если есть подходящий пакет размещения, он будет проигнорирован
            email: Email контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использована почта из Профиля Сотрудника. При публикации от Компании или Пользователя будет использоваться почта из Профиля, переданное значение будет проигнорировано.
            contacts_name: Имя менеджера, контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использовано \"Имя сотрудника, которое видят пользователи при просмотре объявления\". При публикации от Компании или Пользователя не заполняется, переданное значение будет проигнорировано.
            latitude: Широта
            longitude: Долгота
            custom_employer_name: Название компании (строка длиной до 60 символов)
            delivery_method: Способ доставки
            description: Описание вакансии (строка длиной от 1 до 5000 символов) Поддерживает html-тэги `p`, `ul`, `ol`, `li`, `br`, `strong`, `em`
            employee_id: employee_id - Идентификатор сотрудника на Авито. Сотрудник может редактировать только закрепленные за ним вакансии в Avito Pro. Сотрудник должен быть в активен.
            image_url: URL-адрес логотипа вакансии. Ссылка на файл должна быть прямой | (при переходе не открываются элементы другого сайта (логотипы, кнопки или другие детали интерфейса) и не запрашивается логин и пароль) и доступной для IP 185.89.12.0/22, 146.158.48.0/21, 185.79.237.224/28 и 87.245.204.32/28;
            is_company_car: Предоставляет ли компания автомобиль
            is_side_job: Подработка
            name: Название вакансии (строка длиной от 0 до 50 символов)
            salary: Зарплата, рублей в месяц, если заполнено вместе с salary_range, то приоритет у salary_range
            base: Оклад
            salary_range_from_: Нижняя граница зарплаты, рублей в месяц
            salary_range_to: Верхняя граница зарплаты, рублей в месяц
            vacancy_code: Внутренний идентификатор вакансии или номер заявки на подбор, максимум 150 символов
            work_format: Блок \"Формат работы\" (массив строк) Возможные значения элементов массива: - \"office\" - В офисе или на объекте; - \"remote\" - Удалённо; - \"gibrid\" - Гибрид.
        """
        return await self(
            VacancyUpdate2(
                vacancy_id=vacancy_id,
                address=address,
                administrator_organization_type=administrator_organization_type,
                age=AgeCriteria(from_=from_, to=to),
                age_preferences=age_preferences,
                allow_calls=allow_calls,
                allow_messages=allow_messages,
                apply_processing=ApplyProcessing(
                    additional_questions=additional_questions, apply_type=apply_type
                ),
                billing_type=billing_type,
                bonuses=bonuses,
                citizenship=citizenship,
                construction_work_type=construction_work_type,
                contacts=Contacts(email=email, name=contacts_name, phone=phone),
                coordinates=Coordinates(latitude=latitude, longitude=longitude),
                cuisine=cuisine,
                custom_employer_name=custom_employer_name,
                delivery_method=delivery_method,
                description=description,
                driving_experience=VacancyUpdate2DrivingExperience(id=id),
                driving_license_category=driving_license_category,
                eatery_type=eatery_type,
                education_level=education_level,
                employee_id=employee_id,
                experience=VacancyUpdate2Experience(id=experience_id),
                facility_type=facility_type,
                food_production_shop_type=food_production_shop_type,
                grade=grade,
                html_tags=html_tags,
                image_url=image_url,
                is_company_car=is_company_car,
                is_side_job=is_side_job,
                medical_book=medical_book,
                medical_specialization=medical_specialization,
                medical_specialization_ids=medical_specialization_ids,
                name=name,
                payout_frequency=VacancyUpdate2PayoutFrequency(id=payout_frequency_id),
                profession=profession,
                registration_method=registration_method,
                retail_equipment_type=retail_equipment_type,
                retail_shop_type=retail_shop_type,
                salary=salary,
                salary_detail=SalaryDetail(base=base, paid_period=paid_period, taxes=taxes),
                salary_range=VacancyUpdate2SalaryRange(
                    from_=salary_range_from_, to=salary_range_to
                ),
                shifts=shifts,
                tools_availability=tools_availability,
                vacancy_code=vacancy_code,
                vehicle_type=vehicle_type,
                work_days_per_week=work_days_per_week,
                work_format=work_format,
                work_hours_per_day=work_hours_per_day,
                worker_class=worker_class,
            )
        )

    async def vacancy_prolongate2(
        self,
        vacancy_id: int,
        billing_type: VacancyProlongate2BillingType,
        employee_id: int | None = None,
    ) -> None:
        """Реактивация вакансии via ``POST /job/v1/vacancies/{vacancy_id}/prolongate``.

        Args:
            vacancy_id: Идентификатор вакансии на сайте
            billing_type: Вариант платного размещения Возможные значения: - \"package\" - размещение объявления осуществляется только при наличии подходящего пакета размещения - \"packageOrSingle\" - при наличии подходящего пакета оплата размещения объявления произойдет с него; если нет подходящего пакета, но достаточно денег на кошельке Авито, то произойдет разовое размещение - \"single\" - только разовое размещение, произойдет при наличии достаточной суммы на кошельке Авито; если есть подходящий пакет размещения, он будет проигнорирован
            employee_id: employee_id - Идентификатор сотрудника на Авито. Если этот параметр указан, то с баланса сотрудника в Avito Pro будет списано размещение. Использовать параметр можно только с billing_type равным package. Сотрудник должен быть в активен.
        """
        return await self(
            VacancyProlongate2(
                vacancy_id=vacancy_id, billing_type=billing_type, employee_id=employee_id
            )
        )

    async def resume_get_item(
        self,
        resume_id: int,
        fields: ResumeGetItemFields | None = None,
        params: ResumeGetItemParams | None = None,
        photos: bool = False,
    ) -> Resume20:
        """Просмотр данных резюме via ``GET /job/v2/resumes/{resume_id}``.

        Args:
            resume_id: Идентификатор резюме
            fields: Поля основного тела ответа (можно указать несколько значений через запятую). По умолчанию отображаются все поля.
            params: Дополнительные поля, которые входят в params (можно указать несколько значений через запятую). По умолчанию отображаются все поля.
            photos: Признак того, нужно ли отдавать картинки, по умолчанию false
        """
        return await self(
            ResumeGetItem(resume_id=resume_id, fields=fields, params=params, photos=photos)
        )

    async def search_vacancy(
        self,
        per_page: int = 25,
        page: int = 1,
        location: int | None = None,
        business_area: int | None = None,
        work_format: str | None = None,
        schedule: str | None = None,
    ) -> SearchVacancyResponse:
        """Поиск вакансий via ``GET /job/v2/vacancies``.

        Args:
            per_page: Количество записей на странице (положительное число от 10 до 100)
            page: Номер страницы (положительное число больше 0, произведение page на per_page не должно превышать 5000)
            location: Идентификатор региона поиска (можно указать несколько значений через запятую) Метод принимает идентификаторы сущностей Region и City из [справочника](https://autoload.avito.ru/format/Locations.xml).
            business_area: Идентификатор сферы деятельности Получить актуальный список доступных значений можно из справочника `business_area` через метод [getDictByID](/api-catalog/job/documentation#operation/getDictByID). Статичный [справочник](https://www.avito.st/s/openapi/catalog-business-area.xml) объявлен устаревшим и более не будет использоваться.
            work_format: Формат работы (можно указать несколько значений через запятую) Получить актуальный список доступных значений можно из справочника `work_format` через метод [getDictByID](/api-catalog/job/documentation#operation/getDictByID).
            schedule: Режим работы (можно указать несколько значений через запятую) Получить актуальный список доступных значений можно из справочника `schedules` через метод [getDictByID](/api-catalog/job/documentation#operation/getDictByID).
        """
        return await self(
            SearchVacancy(
                per_page=per_page,
                page=page,
                location=location,
                business_area=business_area,
                work_format=work_format,
                schedule=schedule,
            )
        )

    async def vacancy_create_v2(
        self,
        billing_type: VacancyCreateV2BillingType,
        administrator_organization_type: int | None = None,
        from_: int | None = None,
        to: int | None = None,
        age_preferences: list[VacancyCreateV2AgePreferences] | None = None,
        additional_questions: list[ApplyProcessingAdditionalQuestions] | None = None,
        apply_type: ApplyProcessingApplyType | None = None,
        bonuses: list[BonusesValue] | None = None,
        business_area: int | None = None,
        citizenship: list[CitizenshipCriteriaValue] | None = None,
        construction_work_type: list[ConstructionWorkTypeValue] | None = None,
        allow_calls: bool | None = None,
        allow_messages: bool | None = None,
        email: str | None = None,
        name: str | None = None,
        phone: str | None = None,
        cuisine: list[CuisineValue] | None = None,
        delivery_method: list[VacancyCreateV2DeliveryMethod] | None = None,
        description: VacancyCreateV2Description | None = None,
        driving_experience: VacancyCreateV2DrivingExperience | None = None,
        driving_license_category: list[DrivingLicenseCategoryValue] | None = None,
        eatery_type: list[EateryTypeValue] | None = None,
        education_level: VacancyEducationLevel | None = None,
        employment: str | None = None,
        experience: VacancyCreateV2Experience | None = None,
        facility_type: list[FacilityTypeValue] | None = None,
        food_production_shop_type: list[FoodProductionShopTypeValue] | None = None,
        grade: Grade | None = None,
        employee_id: int | None = None,
        image_url: str | None = None,
        is_company_car: bool | None = None,
        is_side_job: bool | None = None,
        address: LocationAddress | None = None,
        coordinates: Coordinates | None = None,
        medical_book: MedicalBookVacancy | None = None,
        medical_specialization: list[str] | None = None,
        medical_specialization_ids: list[int] | None = None,
        payout_frequency: VacancyCreateV2PayoutFrequency | None = None,
        profession: int | None = None,
        programs: list[VacancyCreateV2Programs] | None = None,
        registration_method: list[RegistrationMethodValue] | None = None,
        retail_equipment_type: list[RetailEquipmentTypeValue] | None = None,
        retail_shop_type: list[RetailShopTypeValue] | None = None,
        salary_from_: int | None = None,
        salary_to: int | None = None,
        base: SalaryDetailBase | None = None,
        paid_period: PaidPeriod | None = None,
        taxes: Taxes | None = None,
        schedule: VacancyCreateV2Schedule | None = None,
        shifts: list[int] | None = None,
        title: str | None = None,
        tools_availability: ToolsAvailability | None = None,
        vacancy_code: str | None = None,
        vehicle_type: int | None = None,
        work_days_per_week: list[int] | None = None,
        work_format: list[VacancyCreateV2WorkFormat] | None = None,
        work_hours_per_day: list[int] | None = None,
        worker_class: list[WorkerClassValue] | None = None,
    ) -> None:
        """Публикация вакансии v2 via ``POST /job/v2/vacancies``.

        Args:
            age_preferences: Блок \"в том числе для кандидатов\" (массив строк) Возможные значения элементов массива: - \"olderThan45\" - старше 45 лет; - \"olderThan14\" - от 14 лет; - \"olderThan16\" - от 16 лет; - \"withHealthProblems\" - с нарушениями здоровья; - \"students\" - для студентов; - \"pensioners\" - для пенсионеров.
            additional_questions: *DEPRECATED* Заполнение поля не влияет на вакансию. Массив со списком дополнительных вопросов, которые задаст ассистент Авито. - `experience` - вопрос про опыт работы. В качестве критерия будет использоваться значение поля `experience`. В результатах опроса ассистент отметит, достаточно у кандидата опыта или нет. - `citizenship` - вопрос про гражданство. В качестве критерия будет использоваться значение поля `citizenship`, если оно заполнено. - `age` - вопрос про возраст. В качестве критерия будет использоваться значение поля `age`, если оно заполнено.
            apply_type: Принимает два значения: - `with_assistant` - на вакансию смогут откликнуться кандидаты с резюме и без. - `only_with_resume` - на вакансию смогут откликаться только кандидаты с резюме. Если у кандидата нет резюме, Авито поможет создать его и откликнуться на вакансию
            billing_type: Вариант платного размещения Возможные значения: - \"package\" - размещение объявления осуществляется только при наличии подходящего пакета размещения - \"packageOrSingle\" - при наличии подходящего пакета оплата размещения объявления произойдет с него; если нет подходящего пакета, но достаточно денег на кошельке Авито, то произойдет разовое размещение
            business_area: Идентификатор сферы деятельности Получить актуальный список доступных значений можно из справочника `business_area` через метод [getDictByID](/api-catalog/job/documentation#operation/getDictByID).
            allow_messages: Возможность откликнуться на вакансию через сайт. Если передается apply_processing, то значение allow_messages будет игнорироваться и равно true
            email: Email контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использована почта из Профиля Сотрудника. При публикации от Компании или Пользователя будет использоваться почта из Профиля, переданное значение будет проигнорировано.
            name: Имя менеджера, контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использовано \"Имя сотрудника, которое видят пользователи при просмотре объявления\". При публикации от Компании или Пользователя не заполняется, переданное значение будет проигнорировано.
            phone: Контактный телефон, если не передать - подставляется номер из профиля который используется по умолчанию. Если передать номер телефона которого нет в профиле, то он будет добавлен в профиль, но по нему необходимо будет пройти верификацию. Если номер телефона принадлежит другому пользователю, то вакансия не будет опубликована. Если вакансия публикуется от имени сотрудника и номер телефона ему не принадлежит - объявление так же не будет опубликовано.
            delivery_method: Способ доставки
            description: Описание вакансии (строка длиной от 1 до 5000 символов) Можно использовать HTML-теги в тексте. Поддерживаемые тэги - `p`, `ul`, `ol`, `li`, `br`, `strong`, `em`
            driving_experience: Стаж вождения
            employment: Занятость Возможные значения: - temporary - Временная - full - Полная - partial - Частичная Если ничего не выбрать то будет автоматически проставляться в зависимости от графика работы: При flexible и partTime, тип занятости - partial. ßДля всех остальных full. deprecated значение internship будет заменено на temporary
            experience: Опыт работы
            employee_id: Идентификатор сотрудника на Авито
            image_url: URL-адрес логотипа вакансии. Ссылка на файл должна быть прямой | (при переходе не открываются элементы другого сайта (логотипы, кнопки или другие детали интерфейса) и не запрашивается логин и пароль) и доступной для IP 185.89.12.0/22, 146.158.48.0/21, 185.79.237.224/28 и 87.245.204.32/28;
            is_company_car: Предоставляет ли компания автомобиль
            is_side_job: Подработка
            payout_frequency: Частота выплат Возможные значения: - \"dailyPay\" - Каждый день; - \"biweeklyPay\" - Дважды в месяц; - \"weeklyPay\" - Раз в неделю; - \"thriceMonthlyPay\" - три раза в месяц; - \"monthlyPay\" - Раз в месяц. Для paid_period равным month и week недоступно для выбора dailyPay. deprecated значение hourlyPay будет заменено на dailyPay
            programs: Блок участие вакансии в программах (массив строк) Если у компании от лица которой создается вакансия нет всех необходимых разрешений на участие, программа у вакансии не будет включена. Возможные значения элементов массива: - \"chastyeVyplaty\" - Частые выплаты.
            salary_from_: Нижняя граница зарплаты, рублей в месяц
            salary_to: Верхняя граница зарплаты, рублей в месяц
            base: Оклад
            schedule: Режим работы Возможные значения: - flyInFlyOut - Вахта - fixed - Фиксированный - flexible - Гибкий - shift - Сменный flyInFlyOut - Вахта, при выборе данного режима работы, адрес вакансии может быть только \"Город\", если адрес передается полноценный, то улица будет отрезана и адрес будет до \"Города\". deprecated значения fiveDay, sixDay, partTime, fullDay и remote будут заменены на fixed
            title: Название вакансии (строка длиной от 1 до 50 символов)
            vacancy_code: Внутренний идентификатор вакансии или номер заявки на подбор, максимум 150 символов
            work_format: Блок \"Формат работы\" (массив строк) Возможные значения элементов массива: - \"office\" - В офисе или на объекте; - \"remote\" - Удалённо; - \"gibrid\" - Гибрид.
        """
        return await self(
            VacancyCreateV2(
                administrator_organization_type=administrator_organization_type,
                age=AgeCriteria(from_=from_, to=to),
                age_preferences=age_preferences,
                apply_processing=ApplyProcessing(
                    additional_questions=additional_questions, apply_type=apply_type
                ),
                billing_type=billing_type,
                bonuses=bonuses,
                business_area=business_area,
                citizenship=citizenship,
                construction_work_type=construction_work_type,
                contacts=VacancyCreateV2Contacts(
                    allow_calls=allow_calls,
                    allow_messages=allow_messages,
                    email=email,
                    name=name,
                    phone=phone,
                ),
                cuisine=cuisine,
                delivery_method=delivery_method,
                description=description,
                driving_experience=driving_experience,
                driving_license_category=driving_license_category,
                eatery_type=eatery_type,
                education_level=education_level,
                employment=employment,
                experience=experience,
                facility_type=facility_type,
                food_production_shop_type=food_production_shop_type,
                grade=grade,
                hierarchy=VacancyCreateV2Hierarchy(employee_id=employee_id),
                image_url=image_url,
                is_company_car=is_company_car,
                is_side_job=is_side_job,
                location=VacancyCreateV2Location(address=address, coordinates=coordinates),
                medical_book=medical_book,
                medical_specialization=medical_specialization,
                medical_specialization_ids=medical_specialization_ids,
                payout_frequency=payout_frequency,
                profession=profession,
                programs=programs,
                registration_method=registration_method,
                retail_equipment_type=retail_equipment_type,
                retail_shop_type=retail_shop_type,
                salary=VacancyCreateV2Salary(from_=salary_from_, to=salary_to),
                salary_detail=SalaryDetail(base=base, paid_period=paid_period, taxes=taxes),
                schedule=schedule,
                shifts=shifts,
                title=title,
                tools_availability=tools_availability,
                vacancy_code=vacancy_code,
                vehicle_type=vehicle_type,
                work_days_per_week=work_days_per_week,
                work_format=work_format,
                work_hours_per_day=work_hours_per_day,
                worker_class=worker_class,
            )
        )

    async def vacancies_get_by_ids(
        self,
        ids: list[int],
        fields: list[VacanciesGetByIdsFields] | None = None,
        params: list[VacanciesGetByIdsParams] | None = None,
    ) -> Vacancies20:
        """Просмотр данных вакансий via ``POST /job/v2/vacancies/batch``.

        Args:
            fields: Поля для основного тела ответа
            ids: Идентификаторы вакансий на сайте
            params: Дополнительные поля, которые входят в params (можно указать несколько значений через запятую). Если значение не задано - возвращаются все поля. Устаревшие значения: * change (используйте shifts) * is_remote (используйте work_format) Удалённые значения (более недоступны): * manufacturing_type * industry_type * piecework_flag * programs * warehouse_functionality * where_to_work
        """
        return await self(VacanciesGetByIds(fields=fields, ids=ids, params=params))

    async def vacancy_get_statuses(self, ids: list[str] | None = None) -> VacancyStatusesResult:
        """Получение статуса публикации вакансий V2 via ``POST /job/v2/vacancies/statuses``."""
        return await self(VacancyGetStatuses(ids=ids))

    async def vacancy_update_v2(
        self,
        vacancy_uuid: str,
        billing_type: VacancyUpdateV2BillingType,
        administrator_organization_type: int | None = None,
        from_: int | None = None,
        to: int | None = None,
        age_preferences: list[VacancyUpdateV2AgePreferences] | None = None,
        additional_questions: list[ApplyProcessingAdditionalQuestions] | None = None,
        apply_type: ApplyProcessingApplyType | None = None,
        bonuses: list[BonusesValue] | None = None,
        business_area: int | None = None,
        citizenship: list[CitizenshipCriteriaValue] | None = None,
        construction_work_type: list[ConstructionWorkTypeValue] | None = None,
        allow_calls: bool | None = None,
        allow_messages: bool | None = None,
        email: str | None = None,
        name: str | None = None,
        phone: str | None = None,
        cuisine: list[CuisineValue] | None = None,
        delivery_method: list[VacancyUpdateV2DeliveryMethod] | None = None,
        description: VacancyUpdateV2Description | None = None,
        driving_experience: VacancyUpdateV2DrivingExperience | None = None,
        driving_license_category: list[DrivingLicenseCategoryValue] | None = None,
        eatery_type: list[EateryTypeValue] | None = None,
        education_level: VacancyEducationLevel | None = None,
        employment: str | None = None,
        experience: VacancyUpdateV2Experience | None = None,
        facility_type: list[FacilityTypeValue] | None = None,
        food_production_shop_type: list[FoodProductionShopTypeValue] | None = None,
        grade: Grade | None = None,
        employee_id: int | None = None,
        image_url: str | None = None,
        is_company_car: bool | None = None,
        is_side_job: bool | None = None,
        address: LocationAddress | None = None,
        coordinates: Coordinates | None = None,
        medical_book: MedicalBookVacancy | None = None,
        medical_specialization: list[str] | None = None,
        medical_specialization_ids: list[int] | None = None,
        payout_frequency: VacancyUpdateV2PayoutFrequency | None = None,
        profession: int | None = None,
        programs: list[VacancyUpdateV2Programs] | None = None,
        registration_method: list[RegistrationMethodValue] | None = None,
        retail_equipment_type: list[RetailEquipmentTypeValue] | None = None,
        retail_shop_type: list[RetailShopTypeValue] | None = None,
        salary_from_: int | None = None,
        salary_to: int | None = None,
        base: SalaryDetailBase | None = None,
        paid_period: PaidPeriod | None = None,
        taxes: Taxes | None = None,
        schedule: VacancyUpdateV2Schedule | None = None,
        shifts: list[int] | None = None,
        title: str | None = None,
        tools_availability: ToolsAvailability | None = None,
        vacancy_code: str | None = None,
        vehicle_type: int | None = None,
        work_days_per_week: list[int] | None = None,
        work_format: list[VacancyUpdateV2WorkFormat] | None = None,
        work_hours_per_day: list[int] | None = None,
        worker_class: list[WorkerClassValue] | None = None,
    ) -> None:
        """Редактирование вакансии v2 via ``POST /job/v2/vacancies/update/{vacancy_uuid}``.

        Args:
            vacancy_uuid: UUID Идентификатор вакансии для V2 ручек (возвращается ручкой [Публикация вакансии V2](https://developers.avito.ru/api-catalog/job/documentation#operation/vacancyCreateV2) )
            age_preferences: Блок \"в том числе для кандидатов\" (массив строк) Возможные значения элементов массива: - \"olderThan45\" - старше 45 лет; - \"olderThan14\" - от 14 лет; - \"olderThan16\" - от 16 лет; - \"withHealthProblems\" - с нарушениями здоровья; - \"students\" - для студентов; - \"pensioners\" - для пенсионеров.
            additional_questions: *DEPRECATED* Заполнение поля не влияет на вакансию. Массив со списком дополнительных вопросов, которые задаст ассистент Авито. - `experience` - вопрос про опыт работы. В качестве критерия будет использоваться значение поля `experience`. В результатах опроса ассистент отметит, достаточно у кандидата опыта или нет. - `citizenship` - вопрос про гражданство. В качестве критерия будет использоваться значение поля `citizenship`, если оно заполнено. - `age` - вопрос про возраст. В качестве критерия будет использоваться значение поля `age`, если оно заполнено.
            apply_type: Принимает два значения: - `with_assistant` - на вакансию смогут откликнуться кандидаты с резюме и без. - `only_with_resume` - на вакансию смогут откликаться только кандидаты с резюме. Если у кандидата нет резюме, Авито поможет создать его и откликнуться на вакансию
            billing_type: Вариант платного размещения Возможные значения: - \"package\" - размещение объявления осуществляется только при наличии подходящего пакета размещения - \"packageOrSingle\" - при наличии подходящего пакета оплата размещения объявления произойдет с него; если нет подходящего пакета, но достаточно денег на кошельке Авито, то произойдет разовое размещение
            business_area: Идентификатор сферы деятельности Получить актуальный список доступных значений можно из справочника `business_area` через метод [getDictByID](/api-catalog/job/documentation#operation/getDictByID).
            allow_messages: Возможность откликнуться на вакансию через сайт. Если передается apply_processing, то значение allow_messages будет игнорироваться и равно true
            email: Email контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использована почта из Профиля Сотрудника. При публикации от Компании или Пользователя будет использоваться почта из Профиля, переданное значение будет проигнорировано.
            name: Имя менеджера, контактного лица по данному объявлению. Учитывается только при публикации вакансии от имени Сотрудника. Если не заполнено то при публикации от Сотрудника будет использовано \"Имя сотрудника, которое видят пользователи при просмотре объявления\". При публикации от Компании или Пользователя не заполняется, переданное значение будет проигнорировано.
            phone: Контактный телефон, если не передать - подставляется номер из профиля который используется по умолчанию. Если передать номер телефона которого нет в профиле, то он будет добавлен в профиль, но по нему необходимо будет пройти верификацию. Если номер телефона принадлежит другому пользователю, то вакансия не будет опубликована. Если вакансия публикуется от имени сотрудника и номер телефона ему не принадлежит - объявление так же не будет опубликовано.
            delivery_method: Способ доставки
            description: Описание вакансии (строка длиной от 1 до 5000 символов) Можно использовать HTML-теги в тексте. Поддерживаемые тэги - `p`, `ul`, `ol`, `li`, `br`, `strong`, `em`
            driving_experience: Стаж вождения
            employment: Занятость Возможные значения: - temporary - Временная - full - Полная - partial - Частичная Если ничего не выбрать то будет автоматически проставляться в зависимости от графика работы: При flexible и partTime, тип занятости - partial. ßДля всех остальных full. deprecated значение internship будет заменено на temporary
            experience: Опыт работы
            employee_id: Идентификатор сотрудника на Авито
            image_url: URL-адрес логотипа вакансии. Ссылка на файл должна быть прямой | (при переходе не открываются элементы другого сайта (логотипы, кнопки или другие детали интерфейса) и не запрашивается логин и пароль) и доступной для IP 185.89.12.0/22, 146.158.48.0/21, 185.79.237.224/28 и 87.245.204.32/28;
            is_company_car: Предоставляет ли компания автомобиль
            is_side_job: Подработка
            payout_frequency: Частота выплат Возможные значения: - \"dailyPay\" - Каждый день; - \"biweeklyPay\" - Дважды в месяц; - \"weeklyPay\" - Раз в неделю; - \"thriceMonthlyPay\" - три раза в месяц; - \"monthlyPay\" - Раз в месяц. Для paid_period равным month и week недоступно для выбора dailyPay. deprecated значение hourlyPay будет заменено на dailyPay
            programs: Блок участие вакансии в программах (массив строк) Если у компании от лица которой создается вакансия нет всех необходимых разрешений на участие, программа у вакансии не будет включена. Возможные значения элементов массива: - \"chastyeVyplaty\" - Частые выплаты.
            salary_from_: Нижняя граница зарплаты, рублей в месяц
            salary_to: Верхняя граница зарплаты, рублей в месяц
            base: Оклад
            schedule: Режим работы Возможные значения: - flyInFlyOut - Вахта - fixed - Фиксированный - flexible - Гибкий - shift - Сменный flyInFlyOut - Вахта, при выборе данного режима работы, адрес вакансии может быть только \"Город\", если адрес передается полноценный, то улица будет отрезана и адрес будет до \"Города\". deprecated значения fiveDay, sixDay, partTime, fullDay и remote будут заменены на fixed
            title: Название вакансии (строка длиной от 1 до 50 символов)
            vacancy_code: Внутренний идентификатор вакансии или номер заявки на подбор, максимум 150 символов
            work_format: Блок \"Формат работы\" (массив строк) Возможные значения элементов массива: - \"office\" - В офисе или на объекте; - \"remote\" - Удалённо; - \"gibrid\" - Гибрид.
        """
        return await self(
            VacancyUpdateV2(
                vacancy_uuid=vacancy_uuid,
                administrator_organization_type=administrator_organization_type,
                age=AgeCriteria(from_=from_, to=to),
                age_preferences=age_preferences,
                apply_processing=ApplyProcessing(
                    additional_questions=additional_questions, apply_type=apply_type
                ),
                billing_type=billing_type,
                bonuses=bonuses,
                business_area=business_area,
                citizenship=citizenship,
                construction_work_type=construction_work_type,
                contacts=VacancyUpdateV2Contacts(
                    allow_calls=allow_calls,
                    allow_messages=allow_messages,
                    email=email,
                    name=name,
                    phone=phone,
                ),
                cuisine=cuisine,
                delivery_method=delivery_method,
                description=description,
                driving_experience=driving_experience,
                driving_license_category=driving_license_category,
                eatery_type=eatery_type,
                education_level=education_level,
                employment=employment,
                experience=experience,
                facility_type=facility_type,
                food_production_shop_type=food_production_shop_type,
                grade=grade,
                hierarchy=VacancyUpdateV2Hierarchy(employee_id=employee_id),
                image_url=image_url,
                is_company_car=is_company_car,
                is_side_job=is_side_job,
                location=VacancyUpdateV2Location(address=address, coordinates=coordinates),
                medical_book=medical_book,
                medical_specialization=medical_specialization,
                medical_specialization_ids=medical_specialization_ids,
                payout_frequency=payout_frequency,
                profession=profession,
                programs=programs,
                registration_method=registration_method,
                retail_equipment_type=retail_equipment_type,
                retail_shop_type=retail_shop_type,
                salary=VacancyUpdateV2Salary(from_=salary_from_, to=salary_to),
                salary_detail=SalaryDetail(base=base, paid_period=paid_period, taxes=taxes),
                schedule=schedule,
                shifts=shifts,
                title=title,
                tools_availability=tools_availability,
                vacancy_code=vacancy_code,
                vehicle_type=vehicle_type,
                work_days_per_week=work_days_per_week,
                work_format=work_format,
                work_hours_per_day=work_hours_per_day,
                worker_class=worker_class,
            )
        )

    async def vacancy_get_item(
        self,
        vacancy_id: int,
        fields: VacancyGetItemFields | None = None,
        params: VacancyGetItemParams | None = None,
    ) -> Vacancy20:
        """Просмотр данных вакансии via ``GET /job/v2/vacancies/{vacancy_id}``.

        Args:
            vacancy_id: Идентификатор вакансии
            fields: Поля основного тела ответа (можно указать несколько значений через запятую). По умолчанию отображаются все поля.
            params: Дополнительные поля, которые входят в params (можно указать несколько значений через запятую). Если значение не задано - возвращаются все поля. Устаревшие значения: * change (используйте shifts) * is_remote (используйте work_format) Удалённые значения (более недоступны): * manufacturing_type * industry_type * piecework_flag * programs * warehouse_functionality * where_to_work
        """
        return await self(VacancyGetItem(vacancy_id=vacancy_id, fields=fields, params=params))

    async def vacancy_auto_renewal2(
        self, vacancy_uuid: str, auto_renewal: bool | None = None
    ) -> None:
        """Автопродление вакансии v2 via ``PUT /job/v2/vacancies/{vacancy_uuid}/auto_renewal``.

        Args:
            vacancy_uuid: UUID Идентификатор вакансии для V2 ручек (возвращается ручкой [Публикация вакансии V2](https://developers.avito.ru/api-catalog/job/documentation#operation/vacancyCreateV2) )
        """
        return await self(VacancyAutoRenewal2(vacancy_uuid=vacancy_uuid, auto_renewal=auto_renewal))

    async def dicts(self) -> None:
        """Получение списка доступных словарей via ``GET /job/v2/vacancy/dict``."""
        return await self(GetDicts())

    async def dict_by_id(self, dictionary_id: str) -> None:
        """Получение доступных значений списка по ID словаря via ``GET /job/v2/vacancy/dict/{dictionary_id}``.

        Args:
            dictionary_id: Идентификатор словаря
        """
        return await self(GetDictById(dictionary_id=dictionary_id))
