# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Мессенджер — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..enums.messenger import GetChatsV2ChatTypes, PostSendMessageType
from ..methods.messenger import (
    ChatRead,
    DeleteMessage,
    GetChatByIdV2,
    GetChatsV2,
    GetMessagesV3,
    GetSubscriptions,
    GetVoiceFiles,
    PostBlacklistV2,
    PostSendImageMessage,
    PostSendMessage,
    PostWebhookUnsubscribe,
    PostWebhookV3,
    UploadImages,
)
from ..models._helpers import _resolve_user_id
from ..models.messenger import (
    Chat,
    ChatReadResponse,
    Chats,
    DeleteMessageResponse,
    GetSubscriptionsResponse,
    Messages,
    PostBlacklistV2Users,
    PostSendImageMessageResponse,
    PostSendMessageMessage,
    PostSendMessageResponse,
    PostWebhookUnsubscribeResponse,
    PostWebhookV3Response,
    UploadImagesResponse,
    VoiceFiles,
)
from ._base import FacadeBase


class MessengerFacade(FacadeBase):
    """``Client`` mixin — Мессенджер endpoints."""

    async def send_message(
        self,
        chat_id: str,
        user_id: int | None = None,
        text: str | None = None,
        type_: PostSendMessageType | None = None,
    ) -> PostSendMessageResponse:
        """Отправка сообщения via ``POST /messenger/v1/accounts/{user_id}/chats/{chat_id}/messages``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            chat_id: Идентификатор чата (клиента)
            text: Текст сообщения (максимум 1000 символов)
            type_: Тип сообщения
        """
        return await self.execute(
            PostSendMessage(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                chat_id=chat_id,
                message=PostSendMessageMessage(text=text),
                type_=type_,
            )
        )

    async def send_image_message(
        self, chat_id: str, image_id: str, user_id: int | None = None
    ) -> PostSendImageMessageResponse:
        """Отправка сообщения с изображением via ``POST /messenger/v1/accounts/{user_id}/chats/{chat_id}/messages/image``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            chat_id: Идентификатор чата (клиента)
            image_id: Идентификатор загруженного изображения
        """
        return await self.execute(
            PostSendImageMessage(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                chat_id=chat_id,
                image_id=image_id,
            )
        )

    async def delete_message(
        self, chat_id: str, message_id: str, user_id: int | None = None
    ) -> DeleteMessageResponse:
        """Удаление сообщения via ``POST /messenger/v1/accounts/{user_id}/chats/{chat_id}/messages/{message_id}``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            chat_id: Идентификатор чата (клиента)
            message_id: Идентификатор сообщения
        """
        return await self.execute(
            DeleteMessage(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                chat_id=chat_id,
                message_id=message_id,
            )
        )

    async def chat_read(self, chat_id: str, user_id: int | None = None) -> ChatReadResponse:
        """Прочитать чат via ``POST /messenger/v1/accounts/{user_id}/chats/{chat_id}/read``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            chat_id: Идентификатор чата (клиента)
        """
        return await self.execute(
            ChatRead(
                user_id=_resolve_user_id(self) if user_id is None else user_id, chat_id=chat_id
            )
        )

    async def voice_files(self, voice_ids: list[str], user_id: int | None = None) -> VoiceFiles:
        """Получение голосовых сообщений via ``GET /messenger/v1/accounts/{user_id}/getVoiceFiles``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            voice_ids: Получение файлов голосовых сообщений с указанными voice_id
        """
        return await self.execute(
            GetVoiceFiles(
                user_id=_resolve_user_id(self) if user_id is None else user_id, voice_ids=voice_ids
            )
        )

    async def upload_images(
        self, uploadfile: str, user_id: int | None = None
    ) -> UploadImagesResponse:
        """Загрузка изображений via ``POST /messenger/v1/accounts/{user_id}/uploadImages``.

        Args:
            user_id: Идентификатор пользователя (клиента)
        """
        return await self.execute(
            UploadImages(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                uploadfile=uploadfile,
            )
        )

    async def subscriptions(self) -> GetSubscriptionsResponse:
        """Получение подписок (webhooks) via ``POST /messenger/v1/subscriptions``."""
        return await self.execute(GetSubscriptions())

    async def webhook_unsubscribe(self, url: str) -> PostWebhookUnsubscribeResponse:
        """Отключение уведомлений (webhooks) via ``POST /messenger/v1/webhook/unsubscribe``.

        Args:
            url: Url на который будут отправляться нотификации
        """
        return await self.execute(PostWebhookUnsubscribe(url=url))

    async def blacklist_v2(
        self, user_id: int | None = None, users: list[PostBlacklistV2Users] | None = None
    ) -> None:
        """Добавление пользователя в blacklist via ``POST /messenger/v2/accounts/{user_id}/blacklist``.

        Args:
            user_id: Идентификатор пользователя (клиента)
        """
        return await self.execute(
            PostBlacklistV2(
                user_id=_resolve_user_id(self) if user_id is None else user_id, users=users
            )
        )

    async def chats_v2(
        self,
        user_id: int | None = None,
        item_ids: list[int] | None = None,
        unread_only: bool = False,
        chat_types: list[GetChatsV2ChatTypes] | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> Chats:
        """Получение информации по чатам via ``GET /messenger/v2/accounts/{user_id}/chats``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            item_ids: Получение чатов только по объявлениям с указанными item_id
            unread_only: При значении true метод возвращает только непрочитанные чаты
            chat_types: Фильтрация возвращаемых чатов. * u2i — чаты по объявлениям; * u2u — чаты между пользователями; * a2u — чаты между пользователями и Авито;
            limit: Количество сообщений / чатов для запроса
            offset: Сдвиг сообщений / чатов для запроса
        """
        return await self.execute(
            GetChatsV2(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                item_ids=item_ids,
                unread_only=unread_only,
                chat_types=chat_types,
                limit=limit,
                offset=offset,
            )
        )

    async def chat_by_id_v2(self, chat_id: str, user_id: int | None = None) -> Chat:
        """Получение информации по чату via ``GET /messenger/v2/accounts/{user_id}/chats/{chat_id}``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            chat_id: Идентификатор чата (клиента)
        """
        return await self.execute(
            GetChatByIdV2(
                user_id=_resolve_user_id(self) if user_id is None else user_id, chat_id=chat_id
            )
        )

    async def messages_v3(
        self, chat_id: str, user_id: int | None = None, limit: int = 100, offset: int = 0
    ) -> Messages:
        """Получение списка сообщений V3 via ``GET /messenger/v3/accounts/{user_id}/chats/{chat_id}/messages/``.

        Args:
            user_id: Идентификатор пользователя (клиента)
            chat_id: Идентификатор чата (клиента)
            limit: Количество сообщений / чатов для запроса
            offset: Сдвиг сообщений / чатов для запроса
        """
        return await self.execute(
            GetMessagesV3(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                chat_id=chat_id,
                limit=limit,
                offset=offset,
            )
        )

    async def webhook_v3(self, url: str) -> PostWebhookV3Response:
        """Включение уведомлений V3 (webhooks) via ``POST /messenger/v3/webhook``.

        Args:
            url: Url на который будут отправляться нотификации
        """
        return await self.execute(PostWebhookV3(url=url))
