# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Управление заказами — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..enums.order_management import (
    ApplyTransitionTransition,
    SetCourierDeliveryRangeIntervalType,
    Status,
)
from ..methods.order_management import (
    AcceptReturnOrder,
    ApplyTransition,
    CheckConfirmationCode,
    CncSetDetails,
    DownloadLabel,
    GenerateLabels,
    GenerateLabelsExtended,
    GetCourierDeliveryRange,
    GetOrders,
    Markings,
    SetCourierDeliveryRange,
    SetOrderTrackingNumber,
)
from ..models.common import TZDatetime
from ..models.order_management import (
    AcceptReturnOrderRecipient,
    ApplyTransitionParams,
    GetDeliveryCourierConfirmationResponse,
    Marking,
    OrderAcceptReturnOrderResponse,
    OrderApplyTransitionResponse,
    OrderCheckConfirmationCodeResponse,
    OrderCncSetDetailsResponse,
    OrderSetTrackingNumberResponse,
    OrdersInfo,
    OrdersLabelsResponse,
    SetCourierDeliveryRangeResponse,
    SetOrderMarkingResponse,
)
from ._base import FacadeBase


class OrderManagementFacade(FacadeBase):
    """``Client`` mixin — Управление заказами endpoints."""

    async def markings(self, markings: list[Marking] | None = None) -> SetOrderMarkingResponse:
        """Передача честного знака via ``POST /order-management/1/markings``.

        Args:
            markings: Массив маркировок, которые требуется передать
        """
        return await self(Markings(markings=markings))

    async def accept_return_order(
        self,
        order_id: str | None = None,
        recipient: AcceptReturnOrderRecipient | None = None,
        terminal_number: str | None = None,
    ) -> OrderAcceptReturnOrderResponse:
        """Выбор отделения отделения Почты России для получения возврата via ``POST /order-management/1/order/acceptReturnOrder``.

        Args:
            order_id: ID заказа в Авито
            recipient: Данные человека, который будет забирать возвратную посылку
            terminal_number: Номер отделения Почты России, куда придёт возвратная посылка.
        """
        return await self(
            AcceptReturnOrder(
                order_id=order_id, recipient=recipient, terminal_number=terminal_number
            )
        )

    async def apply_transition(
        self,
        order_id: str | None = None,
        params: ApplyTransitionParams | None = None,
        transition: ApplyTransitionTransition | None = None,
    ) -> OrderApplyTransitionResponse:
        """Изменение статуса заказа via ``POST /order-management/1/order/applyTransition``.

        Args:
            order_id: ID заказа в Авито
            params: Дополнительные параметры доставки
            transition: Название перехода. * `confirm` - подтверждение заказа; * `reject` - отмена заказа; * `perform` - подтверждение отправки заказа (RDBS); * `receive` - подтверждение доставки заказа (RDBS, CNC).
        """
        return await self(ApplyTransition(order_id=order_id, params=params, transition=transition))

    async def check_confirmation_code_order_management(
        self, confirm_code: str | None = None, parcel_id: str | None = None
    ) -> OrderCheckConfirmationCodeResponse:
        """Метод для проверки кода подтверждения заказа. via ``POST /order-management/1/order/checkConfirmationCode``.

        Args:
            confirm_code: Код, который показал пользователь
            parcel_id: ID посылки в Авито
        """
        return await self(CheckConfirmationCode(confirm_code=confirm_code, parcel_id=parcel_id))

    async def cnc_set_details(
        self,
        booking_period: int,
        id: str,
        marketplace_id: str,
        address: str | None = None,
        details: str | None = None,
    ) -> OrderCncSetDetailsResponse:
        """Метод для подготовки заказа с самовывозом via ``POST /order-management/1/order/cncSetDetails``.

        Args:
            address: Адрес получения товара
            booking_period: Сроки бронирования товара
            details: Комментарий, который получит покупатель
            id: ID заказа в Авито
            marketplace_id: Номер заказа в Авито в новой системе
        """
        return await self(
            CncSetDetails(
                address=address,
                booking_period=booking_period,
                details=details,
                id=id,
                marketplace_id=marketplace_id,
            )
        )

    async def get_courier_delivery_range(
        self, order_id: str, address: str | None = None
    ) -> GetDeliveryCourierConfirmationResponse:
        """Метод получения доступных временных промежутков приезда курьера via ``GET /order-management/1/order/getCourierDeliveryRange``.

        Args:
            order_id: ID заказа
            address: Адрес продавца
        """
        return await self(GetCourierDeliveryRange(order_id=order_id, address=address))

    async def set_courier_delivery_range(
        self,
        address: str,
        end_date: TZDatetime,
        interval_type: SetCourierDeliveryRangeIntervalType,
        name: str,
        order_id: str,
        phone: str,
        start_date: TZDatetime,
        address_details: str | None = None,
    ) -> SetCourierDeliveryRangeResponse:
        """Метод выбора определённого доступного временного промежутка для приезда курьера via ``POST /order-management/1/order/setCourierDeliveryRange``.

        Args:
            address: Адрес продавца
            address_details: Детали адреса продавца
            end_date: Конечная дата приезда курьера
            interval_type: Тип интервала
            name: ФИО
            order_id: ID заказа
            phone: Телефон
            start_date: Начальная дата приезда курьера
        """
        return await self(
            SetCourierDeliveryRange(
                address=address,
                address_details=address_details,
                end_date=end_date,
                interval_type=interval_type,
                name=name,
                order_id=order_id,
                phone=phone,
                start_date=start_date,
            )
        )

    async def set_order_tracking_number(
        self, order_id: str | None = None, tracking_number: str | None = None
    ) -> OrderSetTrackingNumberResponse:
        """Передача трек-номера via ``POST /order-management/1/order/setTrackingNumber``.

        Args:
            order_id: ID заказа в Авито
            tracking_number: Трек-номер посылки
        """
        return await self(
            SetOrderTrackingNumber(order_id=order_id, tracking_number=tracking_number)
        )

    async def get_orders(
        self,
        ids: list[str] | None = None,
        statuses: list[Status] | None = None,
        date_from: int | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> OrdersInfo:
        """Получение информации о заказах via ``GET /order-management/1/orders``.

        Args:
            ids: Идентификаторы заказов
            statuses: Статус, по которому нужно получить заказы. - on_confirmation - ожидает подтверждения - ready_to_ship - ждет отправки - in_transit - в пути - canceled - отменный заказ - delivered - доставлен покупателю - on_return - на возврате - in_dispute - по заказу открыт спор - closed - заказ закрыт
            date_from: Метка времени, с момента которого созданы покупки
            page: Номер страницы для пагинации
            limit: Максимальное количество заказов на странице
        """
        return await self(
            GetOrders(ids=ids, statuses=statuses, date_from=date_from, page=page, limit=limit)
        )

    async def generate_labels(self, order_ids: list[str]) -> OrdersLabelsResponse:
        """Создать задачу на генерацию этикеток (до 100). via ``POST /order-management/1/orders/labels``.

        Args:
            order_ids: ID заказов в сервисе сделок (marketplace)
        """
        return await self(GenerateLabels(order_ids=order_ids))

    async def generate_labels_extended(self, order_ids: list[str]) -> OrdersLabelsResponse:
        """Создать задачу на генерацию этикеток (до 1000). via ``POST /order-management/1/orders/labels/extended``.

        Args:
            order_ids: ID заказов в сервисе сделок (marketplace)
        """
        return await self(GenerateLabelsExtended(order_ids=order_ids))

    async def download_label(self, task_id: str) -> bytes:
        """Скачать сгенерированный PDF-файл (этикетку). via ``GET /order-management/1/orders/labels/{task_id}/download``.

        Args:
            task_id: ID задачи на генерацию
        """
        return await self(DownloadLabel(task_id=task_id))
