# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Продвижение — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..methods.promotion import (
    CreateBbipOrderForItemsV1,
    GetBbipForecastsByItemsV1,
    GetBbipSuggestsByItemsV1,
    GetDictOfServicesV1,
    GetOrderStatusV1,
    GetServicesByItemsV1,
    ListOrdersByUserV1,
)
from ..models.promotion import (
    BbipForecastRequestByItemV1,
    BbipOrderByItemV1,
    GetBbipForecastByItemsV1Resp,
    GetBbipSuggestsV1Resp,
    GetDictOfServicesV1Resp,
    GetOrderStatusV1Resp,
    GetServicesByItemsV1Resp,
    ListOrdersByUserV1Pagination,
    ListOrdersByUserV1Resp,
    OrderBbipForItemsV1Resp,
)
from ._base import FacadeBase


class PromotionFacade(FacadeBase):
    """``Client`` mixin — Продвижение endpoints."""

    async def get_bbip_forecasts_by_items_v1(
        self, items: list[BbipForecastRequestByItemV1]
    ) -> GetBbipForecastByItemsV1Resp:
        """BBIP. Прогноз продвижения via ``POST /promotion/v1/items/services/bbip/forecasts/get``.

        Args:
            items: Данные по объявлениям для запроса прогноза
        """
        return await self.execute(GetBbipForecastsByItemsV1(items=items))

    async def create_bbip_order_for_items_v1(
        self, items: list[BbipOrderByItemV1]
    ) -> OrderBbipForItemsV1Resp:
        """BBIP. Подключение услуги продвижения via ``PUT /promotion/v1/items/services/bbip/orders/create``.

        Args:
            items: Заявки на подключение BBIP по отдельным объявлениям
        """
        return await self.execute(CreateBbipOrderForItemsV1(items=items))

    async def get_bbip_suggests_by_items_v1(
        self, item_ids: list[int] | None = None
    ) -> GetBbipSuggestsV1Resp:
        """BBIP. Варианты бюджета продвижения via ``POST /promotion/v1/items/services/bbip/suggests/get``.

        Args:
            item_ids: Идентификаторы объявлений
        """
        return await self.execute(GetBbipSuggestsByItemsV1(item_ids=item_ids))

    async def get_dict_of_services_v1(self) -> GetDictOfServicesV1Resp:
        """Словарь типов услуг продвижения via ``POST /promotion/v1/items/services/dict``."""
        return await self.execute(GetDictOfServicesV1())

    async def get_services_by_items_v1(
        self, item_ids: list[int] | None = None
    ) -> GetServicesByItemsV1Resp:
        """Список услуг продвижения via ``POST /promotion/v1/items/services/get``.

        Args:
            item_ids: Идентификаторы объявлений
        """
        return await self.execute(GetServicesByItemsV1(item_ids=item_ids))

    async def list_orders_by_user_v1(
        self, page: int = 1, per_page: int = 20
    ) -> ListOrdersByUserV1Resp:
        """Список заявок via ``POST /promotion/v1/items/services/orders/get``.

        Args:
            page: Номер страницы
            per_page: Количество записей на странице
        """
        return await self.execute(
            ListOrdersByUserV1(
                pagination=ListOrdersByUserV1Pagination(page=page, per_page=per_page)
            )
        )

    async def get_order_status_v1(self, order_id: str | None = None) -> GetOrderStatusV1Resp:
        """Статус заявки via ``POST /promotion/v1/items/services/orders/status``.

        Args:
            order_id: Идентификатор заявки на подключение услуг продвижения
        """
        return await self.execute(GetOrderStatusV1(order_id=order_id))
