# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Рейтинги и отзывы — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..methods.reviews import (
    CreateReviewAnswerV1,
    GetRatingsInfoV1,
    GetReviewsV1,
    RemoveReviewAnswerV1,
)
from ..models.reviews import (
    CreateAnswerResponse,
    GetRatingInfoResponse,
    GetReviewsResponse,
    RemoveAnswerResponse,
)
from ._base import FacadeBase


class ReviewsFacade(FacadeBase):
    """``Client`` mixin — Рейтинги и отзывы endpoints."""

    async def create_review_answer_v1(self, message: str, review_id: int) -> CreateAnswerResponse:
        """Отправка ответа на отзыв via ``POST /ratings/v1/answers``.

        Args:
            message: Текст ответа на отзыв
            review_id: ID отзыва
        """
        return await self.execute(CreateReviewAnswerV1(message=message, review_id=review_id))

    async def remove_review_answer_v1(self, answer_id: int) -> RemoveAnswerResponse:
        """Запрос на удаление ответа на отзыв via ``DELETE /ratings/v1/answers/{answer_id}``.

        Args:
            answer_id: Идентификатор ответа на отзыв
        """
        return await self.execute(RemoveReviewAnswerV1(answer_id=answer_id))

    async def get_ratings_info_v1(self) -> GetRatingInfoResponse:
        """Получение информации о рейтинге пользователя via ``GET /ratings/v1/info``."""
        return await self.execute(GetRatingsInfoV1())

    async def get_reviews_v1(self, offset: int, limit: int) -> GetReviewsResponse:
        """Получение списка активных отзывов на пользователя с пагинацией via ``GET /ratings/v1/reviews``.

        Args:
            offset: Смещение
            limit: Лимит количества отзывов
        """
        return await self.execute(GetReviewsV1(offset=offset, limit=limit))
