# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Краткосрочная аренда — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from datetime import date

from ..methods.short_term_rental import (
    GetRealtyBookings,
    PostBaseParams,
    PostRealtyPrices,
    PutBookingsInfo,
    PutIntervals,
)
from ..models._helpers import _resolve_user_id
from ..models.short_term_rental import (
    GetRealtyBookingsResponse,
    ParamPriceItemRealty,
    PostBaseParamsDiscount,
    PostBaseParamsFees,
    PostBaseParamsInstant,
    PostBaseParamsRefund,
    PostRealtyPricesResponse,
    PutBookingsInfoBookings,
    PutBookingsInfoResponse,
    PutIntervalsIntervals,
    PutIntervalsResponse,
)
from ._base import FacadeBase


class ShortTermRentalFacade(FacadeBase):
    """``Client`` mixin — Краткосрочная аренда endpoints."""

    async def put_bookings_info(
        self,
        item_id: int,
        user_id: int | None = None,
        bookings: list[PutBookingsInfoBookings] | None = None,
        source: str | None = None,
    ) -> PutBookingsInfoResponse:
        """Заполнение календаря занятости объекта недвижимости via ``POST /core/v1/accounts/{user_id}/items/{item_id}/bookings``.

        See: https://developers.avito.ru/api-catalog/str/documentation

        Args:
            user_id: Номер пользователя в Личном кабинете Авито
            item_id: Идентификатор объявления на сайте
            bookings: Список броней для выбранного объекта недвижимости (объявления)
            source: Название PMS системы
        """
        return await self(
            PutBookingsInfo(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                item_id=item_id,
                bookings=bookings,
                source=source,
            )
        )

    async def get_realty_bookings(
        self,
        item_id: int,
        date_start: date,
        date_end: date,
        user_id: int | None = None,
        skip_error: bool | None = None,
        with_unpaid: bool | None = None,
    ) -> GetRealtyBookingsResponse:
        """Получение списка броней по объявлению via ``GET /realty/v1/accounts/{user_id}/items/{item_id}/bookings``.

        See: https://developers.avito.ru/api-catalog/str/documentation

        Args:
            user_id: Номер пользователя в Личном кабинете Авито
            item_id: Идентификатор объявления на сайте
            skip_error: Флаг, с которым вместо ошибок(если ошибка произошла с айтемом) возвращается 200 статус, без ошибки
            date_start: Фильтр, ограничивающий выборку по нижней границе дат, не в прошлом
            date_end: Фильтр, ограничивающий выборку по верхней границе дат, не в прошлом
            with_unpaid: Флаг, позволяющий получить неоплаченные брони (возвращаются в статусе pending)
        """
        return await self(
            GetRealtyBookings(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                item_id=item_id,
                skip_error=skip_error,
                date_start=date_start,
                date_end=date_end,
                with_unpaid=with_unpaid,
            )
        )

    async def post_realty_prices(
        self,
        item_id: int,
        user_id: int | None = None,
        skip_error: bool | None = None,
        prices: list[ParamPriceItemRealty] | None = None,
    ) -> PostRealtyPricesResponse:
        """Актуализация параметров для выбранных периодов via ``POST /realty/v1/accounts/{user_id}/items/{item_id}/prices``.

        See: https://developers.avito.ru/api-catalog/str/documentation

        Args:
            user_id: Номер пользователя в Личном кабинете Авито
            item_id: Идентификатор объявления на сайте
            skip_error: Флаг, с которым вместо ошибок(если ошибка произошла с айтемом) возвращается 200 статус, без ошибки
        """
        return await self(
            PostRealtyPrices(
                user_id=_resolve_user_id(self) if user_id is None else user_id,
                item_id=item_id,
                skip_error=skip_error,
                prices=prices,
            )
        )

    async def put_intervals(
        self,
        skip_error: bool | None = None,
        intervals: list[PutIntervalsIntervals] | None = None,
        item_id: int | None = None,
        source: str | None = None,
    ) -> PutIntervalsResponse:
        """Заполнение доступности объекта недвижимости с квотами и без via ``POST /realty/v1/items/intervals``.

        See: https://developers.avito.ru/api-catalog/str/documentation

        Args:
            skip_error: Флаг, с которым вместо ошибок(если ошибка произошла с айтемом) возвращается 200 статус, без ошибки
            intervals: Список интервалов для выбранного объявления
            item_id: ID объявления
            source: Название PMS системы
        """
        return await self(
            PutIntervals(skip_error=skip_error, intervals=intervals, item_id=item_id, source=source)
        )

    async def post_base_params(
        self,
        item_id: int,
        discount: list[PostBaseParamsDiscount] | None = None,
        extra_guest_fee: int | None = None,
        extra_guest_threshold: int | None = None,
        fees: PostBaseParamsFees | None = None,
        instant: PostBaseParamsInstant | None = None,
        minimal_duration: int | None = None,
        night_price: int | None = None,
        refund: PostBaseParamsRefund | None = None,
    ) -> None:
        """Установка базовых параметров via ``POST /realty/v1/items/{item_id}/base``.

        See: https://developers.avito.ru/api-catalog/str/documentation

        Args:
            item_id: Идентификатор объявления на сайте
            discount: Скидки при бронировании от threshold ночей
            extra_guest_fee: Доплата за гостя (рубли)
            extra_guest_threshold: Порог гостей, при котором цена - night_price
            fees: Настройки доплат
            instant: Параметры мгновенного бронирования
            minimal_duration: Минимальная продолжительность (ночи)
            night_price: Цена проживания за ночь (рубли)
            refund: Параметры возврата
        """
        return await self(
            PostBaseParams(
                item_id=item_id,
                discount=discount,
                extra_guest_fee=extra_guest_fee,
                extra_guest_threshold=extra_guest_threshold,
                fees=fees,
                instant=instant,
                minimal_duration=minimal_duration,
                night_price=night_price,
                refund=refund,
            )
        )
