# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""TrxPromo — client facade mixin (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ..methods.trxpromo import (
    ApiTrxPromoOpenApiApply,
    ApiTrxPromoOpenApiCancel,
    ApiTrxPromoOpenApiCommissions,
)
from ..models.trxpromo import (
    ApiTrxPromoOpenApiApplyItems,
    ApplyResponse,
    CancelResponse,
    CommissionResponse,
)
from ._base import FacadeBase


class TrxpromoFacade(FacadeBase):
    """``Client`` mixin — TrxPromo endpoints."""

    async def api_trx_promo_open_api_apply(
        self, items: list[ApiTrxPromoOpenApiApplyItems]
    ) -> ApplyResponse:
        """Запуск продвижения via ``POST /trx-promo/1/apply``."""
        return await self.execute(ApiTrxPromoOpenApiApply(items=items))

    async def api_trx_promo_open_api_cancel(self, item_ids: list[int]) -> CancelResponse:
        """Остановка продвижения via ``POST /trx-promo/1/cancel``."""
        return await self.execute(ApiTrxPromoOpenApiCancel(item_ids=item_ids))

    async def api_trx_promo_open_api_commissions(self, item_ids: list[int]) -> CommissionResponse:
        """Проверка доступности продвижения и размера комиссий via ``GET /trx-promo/1/commissions``."""
        return await self.execute(ApiTrxPromoOpenApiCommissions(item_ids=item_ids))
