# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Автостратегия — domain enums (auto-generated from the Avito OpenAPI spec)."""

from enum import StrEnum


class CampaignCampaignType(StrEnum):
    """CampaignCampaignType values."""

    AS = "AS"
    AP = "AP"


class CreateCampaignRequestBodyCampaignType(StrEnum):
    """CreateCampaignRequestBodyCampaignType values."""

    AS = "AS"
    AP = "AP"


class GetBudgetRequestBodyCampaignType(StrEnum):
    """GetBudgetRequestBodyCampaignType values."""

    AS = "AS"
    AP = "AP"


class GetCampaignInfoForecastResultCallsLackReason(StrEnum):
    """GetCampaignInfoForecastResultCallsLackReason values."""

    NOT_ENOUGH_DATA = "not_enough_data"
    NO_CALLTRACKING = "no_calltracking"


class GetCampaignInfoForecastResultViewsLackReason(StrEnum):
    """GetCampaignInfoForecastResultViewsLackReason values."""

    NOT_ENOUGH_DATA = "not_enough_data"


class GetCampaignsRequestBodyOrderByColumn(StrEnum):
    """GetCampaignsRequestBodyOrderByColumn values."""

    CAMPAIGNID = "campaignId"
    USERID = "userId"
    BUDGET = "budget"
    BALANCE = "balance"
    TITLE = "title"
    STATUSID = "statusId"
    STARTTIME = "startTime"
    FINISHTIME = "finishTime"
    CREATETIME = "createTime"
    UPDATETIME = "updateTime"
    ITEMSCOUNT = "itemsCount"
    ISPAID = "isPaid"


class GetCampaignsRequestBodyOrderByDirection(StrEnum):
    """GetCampaignsRequestBodyOrderByDirection values."""

    ASC = "asc"
    DESC = "desc"


class GetAutostrategyBudgetCampaignType(StrEnum):
    """GetAutostrategyBudgetCampaignType values."""

    AS = "AS"
    AP = "AP"


class CreateAutostrategyCampaignCampaignType(StrEnum):
    """CreateAutostrategyCampaignCampaignType values."""

    AS = "AS"
    AP = "AP"


class GetAutostrategyCampaignsOrderByColumn(StrEnum):
    """GetAutostrategyCampaignsOrderByColumn values."""

    CAMPAIGNID = "campaignId"
    USERID = "userId"
    BUDGET = "budget"
    BALANCE = "balance"
    TITLE = "title"
    STATUSID = "statusId"
    STARTTIME = "startTime"
    FINISHTIME = "finishTime"
    CREATETIME = "createTime"
    UPDATETIME = "updateTime"
    ITEMSCOUNT = "itemsCount"
    ISPAID = "isPaid"


class GetAutostrategyCampaignsOrderByDirection(StrEnum):
    """GetAutostrategyCampaignsOrderByDirection values."""

    ASC = "asc"
    DESC = "desc"
