# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Рейтинги и отзывы — domain enums (auto-generated from the Avito OpenAPI spec)."""

from enum import StrEnum


class ReviewStage(StrEnum):
    """ReviewStage values."""

    DONE = "done"
    FELL_THROUGH = "fell_through"
    NOT_AGREE = "not_agree"
    NOT_COMMUNICATE = "not_communicate"


class ReviewAnswerStatus(StrEnum):
    """ReviewAnswerStatus values."""

    MODERATION = "moderation"
    PUBLISHED = "published"
    REJECTED = "rejected"
