# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Краткосрочная аренда — domain enums (auto-generated from the Avito OpenAPI spec)."""

from enum import StrEnum


class BaseParamsFeesPetsApplication(StrEnum):
    """BaseParamsFeesPetsApplication values."""

    BY_BOOKING = "by_booking"
    BY_NIGHT = "by_night"


class PostCalendarDataBookingsType(StrEnum):
    """PostCalendarDataBookingsType values."""

    MANUAL = "manual"
    BOOKING = "booking"


class RealtyBookingStatus(StrEnum):
    """RealtyBookingStatus values."""

    ACTIVE = "active"
    CANCELED = "canceled"
    PENDING = "pending"


class PutBookingsInfoResponseResult(StrEnum):
    """PutBookingsInfoResponseResult values."""

    SUCCESS = "success"


class PutBookingsInfoBookingsType(StrEnum):
    """PutBookingsInfoBookingsType values."""

    MANUAL = "manual"
    BOOKING = "booking"


class PostRealtyPricesResponseResult(StrEnum):
    """PostRealtyPricesResponseResult values."""

    SUCCESS = "success"


class PutIntervalsResponseResult(StrEnum):
    """PutIntervalsResponseResult values."""

    SUCCESS = "success"


class PostBaseParamsFeesPetsApplication(StrEnum):
    """PostBaseParamsFeesPetsApplication values."""

    BY_BOOKING = "by_booking"
    BY_NIGHT = "by_night"
