# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Информация о пользователе — domain enums (auto-generated from the Avito OpenAPI spec)."""

from enum import StrEnum


class ResponseOperationsHistoryItemOperationType(StrEnum):
    """ResponseOperationsHistoryItemOperationType values."""

    SPISANIE_V_SCHET_KREDITA = "списание в счёт кредита"
    POSTOPLATA = "постоплата"
    VNESENIE_CPA_AVANSA = "внесение CPA аванса"
    VOZVRAT_CPA_AVANSA = "возврат CPA аванса"
    AVANS = "аванс"
    VOZVRAT_AVANSA = "возврат аванса"
    SPISANIE_SREDSTV_S_KOSHELKA_V_DOHOD_NE_ZA_OKAZANNYE_USLUGI = (
        "списание средств с кошелька в доход (не за оказанные услуги)"
    )
    SZHIGANIE_BONUSOV = "сжигание бонусов"
    REZERVIROVANIE_POD_AVTOSTRATEGIYU = "резервирование под автостратегию"
    VOZVRAT_ZAREZERVIROVANNYH_SREDSTV_POD_AVTOSTATEGIYU_NA_KOSHELEK = (
        "возврат зарезервированных средств под автостатегию на кошелек"
    )
    REZERVIROVANIE_SREDSTV_POD_USLUGU = "резервирование средств под услугу"
    VOZVRAT_ZARZERVIROVANNYH_SREDSTV_NA_BALANS_KOSHELKA = (
        "возврат зарзервированных средств на баланс кошелька"
    )
    PRIZNANIE_VYRUCHKI = "признание выручки"
    SPISANIE_OSTATKA = "списание остатка"
    STORNO = "сторно"
    OPROTESTOVANO = "опротестовано"
    CHARDZHBEK = "чарджбэк"


class ResponseOperationsHistoryItemServiceType(StrEnum):
    """ResponseOperationsHistoryItemServiceType values."""

    VAS = "vas"
    PERF_VAS = "perf_vas"
    LF = "lf"
    CV = "cv"
    TARIFF = "tariff"
    SUBSCRIPTION = "subscription"
    CPA = "cpa"
    BUNDLE = "bundle"
