# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Shared models — cross-domain DTOs collapsed by codegen dedup (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from ._base import AvitoObject


class ErrorMessage(AvitoObject):
    """ErrorMessage — shared across domains."""

    message: str


class GetTokenRequest(AvitoObject):
    """GetTokenRequest — shared across domains."""

    client_id: str
    client_secret: str
    grant_type: str


class TooManyRequestsErrorError(AvitoObject):
    """TooManyRequestsErrorError — shared across domains.

    Attributes:
        code: Код ошибки
    """

    code: int
