# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Авито Реклама — domain models (auto-generated from the Avito OpenAPI spec).

See: https://developers.avito.ru/api-catalog/ads/documentation"""

from __future__ import annotations

from datetime import date

from pydantic import Field, RootModel

from ..enums.ads import (
    AudienceType,
    BannerFormat,
    BudgetFrequency,
    CampaignFieldName,
    CampaignGoalType,
    CampaignLandingType,
    CampaignPaymentModel,
    CampaignStatus,
    CampaignStrategy,
    CampaignType,
    ContractAction,
    ContractCounterpartyType,
    ContractSubject,
    ContractType,
    CreateCampaignPaymentModel,
    CreateCampaignType,
    CreativesStatus,
    FrequencyPeriod,
    GroupFormat,
    GroupPriceControl,
    GroupsStatus,
    LegalRole,
    LegalType,
    Paces,
    PeriodTimezone,
    ScheduleType,
    UserRole,
    V1GetHtmlOutStatus,
)
from ._base import AvitoObject
from .common import TZDatetime


class Account(AvitoObject):
    """Account response model.

    Attributes:
        contact: Контактное лицо
        manager: MSD Менеджер
    """

    actual_address: str = Field(..., alias="actualAddress")
    contact: AccountContact
    inn: str
    kpp: str
    legal_address: str = Field(..., alias="legalAddress")
    long_name: str = Field(..., alias="longName")
    manager: AccountManager | None = None
    ogrn: str
    short_name: str = Field(..., alias="shortName")


class AccountContact(AvitoObject):
    """Контактное лицо"""

    name: str
    phone: str


class AccountManager(AvitoObject):
    """MSD Менеджер"""

    email: str
    name: str


class Advertiser(AvitoObject):
    """Advertiser response model."""

    account_id: int = Field(..., alias="accountId")
    actual_address: str = Field(..., alias="actualAddress")
    id: int
    inn: str
    kpp: str | None = None
    legal_address: str = Field(..., alias="legalAddress")
    legal_role: LegalRole = Field(..., alias="legalRole")
    legal_type: LegalType = Field(..., alias="legalType")
    long_name: str = Field(..., alias="longName")
    ogrn: str
    short_name: str = Field(..., alias="shortName")


class AdvertiserFilter(AvitoObject):
    """AdvertiserFilter response model.

    Attributes:
        ids: Список ID рекламодателей
        inns: Список ИНН рекламодателей
        roles: Список ролей рекламодателей
    """

    ids: list[int] | None = None
    inns: list[str] | None = None
    roles: list[LegalRole] | None = None


class Campaign(AvitoObject):
    """Campaign response model.

    Attributes:
        account_id: ID аккаунта
        additional_agreement_id: ID дополнительного соглашения к изначальному договору
        advertiser_id: ID рекламодателя
        budget: Бюджет кампании в рублях с НДС
        budget_kopeks: Бюджет кампании в копейках с НДС
        contract_id: ID контракта
        created_at: Дата создания кампании
        end_date: Дата окончания кампании
        id: ID кампании
        manager_id: ID менеджера, ответственного за кампанию (userID)
        name: Название кампании
        performance_additional_agreement_id: ID доп соглашения к исполнительскому договору
        start_date: Дата начала кампании
        updated_at: Дата обновления кампании
        user_id: ID пользователя создавшего кампанию
    """

    account_id: int | None = Field(None, alias="accountId")
    additional_agreement_id: int | None = Field(None, alias="additionalAgreementID")
    advertiser_id: int | None = Field(None, alias="advertiserId")
    budget: int | None = None
    budget_kopeks: int | None = Field(None, alias="budgetKopeks")
    campaign_type: CampaignType | None = Field(None, alias="campaignType")
    contract_id: int | None = Field(None, alias="contractId")
    created_at: str | None = Field(None, alias="createdAt")
    end_date: str | None = Field(None, alias="endDate")
    id: int | None = None
    manager_id: int | None = Field(None, alias="managerID")
    name: str | None = None
    payment_model: CampaignPaymentModel | None = Field(None, alias="paymentModel")
    performance_additional_agreement_id: int | None = Field(
        None, alias="performanceAdditionalAgreementID"
    )
    start_date: str | None = Field(None, alias="startDate")
    status: CampaignStatus | None = None
    updated_at: str | None = Field(None, alias="updatedAt")
    user_id: int | None = Field(None, alias="userId")


class CampaignStatistic(AvitoObject):
    """Статистика кампании

    Attributes:
        data: Статистика в разбивке по дням
        id: ID кампании
        name: Название кампании
    """

    campaign_type: CampaignType = Field(..., alias="campaignType")
    data: list[StatsData]
    id: int
    name: str
    payment_model: CampaignPaymentModel = Field(..., alias="paymentModel")
    total_data: StatsData = Field(..., alias="totalData")


class CampaignsFilter(AvitoObject):
    """CampaignsFilter response model.

    Attributes:
        additional_agreement_ids: Список ID дополнительных соглашений
        advertisers: Список ID рекламодателей
        campaign_types: Список типов кампаний
        contract_ids: Список ID договоров
        ids: Список ID кампаний
        managers: Список ID менеджеров
        payment_models: Список моделей оплаты
        statuses: Список статусов кампаний
    """

    additional_agreement_ids: list[int] | None = Field(None, alias="additionalAgreementIDs")
    advertisers: list[int] | None = None
    campaign_types: list[CampaignType] | None = Field(None, alias="campaignTypes")
    contract_ids: list[int] | None = Field(None, alias="contractIDs")
    created_at: DateRange | None = Field(None, alias="createdAt")
    ids: list[int] | None = None
    managers: list[int] | None = None
    payment_models: list[CampaignPaymentModel] | None = Field(None, alias="paymentModels")
    statuses: list[CampaignStatus] | None = None
    time_frame: DateRange | None = Field(None, alias="timeFrame")


class Contract(AvitoObject):
    """Contract response model."""

    account_id: int = Field(..., alias="accountID")
    cid: str | None = None
    client: Advertiser
    contractor: Advertiser
    date_: str | None = Field(None, alias="date")
    description: str | None = None
    id: int
    is_agent_acting_for_publisher: bool | None = Field(None, alias="isAgentActingForPublisher")
    is_creative_reporter: bool | None = Field(None, alias="isCreativeReporter")
    number: str | None = None
    object: str | None = None
    parent_id: int | None = Field(None, alias="parentId")
    subject: str | None = None
    type_: ContractType = Field(..., alias="type")


class ContractForChildAccount(AvitoObject):
    """ContractForChildAccount response model."""

    account_id: int | None = Field(None, alias="accountID")
    cid: str | None = None
    client: Advertiser | None = None
    contractor: Advertiser | None = None
    date_: str | None = Field(None, alias="date")
    description: str | None = None
    id: int | None = None
    is_agent_acting_for_publisher: bool | None = Field(None, alias="isAgentActingForPublisher")
    is_creative_reporter: bool | None = Field(None, alias="isCreativeReporter")
    number: str | None = None
    object: str | None = None
    parent_id: int | None = Field(None, alias="parentId")
    subject: str | None = None
    type_: ContractType | None = Field(None, alias="type")


class ContractsFilter(AvitoObject):
    """ContractsFilter response model.

    Attributes:
        ids: Список ID договоров
        numbers: Список номеров договоров
    """

    clients: AdvertiserFilter | None = None
    contractors: AdvertiserFilter | None = None
    ids: list[int] | None = None
    numbers: list[str] | None = None


class CreateGroupActivitySchedule(AvitoObject):
    """Кастомное расписание активности"""

    friday: list[int] | None = None
    monday: list[int] | None = None
    saturday: list[int] | None = None
    sunday: list[int] | None = None
    thursday: list[int] | None = None
    tuesday: list[int] | None = None
    wednesday: list[int] | None = None


class Creative(AvitoObject):
    """Creative response model.

    Attributes:
        account_id: ID аккаунта
        advertiser_id: ID рекламодателя
        button_text: Текст на кнопке
        campaign_id: ID кампании
        description: Описание объявления
        group_id: ID группы
        id: ID креатива
        landing_id: ID посадочной страницы
        link: Целевая ссылка
        manager_id: ID менеджера, ответственного за кампанию (userID)
        name: Название креатива
        origin_url: Оригинальная ссылка для аналитики
        preview_url: Ссылка на предпросмотр креатива
        title: Заголовок объявления
        user_id: ID пользователя, создавшего креатив
    """

    account_id: int | None = Field(None, alias="accountID")
    advertiser_id: int | None = Field(None, alias="advertiserID")
    button_text: str | None = Field(None, alias="buttonText")
    campaign_id: int | None = Field(None, alias="campaignID")
    campaign_type: CampaignType | None = Field(None, alias="campaignType")
    description: str | None = None
    group_id: int | None = Field(None, alias="groupID")
    id: int | None = None
    landing_id: int | None = Field(None, alias="landingID")
    legal_info: LegalInfo | None = Field(None, alias="legalInfo")
    link: str | None = None
    manager_id: int | None = Field(None, alias="managerID")
    name: str | None = None
    origin_url: str | None = Field(None, alias="originUrl")
    payment_model: CampaignPaymentModel | None = Field(None, alias="paymentModel")
    preview_url: str | None = Field(None, alias="previewUrl")
    status: CreativesStatus | None = None
    title: str | None = None
    user_id: int | None = Field(None, alias="userID")


class CreativeStatistic(AvitoObject):
    """Статистика креатива

    Attributes:
        data: Статистика в разбивке по дням
        group_id: ID группы, к которой относится креатив
        id: ID креатива
        name: Название креатива
    """

    data: list[StatsData]
    group_id: int = Field(..., alias="groupId")
    id: int
    name: str
    total_data: StatsData = Field(..., alias="totalData")


class CreativesFilter(AvitoObject):
    """CreativesFilter response model.

    Attributes:
        advertisers: Список ID рекламодателей
        campaign_ids: Список ID кампаний
        campaign_types: Список типов кампаний
        group_ids: Список ID групп
        ids: Список ID креативов
        managers: Список ID менеджеров
        payment_models: Список моделей оплаты
        statuses: Список статусов креативов
    """

    advertisers: list[int] | None = None
    campaign_ids: list[int] | None = Field(None, alias="campaignIDs")
    campaign_types: list[CampaignType] | None = Field(None, alias="campaignTypes")
    group_ids: list[int] | None = Field(None, alias="groupIDs")
    ids: list[int] | None = None
    managers: list[int] | None = None
    payment_models: list[CampaignPaymentModel] | None = Field(None, alias="paymentModels")
    statuses: list[CreativesStatus] | None = None
    time_frame: DateRange | None = Field(None, alias="timeFrame")


class CreteIntermediaryIn(AvitoObject):
    """Данные исполнителя по договору. Для доп соглашений не передаем. Для договоров обязательно передавать.

    Attributes:
        actual_address: Почтовый адрес
        inn: ИНН ЮЛ/ИП
        kpp: КПП ЮЛ, для ИП не передаем
        legal_address: Юридически адрес
        long_name: Полное имя ЮЛ/ИП
        ogrn: ОГРНИП для ИП, ОРГН для ЮЛ
        short_name: Короткое имя ЮЛ/ИП
    """

    actual_address: str | None = Field(None, alias="actualAddress")
    inn: str | None = None
    kpp: str | None = None
    legal_address: str | None = Field(None, alias="legalAddress")
    legal_type: LegalType | None = Field(None, alias="legalType")
    long_name: str | None = Field(None, alias="longName")
    ogrn: str | None = None
    short_name: str | None = Field(None, alias="shortName")


class DateRange(AvitoObject):
    """Диапазон дат

    Attributes:
        from_: Дата начала в формате YYYY-MM-DD
        to: Дата окончания в формате YYYY-MM-DD
    """

    from_: date | None = Field(None, alias="from")
    to: date | None = None


class DetailedError(AvitoObject):
    """DetailedError response model."""

    code: str
    errors: list[DetailedErrorItem] | None = None
    message: str


class DetailedErrorItem(AvitoObject):
    """DetailedErrorItem response model.

    Attributes:
        id: ID сущности
        message: Описание ошибки
    """

    id: int
    message: str


class Disclaimer(AvitoObject):
    """Disclaimer response model."""

    inputs: list[DisclaimerInput]
    key: str
    title: str


class DisclaimerInput(AvitoObject):
    """DisclaimerInput response model."""

    description: str
    key: str
    value_type: str = Field(..., alias="valueType")


class EmptyResponse(AvitoObject):
    """EmptyResponse response model."""


class EnumObject(AvitoObject):
    """EnumObject response model."""

    children: list[EnumObject] | None = None
    name: str
    value: str


class FrequencyRule(AvitoObject):
    """Правило частотного ограничения

    Attributes:
        count: Количество показов за указанный период
    """

    count: int = Field(..., ge=0)
    period: FrequencyPeriod


class Group(AvitoObject):
    """Group response model.

    Attributes:
        account_id: ID аккаунта
        actions: Доступные действия с группой
        activity_schedule: Расписание активности по дням
        advertiser_id: ID рекламодателя
        budget: Бюджет группы в рублях с НДС
        budget_kopeks: Бюджет группы в копейках с НДС
        campaign_id: ID кампании
        created_at: Дата создания группы
        frequency_count: Частота показов в рамках периода
        frequency_rules: Правила частотного ограничения
        have_creative: Есть ли в группе креатив
        id: ID группы
        manager_id: ID менеджера, ответственного за кампанию (userID)
        name: Название группы
        period_end_at: Конец периода кампании
        period_start_at: Начало периода кампании
        period_timezone: Таймзона периода показов
        price: Цена в рублях с НДС
        price_kopeks: Цена в копейках с НДС
        start_asap: Запускать как можно скорее
        targeting_age_ids: ID возрастных сегментов
        targeting_audience_ids: ID аудиторий
        targeting_family_status_ids: ID семейного статуса
        targeting_gender_ids: ID пола
        targeting_income_ids: ID доходных сегментов
        targeting_interest_ids: ID интересов
        targeting_location_ids: ID локаций
        targeting_parent_status_ids: ID родительского статуса
        updated_at: Дата обновления группы
        user_id: ID пользователя, создавшего группу
    """

    account_id: int | None = Field(None, alias="accountID")
    actions: list[str] | None = None
    activity_schedule: GroupActivitySchedule | None = Field(None, alias="activitySchedule")
    advertiser_id: int | None = Field(None, alias="advertiserID")
    audience_type: AudienceType | None = Field(None, alias="audienceType")
    budget: int | None = None
    budget_frequency: BudgetFrequency | None = Field(None, alias="budgetFrequency")
    budget_kopeks: int | None = Field(None, alias="budgetKopeks")
    campaign_id: int | None = Field(None, alias="campaignID")
    campaign_type: CampaignType | None = Field(None, alias="campaignType")
    created_at: TZDatetime | None = Field(None, alias="createdAt")
    format: GroupFormat | None = None
    frequency_count: int = Field(..., alias="frequencyCount")
    frequency_period: FrequencyPeriod | None = Field(None, alias="frequencyPeriod")
    frequency_rules: list[FrequencyRule] = Field(..., alias="frequencyRules")
    have_creative: bool | None = Field(None, alias="haveCreative")
    id: int | None = None
    manager_id: int | None = Field(None, alias="managerID")
    name: str | None = None
    pace: Paces | None = None
    payment_model: CampaignPaymentModel | None = Field(None, alias="paymentModel")
    period_end_at: TZDatetime | None = Field(None, alias="periodEndAt")
    period_start_at: TZDatetime | None = Field(None, alias="periodStartAt")
    period_timezone: str | None = Field(None, alias="periodTimezone")
    price: int | None = None
    price_control: GroupPriceControl | None = Field(None, alias="priceControl")
    price_kopeks: int | None = Field(None, alias="priceKopeks")
    schedule_type: ScheduleType | None = Field(None, alias="scheduleType")
    start_asap: bool = Field(..., alias="startASAP")
    status: GroupsStatus | None = None
    targeting_age_ids: list[int] | None = Field(None, alias="targetingAgeIDs")
    targeting_audience_ids: list[str] | None = Field(None, alias="targetingAudienceIDs")
    targeting_family_status_ids: list[int] | None = Field(None, alias="targetingFamilyStatusIDs")
    targeting_gender_ids: list[int] | None = Field(None, alias="targetingGenderIDs")
    targeting_income_ids: list[int] | None = Field(None, alias="targetingIncomeIDs")
    targeting_interest_ids: list[str] | None = Field(None, alias="targetingInterestIDs")
    targeting_location_ids: list[int] | None = Field(None, alias="targetingLocationIDs")
    targeting_parent_status_ids: list[int] | None = Field(None, alias="targetingParentStatusIDs")
    updated_at: TZDatetime | None = Field(None, alias="updatedAt")
    user_id: int | None = Field(None, alias="userID")


class GroupActivitySchedule(AvitoObject):
    """Расписание активности по дням"""

    friday: list[int] | None = None
    monday: list[int] | None = None
    saturday: list[int] | None = None
    sunday: list[int] | None = None
    thursday: list[int] | None = None
    tuesday: list[int] | None = None
    wednesday: list[int] | None = None


class GroupReferenceData(AvitoObject):
    """GroupReferenceData response model."""

    banner_format: list[EnumObject] = Field(..., alias="bannerFormat")
    budget_thresholds: list[ThresholdItem] = Field(..., alias="budgetThresholds")
    price_thresholds: list[ThresholdItem] = Field(..., alias="priceThresholds")
    targeting_age_ids: list[IdNameObject] = Field(..., alias="targetingAgeIDs")
    targeting_audience_ids: list[StringIdNameObject] = Field(..., alias="targetingAudienceIDs")
    targeting_family_status_ids: list[IdNameObject] = Field(..., alias="targetingFamilyStatusIDs")
    targeting_gender_ids: list[IdNameObject] = Field(..., alias="targetingGenderIDs")
    targeting_income_ids: list[IdNameObject] = Field(..., alias="targetingIncomeIDs")
    targeting_interest_ids: list[EnumObject] = Field(..., alias="targetingInterestIDs")
    targeting_location_ids: list[IdNameObject] = Field(..., alias="targetingLocationIDs")
    targeting_parent_status_ids: list[IdNameObject] = Field(..., alias="targetingParentStatusIDs")


class GroupStatistic(AvitoObject):
    """Статистика группы

    Attributes:
        data: Статистика в разбивке по дням
        id: ID группы
        name: Название группы
    """

    data: list[StatsData]
    id: int
    name: str
    total_data: StatsData = Field(..., alias="totalData")


class GroupsFilter(AvitoObject):
    """GroupsFilter response model.

    Attributes:
        advertisers: Список ID рекламодателей
        campaign_ids: Список ID кампаний
        ids: Список ID групп
        managers: Список ID менеджеров
        paces: Скорости показов
        payment_models: Список моделей оплаты
        statuses: Список статусов групп
    """

    advertisers: list[int] | None = None
    campaign_ids: list[int] | None = Field(None, alias="campaignIDs")
    ids: list[int] | None = None
    managers: list[int] | None = None
    paces: list[Paces] | None = None
    payment_models: list[CampaignPaymentModel] | None = Field(None, alias="paymentModels")
    statuses: list[GroupsStatus] | None = None
    time_frame: DateRange | None = Field(None, alias="timeFrame")


class IdNameObject(AvitoObject):
    """IdNameObject response model."""

    children: list[IdNameObject] | None = None
    id: int
    name: str


class KktuItem(AvitoObject):
    """KktuItem response model."""

    category: str
    code: str
    level: int
    sub_category: str = Field(..., alias="subCategory")
    title: str


class LegalInfo(AvitoObject):
    """LegalInfo response model.

    Attributes:
        age_restriction: Возрастное ограничение
        description: Юридическое описание
        kktu: ККТУ
        notes: Примечания
    """

    age_restriction: int | None = Field(None, alias="ageRestriction")
    description: str | None = None
    kktu: str | None = None
    notes: str | None = None


class ObjectSize(AvitoObject):
    """ObjectSize response model."""

    height: int
    width: int


class ShortAccount(AvitoObject):
    """ShortAccount response model."""

    id: int
    short_name: str = Field(..., alias="shortName")


class ShortAccountWithBalance(AvitoObject):
    """ShortAccountWithBalance response model."""

    account: ShortAccount
    balance: V1GetAccountBalanceByIdOut


class ShortAccountWithContract(AvitoObject):
    """ShortAccountWithContract response model."""

    account: ShortAccount
    contract: ContractForChildAccount | None = None


class StatsData(AvitoObject):
    """Данные статистики за период

    Attributes:
        clicks: Количество кликов
        cpc: Средняя стоимость CPC
        cpm: Средняя стоимость CPM
        ctr: CTR (Click-Through Rate)
        q25: Доля просмотров видео на 25%
        q50: Доля просмотров видео на 50%
        q75: Доля просмотров видео на 75%
        spend: Потрачено денег в рублях
        spend_bonus: Потрачено бонусов в рублях
        spend_bonus_kopeks: Потрачено бонусов в копейках
        spend_kopeks: Потрачено денег в копейках
        timestamp: Временная метка (гранулярность по дням). Заполняется в data[] и отсутствует в totalData.
        video_views100: Количество просмотров видео на 100%
        video_views25: Количество просмотров видео на 25%
        video_views50: Количество просмотров видео на 50%
        video_views75: Количество просмотров видео на 75%
        views: Количество показов
        vtr: Доля просмотров видео на 100%
    """

    clicks: int
    cpc: float
    cpm: float
    ctr: float
    q25: float | None = None
    q50: float | None = None
    q75: float | None = None
    spend: int
    spend_bonus: int = Field(..., alias="spendBonus")
    spend_bonus_kopeks: int | None = Field(None, alias="spendBonusKopeks")
    spend_kopeks: int | None = Field(None, alias="spendKopeks")
    timestamp: TZDatetime | None = None
    video_views100: int | None = Field(None, alias="videoViews100")
    video_views25: int | None = Field(None, alias="videoViews25")
    video_views50: int | None = Field(None, alias="videoViews50")
    video_views75: int | None = Field(None, alias="videoViews75")
    views: int
    vtr: float | None = None


class StringIdNameObject(AvitoObject):
    """StringIdNameObject response model."""

    id: str
    name: str


class TemplateData(AvitoObject):
    """TemplateData response model."""

    fields: list[TemplateField]
    is_optional: bool = Field(..., alias="isOptional")
    logo_ratio: list[ObjectSize] = Field(..., alias="logoRatio")
    media_ratio: ObjectSize = Field(..., alias="mediaRatio")
    platforms: list[str]
    template_id: int = Field(..., alias="templateID")


class TemplateField(AvitoObject):
    """TemplateField response model."""

    can_override: bool | None = Field(None, alias="canOverride")
    default_value: str | None = Field(None, alias="defaultValue")
    field_type: str = Field(..., alias="fieldType")
    is_required: bool | None = Field(None, alias="isRequired")
    key: str


class ThresholdItem(AvitoObject):
    """ThresholdItem response model.

    Attributes:
        value: Минимальное значение в рублях
        value_kopeks: Минимальное значение в копейках
    """

    group_format: GroupFormat = Field(..., alias="groupFormat")
    value: int
    value_kopeks: int = Field(..., alias="valueKopeks")


class User(AvitoObject):
    """User response model.

    Attributes:
        has_logged_in: Флаг, показывающий, заходил ли пользователь в аккаунт
        id: ID пользователя
    """

    has_logged_in: bool = Field(..., alias="hasLoggedIn")
    id: int
    role: UserRole


class V1AddUserIn(AvitoObject):
    """Payload добавления пользователя в аккаунт

    Attributes:
        user_id: ID пользователя авито
    """

    role: UserRole
    user_id: int = Field(..., alias="userId")


class V1ChangeBudgetIn(AvitoObject):
    """Payload для изменения бюджета группы

    Attributes:
        budget: Новый бюджет группы в рублях с НДС
    """

    budget: int = Field(..., ge=1)


class V1ChangePriceIn(AvitoObject):
    """Payload для изменения ставки группы

    Attributes:
        price: Новая ставка группы в рублях с НДС
    """

    price: int = Field(..., ge=1)


class V1CopyCampaignGroup(AvitoObject):
    """Группа и список креативов для копирования

    Attributes:
        creative_ids: Список ID копируемых креативов. Если не передано или передано пустым списком, копируется только группа
        group_id: ID копируемой группы
    """

    creative_ids: list[int] | None = Field(None, alias="creativeIDs")
    group_id: int = Field(..., ge=1, alias="groupID")


class V1CopyCampaignIn(AvitoObject):
    """Payload копирования кампании аккаунта

    Attributes:
        campaign_id: ID копируемой кампании
        groups: Группы и креативы, которые нужно скопировать вместе с кампанией. Если не передано или передано пустым списком, копируется только кампания
    """

    campaign_id: int = Field(..., ge=1, alias="campaignID")
    groups: list[V1CopyCampaignGroup] | None = None


class V1CopyCampaignOut(AvitoObject):
    """V1CopyCampaignOut response model.

    Attributes:
        campaign_id: ID новой кампании
    """

    campaign_id: int = Field(..., ge=1, alias="campaignID")


class V1CopyGroupIn(AvitoObject):
    """Payload копирования группы аккаунта

    Attributes:
        creative_ids: Список ID креативов, которые нужно скопировать вместе с группой. Если не передано или передано пустым списком, копируется только группа
        group_id: ID копируемой группы
    """

    creative_ids: list[int] | None = Field(None, alias="creativeIDs")
    group_id: int = Field(..., ge=1, alias="groupID")


class V1CopyGroupOut(AvitoObject):
    """V1CopyGroupOut response model.

    Attributes:
        new_group_id: ID новой группы
    """

    new_group_id: int = Field(..., ge=1, alias="newGroupID")


class V1CreateAccountIn(AvitoObject):
    """Payload создания аккаунта

    Attributes:
        actual_address: Фактический адрес. Если не передан, используется legalAddress.
        contact: Контактное лицо
        inn: ИНН организации или ИП
        kpp: КПП организации
        legal_address: Юридический адрес или адрес регистрации
        long_name: Полное наименование организации или ИП
        ogrn: ОГРН или ОГРНИП
        short_name: Краткое название аккаунта
    """

    actual_address: str | None = Field(None, alias="actualAddress")
    contact: V1CreateAccountInContact
    inn: str
    kpp: str | None = None
    legal_address: str = Field(..., alias="legalAddress")
    legal_type: LegalType = Field(..., alias="legalType")
    long_name: str = Field(..., alias="longName")
    ogrn: str
    short_name: str = Field(..., alias="shortName")


class V1CreateAccountInContact(AvitoObject):
    """Контактное лицо

    Attributes:
        name: ФИО контактного лица
        phone: Контактный телефон
    """

    name: str
    phone: str


class V1CreateAccountOut(AvitoObject):
    """V1CreateAccountOut response model.

    Attributes:
        warnings: Предупреждения о частично невыполненных sandbox-операциях. Если массив пустой, аккаунт подготовлен полностью.
    """

    account_id: int = Field(..., alias="accountID")
    warnings: list[str]


class V1CreateAdvertiserIn(AvitoObject):
    """Payload создания рекламодателя

    Attributes:
        actual_address: Фактический адрес. Если не передан, используется legalAddress. Пример корректного адреса: 127015, г. Москва, ул. Лесная, д. 7
        inn: ИНН организации
        kpp: КПП организации
        legal_address: Юридический адрес или адрес регистрации. Пример корректного адреса: 127015, г. Москва, ул. Лесная, д. 7
        long_name: Полное наименование организации или ИП
        ogrn: ОГРН или ОГРНИП
        short_name: Краткое наименование организации или ИП
    """

    actual_address: str | None = Field(None, alias="actualAddress")
    inn: str
    kpp: str | None = None
    legal_address: str = Field(..., alias="legalAddress")
    legal_role: LegalRole = Field(..., alias="legalRole")
    legal_type: LegalType = Field(..., alias="legalType")
    long_name: str = Field(..., alias="longName")
    ogrn: str
    short_name: str = Field(..., alias="shortName")


class V1CreateCampaignIn(AvitoObject):
    """Payload запроса на создание кампании

    Attributes:
        additional_agreement_id: ID дополнительного соглашения
        advertiser_id: ID рекламодателя. Может быть null, если для аккаунта включен флаг sSelfAdvertisingEnabled=true (используется 1 кейс)
        campaign_goals: Цели кампании. Пока поддерживается только пустой массив
        contract_id: ID договора. Может быть null, если advertiserID=null. Если advertiserID задан, поле обязательно и принимает контракт 2 или 3 кейса
        landing_page: Посадочная страница. Пока поле не сохраняется
        manager_id: ID менеджера, ответственного за кампанию (userID)
        name: Название кампании
    """

    additional_agreement_id: int | None = Field(None, alias="additionalAgreementID")
    advertiser_id: int | None = Field(None, alias="advertiserID")
    campaign_goals: list[str] = Field(..., max_length=0, alias="campaignGoals")
    campaign_strategy: CampaignStrategy = Field(..., alias="campaignStrategy")
    campaign_type: CreateCampaignType = Field(..., alias="campaignType")
    contract_id: int | None = Field(None, alias="contractID")
    goal_type: CampaignGoalType = Field(..., alias="goalType")
    landing_page: str | None = Field(None, alias="landingPage")
    landing_type: CampaignLandingType = Field(..., alias="landingType")
    manager_id: int = Field(..., alias="managerID")
    name: str
    payment_model: CreateCampaignPaymentModel = Field(..., alias="paymentModel")


class V1CreateContractIn(AvitoObject):
    """Payload запроса на создание договора. Базово обязательны `description`, `advertiserId`, `type`. Для `type = service` дополнительно передаются `subject`, `isReportingRequired`, `date`, `number`; `cid` не передаётся. Для `type = intermediary` дополнительно передаются `subject`, `object`, `isReportingRequired`, `isFundsAllocationToPrincipal`, `date`, `number`; `cid` не передаётся. Для `type = external` передаётся `cid`; `parentId` не передаётся. Дополнительное соглашение создаётся через `parentId` к родительскому договору, без отдельного `type = additional`. Если `parentId` задан, `intermediary` не передаётся; если `parentId` не задан, `intermediary` обязателен.

    Attributes:
        advertiser_id: Id рекламодателя. Указываем только рекламодателей которые не являются аккаунтом. Если рекламодатель и аккаунт одно и тоже ЮЛ, договор создавать не надо
        cid: CID внешнего договора, заполняется только для type = external.
        date_: Дата в формате YYYY-MM-DD. Можно не передавать только для type = external.
        is_funds_allocation_to_principal: Денежные средства на размещение рекламы идут в сторону принципала
        is_reporting_required: На исполнителе лежит обязанность отчитываться по креативам
        number: Номер договора. Можно не передавать только для type = external.
        parent_id: ID родительского договора для доп. соглашения
    """

    advertiser_id: int = Field(..., alias="advertiserId")
    cid: str | None = None
    date_: date | None = Field(None, alias="date")
    description: ContractCounterpartyType
    intermediary: CreteIntermediaryIn | None = None
    is_funds_allocation_to_principal: bool | None = Field(
        None, alias="isFundsAllocationToPrincipal"
    )
    is_reporting_required: bool | None = Field(None, alias="isReportingRequired")
    number: str | None = None
    object: ContractAction | None = None
    parent_id: int | None = Field(None, alias="parentId")
    subject: ContractSubject | None = None
    type_: ContractType = Field(..., alias="type")


class V1CreateGroupIn(AvitoObject):
    """Payload запроса на создание группы

    Attributes:
        budget: Бюджет группы в рублях с НДС
        campaign_id: ID кампании
        frequency_rules: Правила частотного ограничения. Если передано, используется как основной формат; frequencyCount/frequencyPeriod сохраняются для обратной совместимости
        name: Название группы
        period_end_at: Окончание периода показов в формате RFC3339, например 2026-12-31T23:59:59+03:00
        period_start_at: Начало периода показов в формате RFC3339, например 2026-07-01T10:00:00+03:00
        price: Ставка в рублях с НДС
        start_asap: Запускать как можно скорее
        targeting_age_ids: ID возрастных сегментов
        targeting_family_status_ids: ID family status сегментов
        targeting_gender_ids: ID пола
        targeting_income_ids: ID доходных сегментов
        targeting_interest_ids: ID интересов
        targeting_location_ids: ID локаций
        targeting_parent_status_ids: ID parent status сегментов
    """

    activity_schedule: CreateGroupActivitySchedule | None = Field(None, alias="activitySchedule")
    banner_format: BannerFormat = Field(..., alias="bannerFormat")
    budget: int = Field(..., ge=1)
    budget_frequency: BudgetFrequency = Field(..., alias="budgetFrequency")
    campaign_id: int = Field(..., alias="campaignID")
    frequency_count: int = Field(..., alias="frequencyCount")
    frequency_period: FrequencyPeriod = Field(..., alias="frequencyPeriod")
    frequency_rules: list[FrequencyRule] | None = Field(None, max_length=2, alias="frequencyRules")
    name: str = Field(..., min_length=1, max_length=99)
    pace: Paces
    period_end_at: TZDatetime | None = Field(None, alias="periodEndAt")
    period_start_at: TZDatetime | None = Field(None, alias="periodStartAt")
    period_timezone: PeriodTimezone = Field(..., alias="periodTimezone")
    price: int = Field(..., ge=1)
    price_control: GroupPriceControl = Field(..., alias="priceControl")
    schedule_type: ScheduleType = Field(..., alias="scheduleType")
    start_asap: bool = Field(..., alias="startASAP")
    targeting_age_ids: list[int] = Field(..., alias="targetingAgeIDs")
    targeting_family_status_ids: list[int] | None = Field(None, alias="targetingFamilyStatusIDs")
    targeting_gender_ids: list[int] = Field(..., alias="targetingGenderIDs")
    targeting_income_ids: list[int] = Field(..., alias="targetingIncomeIDs")
    targeting_interest_ids: list[str] = Field(..., alias="targetingInterestIDs")
    targeting_location_ids: list[int] = Field(..., alias="targetingLocationIDs")
    targeting_parent_status_ids: list[int] | None = Field(None, alias="targetingParentStatusIDs")


class V1CreateNonPayerAccountIn(AvitoObject):
    """Payload создания аккаунта

    Attributes:
        is_self_advertising_enabled: Флаг разрешающий рекламировать родительский аккаунт. Если вам надо рекламировать нового рекламодателя без возможности рекламировать родителя, выставлять - false
        short_name: Краткое название дочернего аккаунта, меньше 64 символов
    """

    is_self_advertising_enabled: bool = Field(..., alias="isSelfAdvertisingEnabled")
    short_name: str = Field(..., alias="shortName")


class V1CreateNonPayerAccountOut(AvitoObject):
    """V1CreateNonPayerAccountOut response model."""

    account_id: int = Field(..., alias="accountID")
    client_key: str = Field(..., alias="clientKey")
    client_secret: str = Field(..., alias="clientSecret")


class V1GetAccountBalanceByIdOut(AvitoObject):
    """V1GetAccountBalanceByIdOut response model.

    Attributes:
        balance: Баланс аккаунта в рублях
        balance_kopeks: Баланс аккаунта в копейках
        bonus_balance: Баланс бонусов на аккаунте в рублях
        bonus_balance_kopeks: Баланс бонусов на аккаунте в копейках
    """

    balance: int
    balance_kopeks: int = Field(..., alias="balanceKopeks")
    bonus_balance: int = Field(..., alias="bonusBalance")
    bonus_balance_kopeks: int = Field(..., alias="bonusBalanceKopeks")


class V1GetAccountByIdOut(AvitoObject):
    """V1GetAccountByIdOut response model."""

    account: Account | None = None


class V1GetAdvertisersListIn(AvitoObject):
    """Payload запроса на получение списка рекламодателей

    Attributes:
        limit: Количество записей на странице
        page: Номер страницы
    """

    filter: AdvertiserFilter
    limit: int = Field(..., ge=1, le=100)
    page: int = Field(..., ge=1)


class V1GetAdvertisersListOut(AvitoObject):
    """V1GetAdvertisersListOut response model."""

    advertisers: list[Advertiser]
    total: int


class V1GetCampaignByIdWithFieldsOut(AvitoObject):
    """V1GetCampaignByIdWithFieldsOut response model."""

    campaign: Campaign
    editable_fields: list[CampaignFieldName] = Field(..., alias="editableFields")
    warnings: list[str]


class V1GetCampaignStatisticIn(AvitoObject):
    """Request body для запроса статистики по кампании. Максимальный период между dateFrom и dateTo — 100 дней.

    Attributes:
        date_from: Дата начала периода в формате YYYY-MM-DD
        date_to: Дата окончания периода в формате YYYY-MM-DD
    """

    date_from: date = Field(..., alias="dateFrom")
    date_to: date = Field(..., alias="dateTo")


class V1GetCampaignStatisticOut(AvitoObject):
    """Статистика по кампании

    Attributes:
        creatives: Статистика по креативам кампании
        groups: Статистика по группам кампании
    """

    campaign: CampaignStatistic
    creatives: list[CreativeStatistic]
    groups: list[GroupStatistic]


class V1GetCampaignsListIn(AvitoObject):
    """Payload запроса на получение списка кампаний

    Attributes:
        limit: Количество записей на странице
        page: Номер страницы
    """

    filter: CampaignsFilter
    limit: int = Field(..., ge=1, le=100)
    page: int = Field(..., ge=1)


class V1GetCampaignsListOut(AvitoObject):
    """V1GetCampaignsListOut response model."""

    campaigns: list[Campaign]
    total: int


class V1GetChildAccountsListOut(AvitoObject):
    """V1GetChildAccountsListOut response model."""

    children: list[ShortAccountWithContract]


class V1GetChildAccountsWithBalancesListOut(AvitoObject):
    """V1GetChildAccountsWithBalancesListOut response model."""

    children: list[ShortAccountWithBalance]


class V1GetContractsListIn(AvitoObject):
    """Payload запроса на получение списка договоров

    Attributes:
        limit: Количество записей на странице
        page: Номер страницы
    """

    filter: ContractsFilter
    limit: int = Field(..., ge=1, le=100)
    page: int = Field(..., ge=1)


class V1GetContractsListOut(AvitoObject):
    """V1GetContractsListOut response model."""

    contracts: list[Contract]
    total: int


class V1GetCreativesListIn(AvitoObject):
    """Payload запроса на получение списка креативов

    Attributes:
        limit: Количество записей на странице
        page: Номер страницы
    """

    filter: CreativesFilter
    limit: int = Field(..., ge=1, le=100)
    page: int = Field(..., ge=1)


class V1GetCreativesListOut(AvitoObject):
    """V1GetCreativesListOut response model."""

    creatives: list[Creative]
    total: int


class V1GetCreativesStatisticIn(AvitoObject):
    """Request body для запроса статистики по креативам кампании. Максимальный период между dateFrom и dateTo — 100 дней.

    Attributes:
        creative_ids: Список ID креативов для получения статистики
        date_from: Дата начала периода в формате YYYY-MM-DD
        date_to: Дата окончания периода в формате YYYY-MM-DD
    """

    creative_ids: list[int] = Field(..., min_length=1, alias="creativeIDs")
    date_from: date = Field(..., alias="dateFrom")
    date_to: date = Field(..., alias="dateTo")


class V1GetCreativesStatisticOut(AvitoObject):
    """Статистика по креативам кампании

    Attributes:
        creatives: Статистика по креативам кампании
    """

    creatives: list[CreativeStatistic]


class V1GetGroupReferenceDataOut(AvitoObject):
    """V1GetGroupReferenceDataOut response model."""

    reference_data: GroupReferenceData = Field(..., alias="referenceData")


class V1GetGroupsListIn(AvitoObject):
    """Payload запроса на получение списка кампаний

    Attributes:
        limit: Количество записей на странице
        page: Номер страницы
    """

    filter: GroupsFilter
    limit: int = Field(..., ge=1, le=100)
    page: int = Field(..., ge=1)


class V1GetGroupsListOut(AvitoObject):
    """V1GetGroupsListOut response model."""

    groups: list[Group]
    total: int


class V1GetGroupsStatisticIn(AvitoObject):
    """Request body для запроса статистики по группам кампании. Максимальный период между dateFrom и dateTo — 100 дней.

    Attributes:
        date_from: Дата начала периода в формате YYYY-MM-DD
        date_to: Дата окончания периода в формате YYYY-MM-DD
        group_ids: Список ID групп для получения статистики
    """

    date_from: date = Field(..., alias="dateFrom")
    date_to: date = Field(..., alias="dateTo")
    group_ids: list[int] = Field(..., min_length=1, alias="groupIDs")


class V1GetGroupsStatisticOut(AvitoObject):
    """Статистика по группам кампании

    Attributes:
        groups: Статистика по группам кампании
    """

    groups: list[GroupStatistic]


class V1GetHtmlOut(AvitoObject):
    """V1GetHtmlOut response model.

    Attributes:
        error_reason: Причина ошибки (заполнено если status = ERROR)
        id: ID HTML
        url: URL HTML файла
    """

    error_reason: str | None = Field(None, alias="errorReason")
    id: str
    status: V1GetHtmlOutStatus
    url: str | None = None


class V1GetImageOut(AvitoObject):
    """V1GetImageOut response model.

    Attributes:
        id: ID изображения
        url: URL изображения
    """

    id: int
    url: str


class V1GetLegalAttachmentsOut(AvitoObject):
    """V1GetLegalAttachmentsOut response model.

    Attributes:
        id: ID файла
        public_url: Публичный URL файла
    """

    id: str
    public_url: str = Field(..., alias="publicUrl")


class V1GetUsersListByAccountOut(AvitoObject):
    """V1GetUsersListByAccountOut response model."""

    total: int
    users: list[User]


class V1GetVideoOut(AvitoObject):
    """V1GetVideoOut response model.

    Attributes:
        error_reason: Причина ошибки обработки видео
        id: ID видео
        status: Статус видео
        thumbnail_url: URL превью
        thumbnail_video_url: Видео-превью от хостинга
        title: Название видео
        video_url: URL видео
    """

    error_reason: str | None = Field(None, alias="errorReason")
    id: str
    status: str
    thumbnail_url: str | None = Field(None, alias="thumbnailUrl")
    thumbnail_video_url: str | None = Field(None, alias="thumbnailVideoUrl")
    title: str
    video_url: str | None = Field(None, alias="videoUrl")


class V1LaunchGroupIn(AvitoObject):
    """Payload запуска группы аккаунта

    Attributes:
        group_id: ID группы
    """

    group_id: int = Field(..., alias="groupID")


class V1ReferenceDataCreateCreativeOut(AvitoObject):
    """V1ReferenceDataCreateCreativeOut response model."""

    classifier: list[KktuItem]
    disclaimers: list[Disclaimer]
    templates: list[TemplateData]


class V1SetUserRoleIn(AvitoObject):
    """Payload изменение роли пользователя в аккаунте

    Attributes:
        user_id: ID пользователя авито
    """

    role: UserRole
    user_id: int = Field(..., alias="userId")


class V1TransferBonusIn(AvitoObject):
    """Payload Перевода денег между аккаунтом родителем и дочками неплательщиками

    Attributes:
        account_id_to: accountId на который перевести
        amount: Сумма бонусов, не меньше 1 бонуса
    """

    account_id_to: int = Field(..., alias="accountIdTo")
    amount: int = Field(..., ge=1)


class V1TransferFundsIn(AvitoObject):
    """Payload Перевода денег между аккаунтом родителем и дочками неплательщиками

    Attributes:
        account_id_to: accountId на который перевести
        amount: Сумма перевода в рублях, не меньше 1 рубля
    """

    account_id_to: int = Field(..., alias="accountIdTo")
    amount: int = Field(..., ge=1)


class V1UploadHtmlOut(AvitoObject):
    """V1UploadHtmlOut response model.

    Attributes:
        id: ID загруженного HTML
    """

    id: str


class V1UploadImageOut(AvitoObject):
    """V1UploadImageOut response model.

    Attributes:
        id: ID загруженного изображения
        url: URL изображения
    """

    id: int
    url: str


class V1UploadLegalAttachmentsOut(AvitoObject):
    """V1UploadLegalAttachmentsOut response model.

    Attributes:
        id: ID загруженного документа
        name: Имя файла
        url: Публичный URL файла
    """

    id: str
    name: str
    url: str


class V1UploadVideoOut(AvitoObject):
    """V1UploadVideoOut response model.

    Attributes:
        id: ID загруженного видео
    """

    id: str


class V1CreateAccountContact(AvitoObject):
    """Контактное лицо

    Attributes:
        name: ФИО контактного лица
        phone: Контактный телефон
    """

    name: str
    phone: str


class ActivityScheduleDay(RootModel[list[int]]):
    """Root wrapper for a top-level ``list[int]`` response."""


class ActivityScheduleHours(RootModel[list[int]]):
    """Root wrapper for a top-level ``list[int]`` response."""


class DetailedErrors(RootModel[list[DetailedErrorItem]]):
    """Root wrapper for a top-level ``list[DetailedErrorItem]`` response."""


class FrequencyCount(RootModel[int]):
    """Root wrapper for a top-level ``int`` response."""
