# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""CPA-аукцион — domain models (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from pydantic import Field

from ._base import AvitoObject


class Error(AvitoObject):
    """Error response model.

    See: https://developers.avito.ru/api-catalog/auction/documentation

    Attributes:
        message: Текст ошибки
    """

    message: str


class TooManyRequestsError(AvitoObject):
    """TooManyRequestsError response model.

    See: https://developers.avito.ru/api-catalog/auction/documentation
    """

    error: TooManyRequestsErrorError | None = None


class TooManyRequestsErrorError(AvitoObject):
    """TooManyRequestsErrorError response model.

    See: https://developers.avito.ru/api-catalog/auction/documentation

    Attributes:
        code: Код ошибки
    """

    code: int


class GetUserBidsResponse(AvitoObject):
    """GetUserBidsResponse response model.

    See: https://developers.avito.ru/api-catalog/auction/documentation
    """

    items: list[GetUserBidsResponseItems] | None = None


class GetUserBidsResponseItems(AvitoObject):
    """Информация о ставке для объявления

    See: https://developers.avito.ru/api-catalog/auction/documentation

    Attributes:
        expiration_time: Время истечения срока действия ставки (RFC3339)
        item_id: Идентификатор объявления
        price_penny: Текущая цена в копейках
    """

    available_prices: list[GetUserBidsResponseItemsAvailablePrices] = Field(
        ..., alias="availablePrices"
    )
    expiration_time: str = Field(..., alias="expirationTime")
    item_id: int = Field(..., alias="itemID")
    price_penny: int = Field(..., alias="pricePenny")


class GetUserBidsResponseItemsAvailablePrices(AvitoObject):
    """Доступная ставка

    See: https://developers.avito.ru/api-catalog/auction/documentation

    Attributes:
        goodness: Показатель \"хорошести\" цены
        price_penny: Цена в копейках
    """

    goodness: int
    price_penny: int = Field(..., alias="pricePenny")


class SaveItemBidsItems(AvitoObject):
    """Ставка по объявлению

    See: https://developers.avito.ru/api-catalog/auction/documentation

    Attributes:
        expiration_time: Время окончания действия ставки в формате RFC3339 (2022-06-29T12:34:34+03:00). Отсутствие поля либо null означает бесконечно действующую ставку
        item_id: Идентификатор объявления
        price_penny: Цена в копейках
    """

    expiration_time: str | None = Field(None, alias="expirationTime")
    item_id: int = Field(..., alias="itemID")
    price_penny: int = Field(..., alias="pricePenny")
