# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Автостратегия — domain models (auto-generated from the Avito OpenAPI spec).

See: https://developers.avito.ru/api-catalog/autostrategy/documentation"""

from __future__ import annotations

from datetime import date

from pydantic import Field, RootModel

from ..enums.autostrategy import (
    CampaignCampaignType,
    CreateCampaignRequestBodyCampaignType,
    GetAutostrategyCampaignsOrderByColumn,
    GetAutostrategyCampaignsOrderByDirection,
    GetBudgetRequestBodyCampaignType,
    GetCampaignInfoForecastResultCallsLackReason,
    GetCampaignInfoForecastResultViewsLackReason,
    GetCampaignsRequestBodyOrderByColumn,
    GetCampaignsRequestBodyOrderByDirection,
)
from ._base import AvitoObject
from ._shared import CampaignIdResponse, MessageResponse
from .common import TZDatetime


class Budget(AvitoObject):
    """Бюджет кампании

    Attributes:
        maximal: Максимальный бюджет кампании в рублях. **Возвращается только для типа кампании `AP`**
        minimal: Минимальный возможный бюджет кампании в рублях
        price_ranges: Ценовые диапазоны покрытия склада (**только для типа кампании `AP`**) и предсказания.
        recommended: Рекомендуемый бюджет кампании в рублях
    """

    maximal: BudgetMaximal | None = None
    minimal: BudgetMinimal | None = None
    price_ranges: list[BudgetPriceRanges] | None = Field(None, alias="priceRanges")
    recommended: BudgetRecommended | None = None


class BudgetMaximal(AvitoObject):
    """Максимальный бюджет кампании в рублях. **Возвращается только для типа кампании `AP`**

    Attributes:
        bonus: Значение бюджета в рублях, которое можно списать за счет бонусов
        calls_from: Нижняя граница предсказания звонков (только для типа кампании Автопилот)
        calls_to: Верхняя граница предсказания звонков (только для типа кампании Автопилот)
        real: Бюджет в рублях
        total: Суммарный бюджет в рублях
        views_from: Нижняя граница предсказания просмотров (только для типа кампании Автопилот)
        views_to: Верхняя граница предсказания просмотров (только для типа кампании Автопилот)
    """

    bonus: int | None = None
    calls_from: int | None = Field(None, alias="callsFrom")
    calls_to: int | None = Field(None, alias="callsTo")
    real: int | None = None
    total: int | None = None
    views_from: int | None = Field(None, alias="viewsFrom")
    views_to: int | None = Field(None, alias="viewsTo")


class BudgetMinimal(AvitoObject):
    """Минимальный возможный бюджет кампании в рублях

    Attributes:
        bonus: Значение бюджета в рублях, которое можно списать за счет бонусов
        calls_from: Нижняя граница предсказания звонков (только для типа кампании Автопилот)
        calls_to: Верхняя граница предсказания звонков (только для типа кампании Автопилот)
        real: Бюджет в рублях
        total: Суммарный бюджет в рублях
        views_from: Нижняя граница предсказания просмотров (только для типа кампании Автопилот)
        views_to: Верхняя граница предсказания просмотров (только для типа кампании Автопилот)
    """

    bonus: int | None = None
    calls_from: int | None = Field(None, alias="callsFrom")
    calls_to: int | None = Field(None, alias="callsTo")
    real: int | None = None
    total: int | None = None
    views_from: int | None = Field(None, alias="viewsFrom")
    views_to: int | None = Field(None, alias="viewsTo")


class BudgetPriceRanges(AvitoObject):
    """BudgetPriceRanges response model.

    Attributes:
        calls_from: Нижняя граница предсказания звонков
        calls_to: Верхняя граница предсказания звонков
        percent: Процент покрытия склада **Возвращается только для типа кампании `AP`**
        price_from: Начало ценового диапазона
        price_to: Конец ценового диапазона
        views_from: Нижняя граница предсказания просмотров
        views_to: Верхняя граница предсказания просмотров
    """

    calls_from: int = Field(..., alias="callsFrom")
    calls_to: int = Field(..., alias="callsTo")
    percent: int | None = None
    price_from: int = Field(..., alias="priceFrom")
    price_to: int = Field(..., alias="priceTo")
    views_from: int = Field(..., alias="viewsFrom")
    views_to: int = Field(..., alias="viewsTo")


class BudgetRecommended(AvitoObject):
    """Рекомендуемый бюджет кампании в рублях

    Attributes:
        bonus: Значение бюджета в рублях, которое можно списать за счет бонусов
        calls_from: Нижняя граница предсказания звонков (только для типа кампании Автопилот)
        calls_to: Верхняя граница предсказания звонков (только для типа кампании Автопилот)
        real: Бюджет в рублях
        total: Суммарный бюджет в рублях
        views_from: Нижняя граница предсказания просмотров (только для типа кампании Автопилот)
        views_to: Верхняя граница предсказания просмотров (только для типа кампании Автопилот)
    """

    bonus: int | None = None
    calls_from: int | None = Field(None, alias="callsFrom")
    calls_to: int | None = Field(None, alias="callsTo")
    real: int | None = None
    total: int | None = None
    views_from: int | None = Field(None, alias="viewsFrom")
    views_to: int | None = Field(None, alias="viewsTo")


class Campaign(AvitoObject):
    """Кампания

    Attributes:
        balance: Оставшиеся средства от всего бюджета на продвижение кампании
        budget: Бюджет кампании в рублях
        campaign_id: Идентификатор кампании
        campaign_type: Тип кампании. Возможные типы: `AS` - Автостратегия. Cтратегия расчитана на определенное количество автомобилей, которые находятся в продаже `AP` - Автопилот. Cтратегия расчитана на все автомобили, которые находятся в продаже
        create_time: Время создания кампании
        description: Новое описание кампании
        finish_time: Время окончания кампании
        items_count: Количество объявлений, которые продвигаются с помощью данной кампании
        start_time: Время начала кампании
        status_id: Статусы кампании для выборки. Возможные статусы: `0` - Черновик, дата старта сегодня или раньше, денег на балансе нет `1` - Активная кампания, участвует в аукционе `2` - Кампания приостановлена `3` - Кампания удалена `4` - Кампания остановлена `5` - Кампания запланирована, дата старта завтра или позже, на балансе есть деньги
        title: Новое название кампании
        update_time: Время последнего обновления кампании
        user_id: Идентификатор пользователя-владельца кампании
        version: Текущая версия кампании
    """

    balance: int | None = None
    budget: int | None = None
    campaign_id: int | None = Field(None, alias="campaignId")
    campaign_type: CampaignCampaignType | None = Field(None, alias="campaignType")
    create_time: TZDatetime | None = Field(None, alias="createTime")
    description: str | None = None
    finish_time: TZDatetime | None = Field(None, alias="finishTime")
    items_count: int | None = Field(None, alias="itemsCount")
    start_time: TZDatetime | None = Field(None, alias="startTime")
    status_id: int | None = Field(None, alias="statusId")
    title: str | None = None
    update_time: TZDatetime | None = Field(None, alias="updateTime")
    user_id: int | None = Field(None, alias="userId")
    version: int | None = None


class Campaigns(AvitoObject):
    """Список кампаний

    Attributes:
        campaigns: Список кампаний, удовлетворяющих фильтрам, с учетом смещения и ограничения
        total_count: Общее количество кампаний, удовлетворяющих фильтрам
    """

    campaigns: list[Campaign] | None = None
    total_count: int | None = Field(None, alias="totalCount")


class CreateCampaignBadRequestError(AvitoObject):
    """CreateCampaignBadRequestError response model."""

    error: CreateCampaignBadRequestErrorError | None = None


class CreateCampaignBadRequestErrorError(AvitoObject):
    """CreateCampaignBadRequestErrorError response model.

    Attributes:
        field_errors: Описание ошибок валидации полей
        message: Сообщение об ошибке
    """

    field_errors: CreateCampaignBadRequestErrorErrorFieldErrors | None = Field(
        None, alias="fieldErrors"
    )
    message: str


class CreateCampaignBadRequestErrorErrorFieldErrors(AvitoObject):
    """Описание ошибок валидации полей

    Attributes:
        budget: Ошибка валидации поля **budget**
        budget_bonus: Ошибка валидации поля **budgetBonus**
        budget_real: Ошибка валидации поля **budgetReal**
        campaign_type: Ошибка валидации поля **campaignType**
        description: Ошибка валидации поля **description**
        finish_time: Ошибка валидации поля **finishTime**
        items: Ошибка валидации поля **items**
        start_time: Ошибка валидации поля **startTime**
        title: Ошибка валидации поля **title**
    """

    budget: str | None = None
    budget_bonus: str | None = Field(None, alias="budgetBonus")
    budget_real: str | None = Field(None, alias="budgetReal")
    campaign_type: str | None = Field(None, alias="campaignType")
    description: str | None = None
    finish_time: str | None = Field(None, alias="finishTime")
    items: str | None = None
    start_time: str | None = Field(None, alias="startTime")
    title: str | None = None


class CreateCampaignRequestBody(AvitoObject):
    """CreateCampaignRequestBody response model.

    Attributes:
        budget: Выделенный бюджет на кампанию в рублях. **Обязательно только для типа кампании `AS`**
        budget_bonus: Бонусная часть бюджета, в рублях, которая спишется засчет бонусов. **Может быть только для типа кампании `AP`**
        budget_real: Часть бюджета на кампанию в рублях. **Обязательно только для типа кампании `AP`**
        calc_id: Идентфикатор расчета бюджета из ответа ручки `/autostrategy/v1/budget`
        campaign_type: Тип кампании. Возможные типы: `AS` - Автостратегия. Cтратегия расчитана на определенное количество автомобилей, которые находятся в продаже `AP` - Автопилот. Cтратегия расчитана на все автомобили, которые находятся в продаже
        description: Описание кампании
        finish_time: Время окончания кампании. **Обязательно только для типа кампании `AS`**
        items: Список индентификаторов объявлений, которые будут продвигаться с помощью данной кампании. **Обязательно только для типа кампании `AS`**
        start_time: Время начала кампании. **Обязательно только для типа кампании `AS`**
        title: Название кампании
    """

    budget: int | None = None
    budget_bonus: int | None = Field(None, alias="budgetBonus")
    budget_real: int | None = Field(None, alias="budgetReal")
    calc_id: int | None = Field(None, alias="calcId")
    campaign_type: CreateCampaignRequestBodyCampaignType = Field(..., alias="campaignType")
    description: str | None = None
    finish_time: TZDatetime | None = Field(None, alias="finishTime")
    items: list[int] | None = None
    start_time: TZDatetime | None = Field(None, alias="startTime")
    title: str


class EditCampaignBadRequestError(AvitoObject):
    """EditCampaignBadRequestError response model."""

    error: EditCampaignBadRequestErrorError | None = None


class EditCampaignBadRequestErrorError(AvitoObject):
    """EditCampaignBadRequestErrorError response model.

    Attributes:
        field_errors: Описание ошибок валидации полей
        message: Сообщение об ошибке
    """

    field_errors: EditCampaignBadRequestErrorErrorFieldErrors | None = Field(
        None, alias="fieldErrors"
    )
    message: str


class EditCampaignBadRequestErrorErrorFieldErrors(AvitoObject):
    """Описание ошибок валидации полей

    Attributes:
        budget: Ошибка валидации поля **budget**
        campaign_id: Ошибка валидации поля **campaignId**
        description: Ошибка валидации поля **description**
        finish_time: Ошибка валидации поля **finishTime**
        items: Ошибка валидации поля **items**
        start_time: Ошибка валидации поля **startTime**
        title: Ошибка валидации поля **title**
        version: Ошибка валидации поля **version**
    """

    budget: str | None = None
    campaign_id: str | None = Field(None, alias="campaignId")
    description: str | None = None
    finish_time: str | None = Field(None, alias="finishTime")
    items: str | None = None
    start_time: str | None = Field(None, alias="startTime")
    title: str | None = None
    version: str | None = None


class EditCampaignRequestBody(AvitoObject):
    """EditCampaignRequestBody response model.

    Attributes:
        budget: Новый бюджет кампании в рублях
        calc_id: Идентификатор расчета бюджета из ответа ручки `/autostrategy/v1/budget`
        campaign_id: Идентификатор активной кампании
        description: Новое описание кампании
        finish_time: Новое время окончания кампании
        items: Новый список индентификаторов объявлений, которые будут продвигаться с помощью данной кампании
        start_time: Новое время начала кампании
        title: Новое название кампании
        version: Текущая версия кампании
    """

    budget: int | None = None
    calc_id: int | None = Field(None, alias="calcId")
    campaign_id: int = Field(..., alias="campaignId")
    description: str | None = None
    finish_time: TZDatetime | None = Field(None, alias="finishTime")
    items: list[int] | None = None
    start_time: TZDatetime | None = Field(None, alias="startTime")
    title: str | None = None
    version: int


class GetBudgetBadRequestError(AvitoObject):
    """GetBudgetBadRequestError response model."""

    error: GetBudgetBadRequestErrorError | None = None


class GetBudgetBadRequestErrorError(AvitoObject):
    """GetBudgetBadRequestErrorError response model.

    Attributes:
        field_errors: Описание ошибок валидации полей
        message: Сообщение об ошибке
    """

    field_errors: GetBudgetBadRequestErrorErrorFieldErrors | None = Field(None, alias="fieldErrors")
    message: str


class GetBudgetBadRequestErrorErrorFieldErrors(AvitoObject):
    """Описание ошибок валидации полей

    Attributes:
        campaign_type: Ошибка валидации поля **campaignType**
        finish_time: Ошибка валидации поля **finishTime**
        items: Ошибка валидации поля **items**
        start_time: Ошибка валидации поля **startTime**
    """

    campaign_type: str | None = Field(None, alias="campaignType")
    finish_time: str | None = Field(None, alias="finishTime")
    items: str | None = None
    start_time: str | None = Field(None, alias="startTime")


class GetBudgetRequestBody(AvitoObject):
    """GetBudgetRequestBody response model.

    Attributes:
        campaign_type: Тип кампании. Возможные типы: `AS` - Автостратегия. Cтратегия расчитана на определенное количество автомобилей, которые находятся в продаже `AP` - Автопилот. Cтратегия расчитана на все автомобили, которые находятся в продаже
        finish_time: Время окончания кампании. **Обязательно только для типа кампании `AS`**
        items: Список индентификаторов объявлений, которые будут продвигаться с помощью данной кампании. **Обязательно только для типа кампании `AS`**
        start_time: Время начала кампании. **Обязательно только для типа кампании `AS`**
    """

    campaign_type: GetBudgetRequestBodyCampaignType = Field(..., alias="campaignType")
    finish_time: TZDatetime | None = Field(None, alias="finishTime")
    items: list[int] | None = None
    start_time: TZDatetime | None = Field(None, alias="startTime")


class GetCampaignInfoBadRequestError(AvitoObject):
    """GetCampaignInfoBadRequestError response model."""

    error: GetCampaignInfoBadRequestErrorError | None = None


class GetCampaignInfoBadRequestErrorError(AvitoObject):
    """GetCampaignInfoBadRequestErrorError response model.

    Attributes:
        field_errors: Описание ошибок валидации полей
        message: Сообщение об ошибке
    """

    field_errors: CampaignIdResponse | None = Field(None, alias="fieldErrors")
    message: str


class GetCampaignInfoForecastResult(AvitoObject):
    """Предсказание звонков и просмотров на завтра

    Attributes:
        calls: Предсказание звонков
        views: Предсказание просмотров
    """

    calls: GetCampaignInfoForecastResultCalls | None = None
    views: GetCampaignInfoForecastResultViews | None = None


class GetCampaignInfoForecastResultCalls(AvitoObject):
    """Предсказание звонков

    Attributes:
        from_: Нижняя граница предсказания
        lack_reason: Причина отсутствия прогноза, приходит при to = 0
        to: Верхняя граница предсказания
    """

    from_: int = Field(..., alias="from")
    lack_reason: GetCampaignInfoForecastResultCallsLackReason | None = Field(
        None, alias="lackReason"
    )
    to: int


class GetCampaignInfoForecastResultViews(AvitoObject):
    """Предсказание просмотров

    Attributes:
        from_: Нижняя граница предсказания
        lack_reason: Причина отсутствия прогноза, приходит при to = 0.
        to: Верхняя граница предсказания
    """

    from_: int = Field(..., alias="from")
    lack_reason: GetCampaignInfoForecastResultViewsLackReason | None = Field(
        None, alias="lackReason"
    )
    to: int


class GetCampaignInfoRequestBody(AvitoObject):
    """GetCampaignInfoRequestBody response model.

    Attributes:
        campaign_id: Идентификатор активной кампании
    """

    campaign_id: int = Field(..., alias="campaignId")


class GetCampaignsBadRequestError(AvitoObject):
    """GetCampaignsBadRequestError response model."""

    error: GetCampaignsBadRequestErrorError | None = None


class GetCampaignsBadRequestErrorError(AvitoObject):
    """GetCampaignsBadRequestErrorError response model.

    Attributes:
        field_errors: Описание ошибок валидации полей
        message: Сообщение об ошибке
    """

    field_errors: GetCampaignsBadRequestErrorErrorFieldErrors | None = Field(
        None, alias="fieldErrors"
    )
    message: str


class GetCampaignsBadRequestErrorErrorFieldErrors(AvitoObject):
    """Описание ошибок валидации полей

    Attributes:
        limit: Ошибка валидации поля **limit**
        offset: Ошибка валидации поля **offset**
        order_by: Ошибка валидации поля **orderBy**
        status_id: Ошибка валидации поля **statusId**
    """

    limit: str | None = None
    offset: str | None = None
    order_by: GetCampaignsBadRequestErrorErrorFieldErrorsOrderBy | None = Field(
        None, alias="orderBy"
    )
    status_id: str | None = Field(None, alias="statusId")


class GetCampaignsBadRequestErrorErrorFieldErrorsOrderBy(AvitoObject):
    """Ошибка валидации поля **orderBy**

    Attributes:
        column: Ошибка валидации поля **column**
        direction: Ошибка валидации поля **direction**
    """

    column: str | None = None
    direction: str | None = None


class GetCampaignsRequestBody(AvitoObject):
    """GetCampaignsRequestBody response model.

    Attributes:
        filter: Фильтр
        limit: Ограничение на выборку
        offset: Смещение выборки, по умолчанию равно 0
        order_by: Поля, по которым будет произведена сортировка, и тип сортировки
        status_id: Статусы кампании для выборки. Возможные статусы: `0` - Черновик, дата старта сегодня или раньше, денег на балансе нет `1` - Активная кампания `2` - Кампания приостановлена `3` - Кампания удалена `4` - Кампания остановлена `5` - Кампания запланирована, дата старта завтра или позже, на балансе есть деньги По умолчанию в выборку попадают кампании со статусами 0, 1, 2, 4, 5.
    """

    filter: GetCampaignsRequestBodyFilter | None = None
    limit: int
    offset: int | None = None
    order_by: list[GetCampaignsRequestBodyOrderBy] | None = Field(None, alias="orderBy")
    status_id: list[int] | None = Field(None, alias="statusId")


class GetCampaignsRequestBodyFilter(AvitoObject):
    """Фильтр

    Attributes:
        by_update_time: Фильтрация кампаний по дате обновления
    """

    by_update_time: GetCampaignsRequestBodyFilterByUpdateTime | None = Field(
        None, alias="byUpdateTime"
    )


class GetCampaignsRequestBodyFilterByUpdateTime(AvitoObject):
    """Фильтрация кампаний по дате обновления

    Attributes:
        from_: Начало периода включительно
        to: Конец периода, не включая
    """

    from_: TZDatetime | None = Field(None, alias="from")
    to: TZDatetime | None = None


class GetCampaignsRequestBodyOrderBy(AvitoObject):
    """GetCampaignsRequestBodyOrderBy response model.

    Attributes:
        column: Поле, по которому будет произведена сортировка. Возможные поля: `campaignId` - идентификатор кампании `userId` - идентификатор владельца кампании `budget` - бюджет кампании `balance` - баланс кампании(остаток от общего бюджета) `title` - название `statusId` - статус кампании `startTime` - время старта `finishTime` - время финиша `createTime` - время создания `updateTime` - время обновления `itemsCount` - количество объявлений в кампании `isPaid` - оплачена ли кампания
        direction: Тип сортировки
    """

    column: GetCampaignsRequestBodyOrderByColumn | None = None
    direction: GetCampaignsRequestBodyOrderByDirection | None = None


class GetStatRequestBody(AvitoObject):
    """GetStatRequestBody response model.

    Attributes:
        campaign_id: Идентификатор запущенной или уже прошедшей кампании
    """

    campaign_id: int = Field(..., alias="campaignId")


class GetStatRequestError(AvitoObject):
    """GetStatRequestError response model."""

    error: GetStatRequestErrorError | None = None


class GetStatRequestErrorError(AvitoObject):
    """GetStatRequestErrorError response model.

    Attributes:
        code: Код ошибки
        field_errors: Описание ошибок валидации полей
        message: Сообщение об ошибке
    """

    code: int | None = None
    field_errors: CampaignIdResponse | None = Field(None, alias="fieldErrors")
    message: str


class StatRoot(AvitoObject):
    """StatRoot response model.

    Attributes:
        calls: Факт по звонкам
        calls_forecast: Предсказание звонков
        date_: Дата в формате `YYYY-MM-DD`
        views: Факт по просмотрам
    """

    calls: int
    calls_forecast: StatRootCallsForecast | None = Field(None, alias="callsForecast")
    date_: date = Field(..., alias="date")
    views: int
    views_forecast: StatRootViewsForecast | None = Field(None, alias="viewsForecast")


class StatRootCallsForecast(AvitoObject):
    """Предсказание звонков

    Attributes:
        from_: Нижняя граница предсказания
        to: Верхняя граница предсказания
    """

    from_: int = Field(..., alias="from")
    to: int


class StatRootViewsForecast(AvitoObject):
    """StatRootViewsForecast response model.

    Attributes:
        from_: Нижняя граница предсказания
        to: Верхняя граница предсказания
    """

    from_: int = Field(..., alias="from")
    to: int


class StopCampaignBadRequestError(AvitoObject):
    """StopCampaignBadRequestError response model."""

    error: StopCampaignBadRequestErrorError | None = None


class StopCampaignBadRequestErrorError(AvitoObject):
    """StopCampaignBadRequestErrorError response model.

    Attributes:
        field_errors: Описание ошибок валидации полей
        message: Сообщение об ошибке
    """

    field_errors: StopCampaignBadRequestErrorErrorFieldErrors | None = Field(
        None, alias="fieldErrors"
    )
    message: str


class StopCampaignBadRequestErrorErrorFieldErrors(AvitoObject):
    """Описание ошибок валидации полей

    Attributes:
        campaign_id: Ошибка валидации поля **campaignId**
        version: Ошибка валидации поля **version**
    """

    campaign_id: str | None = Field(None, alias="campaignId")
    version: str | None = None


class StopCampaignRequestBody(AvitoObject):
    """StopCampaignRequestBody response model.

    Attributes:
        campaign_id: Идентификатор активной кампании
        version: Текущая версия кампании
    """

    campaign_id: int = Field(..., alias="campaignId")
    version: int


class AutostrategyAuthError(AvitoObject):
    """AutostrategyAuthError response model."""

    error: MessageResponse | None = None


class AutostrategyServiceError(AvitoObject):
    """AutostrategyServiceError response model."""

    error: MessageResponse | None = None


class GetAutostrategyBudgetResponse(AvitoObject):
    """GetAutostrategyBudgetResponse response model.

    Attributes:
        calc_id: Id расчета бюджета
    """

    budget: Budget | None = None
    calc_id: int | None = Field(None, alias="calcId")


class CreateAutostrategyCampaignResponse(AvitoObject):
    """CreateAutostrategyCampaignResponse response model."""

    campaign: Campaign | None = None


class EditAutostrategyCampaignResponse(AvitoObject):
    """EditAutostrategyCampaignResponse response model."""

    campaign: Campaign | None = None


class GetAutostrategyCampaignInfoResponse(AvitoObject):
    """GetAutostrategyCampaignInfoResponse response model.

    Attributes:
        items: Список индентификаторов объявлений, которые продвигаются/продвигались в данной кампании
    """

    campaign: Campaign | None = None
    forecast: GetCampaignInfoForecastResult | None = None
    items: list[GetAutostrategyCampaignInfoResponseItems] | None = None


class GetAutostrategyCampaignInfoResponseItems(AvitoObject):
    """GetAutostrategyCampaignInfoResponseItems response model.

    Attributes:
        is_active: Продвигается ли объявление в кампании на данный момент
        item_id: ID объявления
    """

    is_active: bool | None = Field(None, alias="isActive")
    item_id: int | None = Field(None, alias="itemId")


class StopAutostrategyCampaignResponse(AvitoObject):
    """StopAutostrategyCampaignResponse response model."""

    campaign: Campaign | None = None


class GetAutostrategyCampaignsFilter(AvitoObject):
    """Фильтр

    Attributes:
        by_update_time: Фильтрация кампаний по дате обновления
    """

    by_update_time: GetAutostrategyCampaignsFilterByUpdateTime | None = Field(
        None, alias="byUpdateTime"
    )


class GetAutostrategyCampaignsFilterByUpdateTime(AvitoObject):
    """Фильтрация кампаний по дате обновления

    Attributes:
        from_: Начало периода включительно
        to: Конец периода, не включая
    """

    from_: TZDatetime | None = Field(None, alias="from")
    to: TZDatetime | None = None


class GetAutostrategyCampaignsOrderBy(AvitoObject):
    """GetAutostrategyCampaignsOrderBy response model.

    Attributes:
        column: Поле, по которому будет произведена сортировка. Возможные поля: `campaignId` - идентификатор кампании `userId` - идентификатор владельца кампании `budget` - бюджет кампании `balance` - баланс кампании(остаток от общего бюджета) `title` - название `statusId` - статус кампании `startTime` - время старта `finishTime` - время финиша `createTime` - время создания `updateTime` - время обновления `itemsCount` - количество объявлений в кампании `isPaid` - оплачена ли кампания
        direction: Тип сортировки
    """

    column: GetAutostrategyCampaignsOrderByColumn | None = None
    direction: GetAutostrategyCampaignsOrderByDirection | None = None


class GetAutostrategyStatResponse(AvitoObject):
    """GetAutostrategyStatResponse response model.

    Attributes:
        totals: Статистика, просумированная за все дни
    """

    stat: list[StatValue] | None = None
    totals: GetAutostrategyStatResponseTotals | None = None


class StatValue(AvitoObject):
    """StatValue response model.

    Attributes:
        calls: Факт по звонкам
        calls_forecast: Предсказание звонков
        date_: Дата в формате `YYYY-MM-DD`
        views: Факт по просмотрам
    """

    calls: int
    calls_forecast: StatValueCallsForecast | None = Field(None, alias="callsForecast")
    date_: date = Field(..., alias="date")
    views: int
    views_forecast: StatValueViewsForecast | None = Field(None, alias="viewsForecast")


class StatValueCallsForecast(AvitoObject):
    """Предсказание звонков

    Attributes:
        from_: Нижняя граница предсказания
        to: Верхняя граница предсказания
    """

    from_: int = Field(..., alias="from")
    to: int


class StatValueViewsForecast(AvitoObject):
    """StatValueViewsForecast response model.

    Attributes:
        from_: Нижняя граница предсказания
        to: Верхняя граница предсказания
    """

    from_: int = Field(..., alias="from")
    to: int


class GetAutostrategyStatResponseTotals(AvitoObject):
    """Статистика, просумированная за все дни

    Attributes:
        calls: Факт по звонкам
        views: Факт по просмотрам
    """

    calls: int
    views: int


class Stat(RootModel[list[StatRoot]]):
    """Root wrapper for a top-level ``list[StatRoot]`` response."""
