# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""CallTracking[КТ] — domain models (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from pydantic import Field

from ._base import AvitoObject


class Call(AvitoObject):
    """модель звонка

    See: https://developers.avito.ru/api-catalog/calltracking/documentation

    Attributes:
        buyer_phone: Номер телефона покупателя
        call_id: ID звонка
        call_time: Время, когда звонок был совершен
        item_id: ID объявления, по которому совершался звонок. Проставляется только если звонок был на номера Динамического КТ.
        seller_phone: Номер телефона продавца
        talk_duration: Длительность разговора
        virtual_phone: Защитный номер, через который шел звонок
        waiting_duration: Длительность ожидания
    """

    buyer_phone: str = Field(..., alias="buyerPhone")
    call_id: int = Field(..., alias="callId")
    call_time: str = Field(..., alias="callTime")
    item_id: int | None = Field(None, alias="itemId")
    seller_phone: str = Field(..., alias="sellerPhone")
    talk_duration: int = Field(..., alias="talkDuration")
    virtual_phone: str = Field(..., alias="virtualPhone")
    waiting_duration: float = Field(..., alias="waitingDuration")


class Error(AvitoObject):
    """Error response model.

    See: https://developers.avito.ru/api-catalog/calltracking/documentation

    Attributes:
        code: Внутренний код ошибки Возможные значения: 0 - нет ошибки 1000 - пустой запрос 1001 - ошибка валидации 1002 - ошибка авторизации 1003 - внутренняя ошибка 1004 - не найдено
    """

    code: int
    message: str


class GetCallByIdResponse(AvitoObject):
    """GetCallByIdResponse response model.

    See: https://developers.avito.ru/api-catalog/calltracking/documentation
    """

    call: Call
    error: Error


class GetCallRecordError(AvitoObject):
    """GetCallRecordError response model.

    See: https://developers.avito.ru/api-catalog/calltracking/documentation

    Attributes:
        code: Внутренний код ошибки Возможные значения: 0 - нет ошибки 1000 - пустой запрос 1001 - ошибка валидации 1002 - ошибка авторизации 1003 - внутренняя ошибка 1004 - не найдено 1005 - запись звонка еще не готова на стороне оператора
    """

    code: int
    message: str


class GetCallsResponse(AvitoObject):
    """GetCallsResponse response model.

    See: https://developers.avito.ru/api-catalog/calltracking/documentation
    """

    calls: list[Call]
    error: Error
