# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""CPA Авито — domain models (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ._base import AvitoObject


class Call(AvitoObject):
    """Call response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        buyer_phone: Телефонный номер покупателя
        create_time: Время поступления звонка (строка в формате RFC3339)
        duration: Время разговора
        id: Идентификатор звонка
        is_arbitrage_available: Флаг, указывающий на то, доступен ли арбитраж по звонку
        item_id: Идентификатор объявления
        price: Цена звонка CPA в рублях
        record_url: Ссылка на запись звонка
        seller_phone: Реальный телефонный номер продавца
        start_time: Время начала разговора (строка в формате RFC3339)
        status_id: Статус звонка (0 - целевой, 1 - на модерации, 2 - помечен как целевой после модерации, 3 - помечен как нецелевой после модерации)
        virtual_phone: Виртуальный телефонный номер продавца
        waiting_duration: Время ожидания
    """

    buyer_phone: str | None = Field(None, alias="buyerPhone")
    create_time: str | None = Field(None, alias="createTime")
    duration: int | None = None
    id: int | None = None
    is_arbitrage_available: bool | None = Field(None, alias="isArbitrageAvailable")
    item_id: int | None = Field(None, alias="itemId")
    price: int | None = None
    record_url: str | None = Field(None, alias="recordUrl")
    seller_phone: str | None = Field(None, alias="sellerPhone")
    start_time: str | None = Field(None, alias="startTime")
    status_id: int | None = Field(None, alias="statusId")
    virtual_phone: str | None = Field(None, alias="virtualPhone")
    waiting_duration: float | None = Field(None, alias="waitingDuration")


class CallById(AvitoObject):
    """CallById response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        call_id: Идентификатор звонка
    """

    call_id: int = Field(..., alias="callId")


class CallV2(AvitoObject):
    """CallV2 response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        buyer_phone: Телефонный номер покупателя
        create_time: Время поступления звонка (строка в формате RFC3339)
        duration: Время разговора в секундах
        group_title: Название группы
        id: Идентификатор звонка
        is_arbitrage_available: Флаг, указывающий на то, доступен ли арбитраж по звонку
        item_id: Идентификатор объявления
        price: Цена звонка CPA в копейках
        record_url: Ссылка на запись звонка
        seller_phone: Реальный телефонный номер продавца
        start_time: Время начала разговора (строка в формате RFC3339)
        status_id: Статус звонка (0 - целевой, 1 - на модерации, 2 - помечен как целевой после модерации, 3 - помечен как нецелевой после модерации)
        virtual_phone: Виртуальный телефонный номер продавца
        waiting_duration: Время ожидания в секундах
    """

    buyer_phone: str | None = Field(None, alias="buyerPhone")
    create_time: str | None = Field(None, alias="createTime")
    duration: int | None = None
    group_title: str | None = Field(None, alias="groupTitle")
    id: int | None = None
    is_arbitrage_available: bool | None = Field(None, alias="isArbitrageAvailable")
    item_id: int | None = Field(None, alias="itemId")
    price: int | None = None
    record_url: str | None = Field(None, alias="recordUrl")
    seller_phone: str | None = Field(None, alias="sellerPhone")
    start_time: str | None = Field(None, alias="startTime")
    status_id: int | None = Field(None, alias="statusId")
    virtual_phone: str | None = Field(None, alias="virtualPhone")
    waiting_duration: float | None = Field(None, alias="waitingDuration")


class CallsByTime(AvitoObject):
    """CallsByTime response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        date_time_from: Время с которого нужно начинать поиск звонков по startTime (строка в формате RFC3339)
        limit: Размер выборки
        offset: Смещение выборки (по-умолчанию 0). Для улучшения производительности лучше использовать максимальный startTime звонка из предыдущей выборки
    """

    date_time_from: str = Field(..., alias="dateTimeFrom")
    limit: int
    offset: int | None = None


class CpaError(AvitoObject):
    """CpaError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Внутренний код ошибки Возможные значения: - 1000 - пустой запрос - 1001 - ошибка валидации - 1002 - ошибка авторизации - 1003 - внутренняя ошибка - 1004 - не найдено
        message: Текст ошибки
    """

    code: int | None = None
    message: str | None = None


class CpaErrorChat(AvitoObject):
    """CpaErrorChat response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    result: CpaErrorChatResult | None = None


class CpaErrorChatResult(AvitoObject):
    """CpaErrorChatResult response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        message: Текст ошибки
    """

    message: str | None = None
    status: bool | None = None


class CreateComplaint(AvitoObject):
    """CreateComplaint response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        call_id: Идентификатор звонка
        message: Текст жалобы
    """

    call_id: int = Field(..., alias="callId")
    message: str


class CreateComplaintV4In(AvitoObject):
    """CreateComplaintV4In response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        action_id: ID действия (action), по которому подаётся жалоба
        message: Сообщение, прикрепленное к жалобе
    """

    action_id: int = Field(..., alias="actionId")
    message: str


class CreateComplaintV4Out(AvitoObject):
    """CreateComplaintV4Out response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        success: Успех/неуспех создания жалобы
    """

    success: bool | None = None


class Error(AvitoObject):
    """Error response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Internal error code
        message: Human readable error text
    """

    code: int
    message: str
    payload: ErrorPayload | None = None


class ErrorPayload(AvitoObject):
    """ErrorPayload response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        balance: Баланс пользователя
    """

    balance: int | None = None


class InternalError(AvitoObject):
    """InternalError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    result: InternalErrorResult


class InternalErrorResult(AvitoObject):
    """InternalErrorResult response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    error: InternalErrorResultError


class InternalErrorResultError(AvitoObject):
    """InternalErrorResultError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Код ошибки
        message: Текст ошибки
    """

    code: int
    message: str


class OpenApiChatsByTimeFilters(AvitoObject):
    """OpenApiChatsByTimeFilters response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    date_from: str = Field(..., alias="dateFrom")
    date_to: str = Field(..., alias="dateTo")


class OpenApiChatsByTimeIn(AvitoObject):
    """OpenApiChatsByTimeIn response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        date_time_from: Время с которого нужно начинать поиск чатов по date (строка в формате RFC3339)
        limit: Размер выборки (значение в поле должно быть не более 100)
        offset: Смещение выборки (по-умолчанию 0). Для улучшения производительности лучше использовать максимальный startTime чата из предыдущей выборки
    """

    date_time_from: str = Field(..., alias="dateTimeFrom")
    limit: int
    offset: int


class OpenApiChatsByTimeMetaFilters(AvitoObject):
    """OpenApiChatsByTimeMetaFilters response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    active: OpenApiChatsByTimeFilters


class OpenApiChatsByTimeOut(AvitoObject):
    """OpenApiChatsByTimeOut response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        chats: Данные с чатами
        total: Количество чатов
    """

    chats: list[OpenApiChatsComposition]
    filters: OpenApiChatsByTimeMetaFilters
    total: int


class OpenApiChatsByTimeV2In(AvitoObject):
    """OpenApiChatsByTimeV2In response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        date_time_from: Время с которого нужно начинать поиск чатов по date (строка в формате RFC3339)
        limit: Размер выборки (значение в поле должно быть не более 100)
        offset: Смещение выборки (по-умолчанию 0). Для улучшения производительности лучше использовать максимальный date чата из предыдущей выборки
    """

    date_time_from: str = Field(..., alias="dateTimeFrom")
    limit: int
    offset: int


class OpenApiChatsByTimeV2Out(AvitoObject):
    """OpenApiChatsByTimeV2Out response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        chats: Данные с чатами
        total: Количество чатов
    """

    chats: list[OpenApiChatsComposition]
    filters: OpenApiChatsByTimeMetaFilters
    total: int


class OpenApiPhonesInfoFromChatsIn(AvitoObject):
    """OpenApiPhonesInfoFromChatsIn response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        date_time_from: Время с которого начинается поиск
    """

    date_time_from: str = Field(..., alias="dateTimeFrom")
    limit: int
    offset: int


class OpenApiPhonesInfoFromChatsOut(AvitoObject):
    """OpenApiPhonesInfoFromChatsOut response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        date_: Время отправки сообщения
        group: Прайсинговая группа объявления
        id: ID ЦД
        phone_number: Номер телефона из сообщения
        price_penny: Цена ЦД в копейках
        url: URL до картинки с превью
    """

    date_: str = Field(..., alias="date")
    group: str
    id: int
    phone_number: str | None = None
    price_penny: int = Field(..., alias="pricePenny")
    url: str


class OpenApiChat(AvitoObject):
    """OpenApiChat response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        action_id: ID ЦД
        channel_id: ID канала чата
        contact_type: Тип контакта (email/phone/nick/other)
        date_: Время отправки сообщения
        group: Прайсинговая группа объявления
        message: Текст сообщения
        message_id: ID сообщения
        price_penny: Цена ЦД в копейках
        status: Статус ЦД
        target_chat_type: Тип целевого чата (Контакты/Cделка/Переключения)
    """

    action_id: int = Field(..., alias="actionId")
    channel_id: str = Field(..., alias="channelId")
    contact_type: str = Field(..., alias="contactType")
    date_: str = Field(..., alias="date")
    group: str
    message: str
    message_id: str = Field(..., alias="messageId")
    price_penny: int = Field(..., alias="pricePenny")
    status: str
    target_chat_type: str = Field(..., alias="targetChatType")


class OpenApiChatByActionIdIn(AvitoObject):
    """OpenApiChatByActionIdIn response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        user_id: User ID
    """

    action_id: int = Field(..., alias="actionId")
    user_id: int | None = Field(None, alias="userId")


class OpenApiChatByActionIdOut(AvitoObject):
    """OpenApiChatByActionIdOut response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    chat: OpenApiChatsComposition | None = None
    error: Error | None = None


class OpenApiChatsBuyer(AvitoObject):
    """OpenApiChatsBuyer response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        buyer_id: ID баера
        name: Имя баера
        url: URL до картинки с превью
    """

    buyer_id: int = Field(..., alias="buyerId")
    name: str
    url: str


class OpenApiChatsComposition(AvitoObject):
    """OpenApiChatsComposition response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        is_arbitrage_available: Доступность опротестования ЦД
    """

    buyer: OpenApiChatsBuyer
    chat: OpenApiChat
    is_arbitrage_available: bool = Field(..., alias="isArbitrageAvailable")
    item: OpenApiChatsItem


class OpenApiChatsItem(AvitoObject):
    """OpenApiChatsItem response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        item_id: ID объявления
        price_penny: Цена объявления в копейках
        title: Название объявления
        url: URL до картинки с превью
    """

    item_id: int = Field(..., alias="itemId")
    price_penny: int = Field(..., alias="pricePenny")
    title: str
    url: str


class OpenApiError(AvitoObject):
    """OpenApiError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    result: OpenApiErrorResult


class OpenApiErrorResult(AvitoObject):
    """OpenApiErrorResult response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    error: OpenApiErrorResultError


class OpenApiErrorResultError(AvitoObject):
    """OpenApiErrorResultError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Код ошибки
        message: Текст ошибки
    """

    code: int
    message: str
    payload: OpenApiErrorResultErrorPayload | None = None


class OpenApiErrorResultErrorPayload(AvitoObject):
    """OpenApiErrorResultErrorPayload response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    error: str | None = None


class OpenApiErrorOld(AvitoObject):
    """OpenApiErrorOld response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    result: OpenApiErrorOldResult | None = None


class OpenApiErrorOldResult(AvitoObject):
    """OpenApiErrorOldResult response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Код ошибки
        message: Текст ошибки
    """

    code: int | None = None
    message: str | None = None
    payload: dict[str, Any] | None = None


class NotFoundError(AvitoObject):
    """NotFoundError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    error: NotFoundErrorError | None = None


class NotFoundErrorError(AvitoObject):
    """NotFoundErrorError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Код ошибки
        message: Сообщение об ошибке
    """

    code: int
    message: str


class ServiceError(AvitoObject):
    """ServiceError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    error: ServiceErrorError | None = None


class ServiceErrorError(AvitoObject):
    """ServiceErrorError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Код ошибки
        message: Описание ошибки
    """

    code: int
    message: str


class TooManyRequestsError(AvitoObject):
    """TooManyRequestsError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    error: TooManyRequestsErrorError | None = None


class TooManyRequestsErrorError(AvitoObject):
    """TooManyRequestsErrorError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Код ошибки
    """

    code: int


class ValidatingError(AvitoObject):
    """ValidatingError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    error: ValidatingErrorError | None = None


class ValidatingErrorError(AvitoObject):
    """ValidatingErrorError response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        code: Код ошибки
        fields: Информация об ошибке валидации параметров в формате ключ-значение
        message: Сообщение об ошибке
    """

    code: int
    fields: dict[str, Any] | None = None
    message: str


class ChatByActionIdResponse(AvitoObject):
    """ChatByActionIdResponse response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    chat: OpenApiChatsComposition | None = None


class ChatsByTimeResponse(AvitoObject):
    """ChatsByTimeResponse response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    chats: list[OpenApiChatsComposition] | None = None


class PostCreateComplaintResponse(AvitoObject):
    """PostCreateComplaintResponse response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        success: Флаг статуса запроса
    """

    error: CpaError | None = None
    success: bool | None = None


class CreateComplaintByActionIdResponse(AvitoObject):
    """CreateComplaintByActionIdResponse response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        success: Флаг статуса запроса
    """

    error: CpaError | None = None
    success: bool | None = None


class PhonesInfoFromChatsResponse(AvitoObject):
    """PhonesInfoFromChatsResponse response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        total: Число найденных чатов
    """

    results: list[OpenApiPhonesInfoFromChatsOut]
    total: int


class BalanceInfoV2Response(AvitoObject):
    """BalanceInfoV2Response response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        advance: Аванс, выставленный на текущий период в копейках
        balance: Текущий баланс пользователя в копейках
        debt: Долг пользователя за предыдущий период в копейках
    """

    advance: int | None = None
    balance: int | None = None
    debt: int | None = None
    error: CpaError | None = None


class GetCallByIdV2Response(AvitoObject):
    """GetCallByIdV2Response response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    calls: CallV2 | None = None
    error: CpaError | None = None


class GetCallsByTimeV2Response(AvitoObject):
    """GetCallsByTimeV2Response response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        calls: Полученные звонки
    """

    calls: list[CallV2] | None = None
    error: CpaError | None = None


class ChatsByTime2Response(AvitoObject):
    """ChatsByTime2Response response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation
    """

    chats: list[OpenApiChatsComposition] | None = None


class BalanceInfoV3Response(AvitoObject):
    """BalanceInfoV3Response response model.

    See: https://developers.avito.ru/api-catalog/cpa/documentation

    Attributes:
        balance: Текущий баланс пользователя в копейках
    """

    balance: int | None = None
