# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Настройка цены целевого действия — domain models (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from pydantic import Field

from ._base import AvitoObject
from ._shared import TooManyRequestsErrorError


class AutoBid(AvitoObject):
    """AutoBid response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        action_type_id: Тип события (1 - звонок | 5 - пакет кликов | 7 - мессенджер, передача контакта в чате)
        budget_penny: Текущий бюджет в копейках
        budget_type: Тип бюджета (\"1d\" - дневной | \"7d\" - недельный | \"30d\" - месячный)
        item_id: Идентификатор объявления
    """

    action_type_id: int = Field(..., alias="actionTypeID")
    budget_penny: int = Field(..., alias="budgetPenny")
    budget_type: str = Field(..., alias="budgetType")
    item_id: int = Field(..., alias="itemID")


class ManualBid(AvitoObject):
    """ManualBid response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        action_type_id: Тип события (1 - звонок | 5 - пакет кликов | 7 - мессенджер, передача контакта в чате)
        bid_penny: Текущая цена за целевое действие в копейках
        item_id: Идентификатор объявления
        limit_penny: Дневной лимит в копейках
    """

    action_type_id: int = Field(..., alias="actionTypeID")
    bid_penny: int = Field(..., alias="bidPenny")
    item_id: int = Field(..., alias="itemID")
    limit_penny: int | None = Field(None, alias="limitPenny")


class RemovePromotion(AvitoObject):
    """RemovePromotion response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        item_id: Идентификатор объявления
    """

    item_id: int = Field(..., alias="itemID")


class Auto(AvitoObject):
    """Auto response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        budget_penny: Текущий бюджет (в копейках)
        budget_type: Тип бюджета (\"1d\" - дневной | \"7d\" - недельный | \"30d\" - месячный)
        max_budget_penny: Максимальный бюджет (в копейках)
        min_budget_penny: Минимальный бюджет (в копейках)
    """

    budget_penny: int | None = Field(None, alias="budgetPenny")
    budget_type: str | None = Field(None, alias="budgetType")
    daily_budget: Budget = Field(..., alias="dailyBudget")
    max_budget_penny: int = Field(..., alias="maxBudgetPenny")
    min_budget_penny: int = Field(..., alias="minBudgetPenny")
    monthly_budget: Budget = Field(..., alias="monthlyBudget")
    weekly_budget: Budget = Field(..., alias="weeklyBudget")


class AutoPromotion(AvitoObject):
    """AutoPromotion response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        budget_penny: Текущий бюджет в копейках
        budget_type: Тип бюджета (\"1d\" - дневной | \"7d\" - недельный | \"30d\" - месячный)
    """

    budget_penny: int = Field(..., alias="budgetPenny")
    budget_type: str = Field(..., alias="budgetType")


class Bid(AvitoObject):
    """Bid response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        compare: Количество процентных пунктов. (На сколько выше в сравнении с конкурентами)
        max_forecast: Максимальное кол-во ЦД за цену ЦД
        min_forecast: Минимальное кол-во ЦД за цену ЦД
        value_penny: Цена за целевое действие (в копейках)
    """

    compare: int
    max_forecast: int = Field(..., alias="maxForecast")
    min_forecast: int = Field(..., alias="minForecast")
    value_penny: int = Field(..., alias="valuePenny")


class Budget(AvitoObject):
    """Budget response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        max_limit_penny: Максимальный лимит (в копейках)
        min_limit_penny: Минимальный лимит (в копейках)
        rec_budget_penny: Рекомендованный лимит (в копейках)
    """

    budgets: list[BudgetValue] = Field(..., min_length=1, max_length=200)
    max_limit_penny: int = Field(..., alias="maxLimitPenny")
    min_limit_penny: int = Field(..., alias="minLimitPenny")
    rec_budget_penny: int = Field(..., alias="recBudgetPenny")


class BudgetValue(AvitoObject):
    """BudgetValue response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        compare: Количество процентных пунктов. (На сколько выше в сравнении с конкурентами)
        max_forecast: Максимальное кол-во ЦД за цену ЦД
        min_forecast: Минимальное кол-во ЦД за цену ЦД
        value_penny: Бюджет (в копейках)
    """

    compare: int
    max_forecast: int = Field(..., alias="maxForecast")
    min_forecast: int = Field(..., alias="minForecast")
    value_penny: int = Field(..., alias="valuePenny")


class Error(AvitoObject):
    """Error response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        message: Текст ошибки
    """

    message: str


class GetBidsOut(AvitoObject):
    """GetBidsOut response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        action_type_id: Тип события (1 - звонок | 5 - пакет кликов | 7 - мессенджер, передача контакта в чате)
        selected_type: Выбранный тип продвижения (\"manual\" - ручное продвижение | \"auto\" - автоматическое продвижение)
    """

    action_type_id: int = Field(..., alias="actionTypeID")
    auto: Auto | None = None
    manual: Manual | None = None
    selected_type: str = Field(..., alias="selectedType")


class GetPromotionsByItemIdsIn(AvitoObject):
    """GetPromotionsByItemIdsIn response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation
    """

    item_ids: list[int] = Field(..., min_length=1, max_length=200, alias="itemIDs")


class GetPromotionsByItemIdsOut(AvitoObject):
    """GetPromotionsByItemIdsOut response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation
    """

    items: list[GetPromotionsByItemIdsOutItems] = Field(..., min_length=1, max_length=200)


class GetPromotionsByItemIdsOutItems(AvitoObject):
    """GetPromotionsByItemIdsOutItems response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        action_type_id: Тип события (1 - звонок | 5 - пакет кликов | 7 - мессенджер, передача контакта в чате)
        item_id: Идентификатор объявления
    """

    action_type_id: int = Field(..., alias="actionTypeID")
    auto_promotion: AutoPromotion | None = Field(None, alias="autoPromotion")
    item_id: int = Field(..., alias="itemID")
    manual_promotion: ManualPromotion | None = Field(None, alias="manualPromotion")


class Manual(AvitoObject):
    """Manual response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        bid_penny: Текущая цена за целевое действие (в копейках)
        limit_penny: Дневной лимит (в копейках)
        max_bid_penny: Максимальная цена за целевое действие (в копейках)
        max_limit_penny: Максимальный дневной лимит (в копейках)
        min_bid_penny: Минимальная цена за целевое действие (в копейках)
        min_limit_penny: Минимальный дневной лимит (в копейках)
        rec_bid_penny: Рекомендуемая цена за целевое действие (в копейках)
    """

    bid_penny: int | None = Field(None, alias="bidPenny")
    bids: list[Bid] = Field(..., min_length=1, max_length=200)
    limit_penny: int | None = Field(None, alias="limitPenny")
    max_bid_penny: int = Field(..., alias="maxBidPenny")
    max_limit_penny: int = Field(..., alias="maxLimitPenny")
    min_bid_penny: int = Field(..., alias="minBidPenny")
    min_limit_penny: int = Field(..., alias="minLimitPenny")
    rec_bid_penny: int = Field(..., alias="recBidPenny")


class ManualPromotion(AvitoObject):
    """ManualPromotion response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        bid_penny: Текущая цена за целевое действие в копейках
        limit_penny: Дневной лимит в копейках
    """

    bid_penny: int = Field(..., alias="bidPenny")
    limit_penny: int | None = Field(None, alias="limitPenny")


class TooManyRequestsError(AvitoObject):
    """TooManyRequestsError response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation
    """

    error: TooManyRequestsErrorError | None = None


class RemovePromotion2Response(AvitoObject):
    """RemovePromotion2Response response model.

    See: https://developers.avito.ru/api-catalog/cpxpromo/documentation

    Attributes:
        message: Текст сообщения
    """

    message: str
