# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Объявления — domain models (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING, Any

from pydantic import Field, RootModel

from ..enums.items import (
    AnalyticsRequestSortOrder,
    Groupings,
    InfoVasVasId,
    ItemAnalyticsSortOrder,
    ItemInfoAvitoStatus,
    ItemsInfoWithCategoryAvitoResourcesStatus,
    PackageIdRequestBodyV2PackageId,
    PutItemVasPackageV2PackageId,
    PutItemVasVasId,
    SpendingsGroupings,
    StatisticsFieldsRoot,
    StatisticsFieldsValue,
    StatisticsPeriodGrouping,
    VasIdRequestBodyVasId,
)
from ._base import AvitoObject
from ._helpers import _resolve_user_id
from .common import AvitoErrorBody, TZDatetime

if TYPE_CHECKING:
    from ..methods.items import ApplyVas, GetItemInfo, PutItemVas, PutItemVasPackageV2, UpdatePrice


class AnalyticsRequest(AvitoObject):
    """AnalyticsRequest response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        date_from: Дата (в формате YYYY-MM-DD), с которой (включительно) надо получить статистику
        date_to: Дата (в формате YYYY-MM-DD), по которую (включительно) надо получить статистику
        filter: Набор ограничений, по которым нужно отфильтровать данные
        limit: Инструмент пагинации для ограничения количества сущностей в response;
        metrics: Набор доступных показателей, которые должны присутствовать в ответе
        offset: инструмент пагинации или смещение, с которого начинается выборка данных;
        sort: Сортировка по заданному показателю
    """

    date_from: date = Field(..., alias="dateFrom")
    date_to: date = Field(..., alias="dateTo")
    filter: AnalyticsRequestFilter | None = None
    grouping: Groupings
    limit: int = Field(..., ge=0, le=1000)
    metrics: list[str]
    offset: int = Field(..., ge=0)
    sort: AnalyticsRequestSort | None = None


class AnalyticsRequestFilter(AvitoObject):
    """Набор ограничений, по которым нужно отфильтровать данные

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        category_ids: Идентификаторы категорий [ Справочник идентификаторов категорий ](https://www.avito.st/s/openapi/catalog-categories.xml)
        employee_ids: Идентификаторы сотрудников [ Метод получения идентификаторов сотрудников ](https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation#operation/getEmployeesV1)
    """

    category_ids: list[int] | None = Field(None, alias="categoryIDs")
    employee_ids: list[int] | None = Field(None, alias="employeeIDs")


class AnalyticsRequestSort(AvitoObject):
    """Сортировка по заданному показателю

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        key: Показатель статистики, по которому нужно отсортировать;
        order: Порядок сортировки (asc, desc);
    """

    key: str
    order: AnalyticsRequestSortOrder


class AnalyticsResponse(AvitoObject):
    """AnalyticsResponse response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    result: AnalyticsResponseResult | None = None


class AnalyticsResponseResult(AvitoObject):
    """AnalyticsResponseResult response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    data_total_count: int | None = Field(None, alias="dataTotalCount")
    groupings: list[AnalyticsResponseResultGroupings] | None = None
    timestamp: str | None = None


class AnalyticsResponseResultGroupings(AvitoObject):
    """AnalyticsResponseResultGroupings response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    id: int | None = None
    metrics: list[AnalyticsResponseResultGroupingsMetrics] | None = None
    type_: Groupings | None = Field(None, alias="type")


class AnalyticsResponseResultGroupingsMetrics(AvitoObject):
    """AnalyticsResponseResultGroupingsMetrics response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    slug: str
    value: float


class ApplyVasResp(AvitoObject):
    """ApplyVasResp response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        operation_id: Уникальный идентификатор операции покупки
    """

    operation_id: int = Field(..., alias="operationId")


class CallsStatsDay(AvitoObject):
    """CallsStatsDay response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        answered: Отвеченные звонки
        calls: Звонки всего
        date_: Дата (YYYY-MM-DD)
        new: Новые звонки
        new_answered: Новые и одновременно отвеченные звонки
    """

    answered: int | None = None
    calls: int | None = None
    date_: str | None = Field(None, alias="date")
    new: int | None = None
    new_answered: int | None = Field(None, alias="newAnswered")


class CallsStatsItem(AvitoObject):
    """CallsStatsItem response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        days: Массив статистики звонков объявления в разрезе дней
        employee_id: Идентификатор сотрудника в сервисе иерархии аккаунтов (0 означает, что звонок не аттрибуцирован до сотрудника)
        item_id: Идентификатор объявления (0 означает, что звонок не аттрибуцирован до объявления)
    """

    days: list[CallsStatsDay] | None = None
    employee_id: int = Field(..., alias="employeeId")
    item_id: int = Field(..., alias="itemId")


class CallsStatsRequest(AvitoObject):
    """CallsStatsRequest response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        date_from: Начальная дата периода (YYYY-MM-DD)
        date_to: Конечная дата периода (YYYY-MM-DD)
        item_ids: Идентификаторы объявлений
    """

    date_from: str = Field(..., alias="dateFrom")
    date_to: str = Field(..., alias="dateTo")
    item_ids: list[int] | None = Field(None, alias="itemIds")


class CallsStatsResponse(AvitoObject):
    """CallsStatsResponse response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    result: CallsStatsResponseResult | None = None


class CallsStatsResponseResult(AvitoObject):
    """CallsStatsResponseResult response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        items: Массив статистики по объявлениям
    """

    items: list[CallsStatsItem]


class ErrorResponse(AvitoObject):
    """ErrorResponse response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    error: AvitoErrorBody | None = None


class InfoVas(AvitoObject):
    """InfoVas response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        finish_time: Дата завершения услуги
        schedule: Информация о следующих применениях услуги
        vas_id: Идентификатор услуги
    """

    finish_time: TZDatetime | None = None
    schedule: list[TZDatetime] | None = None
    vas_id: InfoVasVasId | None = None


class ItemInfoAvito(AvitoObject):
    """ItemInfoAvito response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        autoload_item_id: [Идентификатор объявления](https://autoload.avito.ru/format/realty/#Id) из файла автозагрузки
        finish_time: Дата завершения объявления
        start_time: Дата создания объявления
        status: Статус объявления на сайте
        url: URL-адрес объявления
        vas: Список примененных платных услуг
    """

    autoload_item_id: str | None = None
    finish_time: TZDatetime | None = None
    start_time: TZDatetime | None = None
    status: ItemInfoAvitoStatus | None = None
    url: str | None = None
    vas: list[InfoVas] | None = None

    def get_item_info(self) -> GetItemInfo:
        """Build an awaitable :class:`GetItemInfo` bound to this object (await to execute)."""
        from ..methods.items import GetItemInfo

        return GetItemInfo(
            user_id=_resolve_user_id(self._client), item_id=self.autoload_item_id
        ).as_(self._client)

    def put_item_vas(self, vas_id: PutItemVasVasId) -> PutItemVas:
        """Build an awaitable :class:`PutItemVas` bound to this object (await to execute)."""
        from ..methods.items import PutItemVas

        return PutItemVas(
            user_id=_resolve_user_id(self._client), item_id=self.autoload_item_id, vas_id=vas_id
        ).as_(self._client)

    def update_price(self, price: int) -> UpdatePrice:
        """Build an awaitable :class:`UpdatePrice` bound to this object (await to execute)."""
        from ..methods.items import UpdatePrice

        return UpdatePrice(item_id=self.autoload_item_id, price=price).as_(self._client)

    def put_item_vas_package_v2(
        self, package_id: PutItemVasPackageV2PackageId
    ) -> PutItemVasPackageV2:
        """Build an awaitable :class:`PutItemVasPackageV2` bound to this object (await to execute)."""
        from ..methods.items import PutItemVasPackageV2

        return PutItemVasPackageV2(
            user_id=_resolve_user_id(self._client),
            item_id=self.autoload_item_id,
            package_id=package_id,
        ).as_(self._client)

    def apply_vas(self, slugs: list[str], stickers: list[int] | None = None) -> ApplyVas:
        """Build an awaitable :class:`ApplyVas` bound to this object (await to execute)."""
        from ..methods.items import ApplyVas

        return ApplyVas(item_id=self.autoload_item_id, slugs=slugs, stickers=stickers).as_(
            self._client
        )


class ItemVasPricesResp(AvitoObject):
    """ItemVasPricesResp response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        item_id: Идентификатор объявления на сайте
    """

    item_id: int | None = Field(None, alias="itemId")
    stickers: list[StickerResp] | None = None
    vas: list[VasResp]


class ItemsInfoWithCategoryAvito(AvitoObject):
    """ItemsInfoWithCategoryAvito response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    meta: ItemsInfoWithCategoryAvitoMeta | None = None
    resources: list[ItemsInfoWithCategoryAvitoResources] | None = None


class ItemsInfoWithCategoryAvitoMeta(AvitoObject):
    """ItemsInfoWithCategoryAvitoMeta response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        page: Номер страницы
        per_page: Количество записей на странице
    """

    page: int | None = None
    per_page: int | None = None


class ItemsInfoWithCategoryAvitoResources(AvitoObject):
    """ItemsInfoWithCategoryAvitoResources response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        address: Адрес объявления
        id: Идентификатор объявления
        price: Цена объявления (null значение означает, что цена не указана)
        status: Статус объявления на сайте
        title: Наименование объявления
        url: URL-адрес объявления
    """

    address: str | None = None
    category: ItemsInfoWithCategoryAvitoResourcesCategory | None = None
    id: int | None = None
    price: int | None = None
    status: ItemsInfoWithCategoryAvitoResourcesStatus | None = None
    title: str | None = None
    url: str | None = None


class ItemsInfoWithCategoryAvitoResourcesCategory(AvitoObject):
    """ItemsInfoWithCategoryAvitoResourcesCategory response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        id: Идентификатор категории
        name: Наименование категории
    """

    id: int | None = None
    name: str | None = None


class SpendingsRequest(AvitoObject):
    """SpendingsRequest response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        date_from: Дата начала периода статистики расходов в формате YYYY-MM-DD
        date_to: Дата конца периода статистики расходов в формате YYYY-MM-DD
        filter: Набор ограничений, по которым необходимо отфильтровать расходы
        spending_types: Набор необходимых типов расходов
    """

    date_from: date = Field(..., alias="dateFrom")
    date_to: date = Field(..., alias="dateTo")
    filter: SpendingsRequestFilter | None = None
    grouping: SpendingsGroupings
    spending_types: list[str] = Field(..., alias="spendingTypes")


class SpendingsRequestFilter(AvitoObject):
    """Набор ограничений, по которым необходимо отфильтровать расходы

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        category_ids: Идентификаторы категорий [ Справочник идентификаторов категорий ](https://www.avito.st/s/openapi/catalog-categories.xml)
        item_ids: Идентификаторы объявлений
        location_ids: Идентификаторы населенных пунктов
    """

    category_ids: list[int] | None = Field(None, alias="categoryIDs")
    item_ids: list[int] | None = Field(None, alias="itemIDs")
    location_ids: list[int] | None = Field(None, alias="locationIDs")


class SpendingsResponse(AvitoObject):
    """SpendingsResponse response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    result: SpendingsResponseResult


class SpendingsResponseResult(AvitoObject):
    """SpendingsResponseResult response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        groupings: Группировки расходов
        timestamp: Временная метка ответа (UTC)
    """

    groupings: list[SpendingsResponseResultGroupings]
    timestamp: int


class SpendingsResponseResultGroupings(AvitoObject):
    """SpendingsResponseResultGroupings response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        date_: Дата группировки в формате YYYY-MM-DD
        spendings: Расходы
    """

    date_: str = Field(..., alias="date")
    spendings: list[SpendingsResponseResultGroupingsSpendings]
    type_: SpendingsGroupings = Field(..., alias="type")


class SpendingsResponseResultGroupingsSpendings(AvitoObject):
    """SpendingsResponseResultGroupingsSpendings response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        services: Детализация по услугам
        slug: Слаг типа расходов (promotion, presence, commission, rest)
        value: Сумма расходов в рублях
    """

    services: list[SpendingsResponseResultGroupingsSpendingsServices] | None = None
    slug: str
    value: float


class SpendingsResponseResultGroupingsSpendingsServices(AvitoObject):
    """SpendingsResponseResultGroupingsSpendingsServices response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        slug: Слаг услуги
        value: Сумма расходов в рублях
    """

    slug: str
    value: float


class StatisticsCountersRoot(AvitoObject):
    """StatisticsCountersRoot response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        item_id: Идентификатор объявления
    """

    item_id: int | None = Field(None, alias="itemId")
    stats: list[StatisticsCountersRootStats] | None = None


class StatisticsCountersRootStats(AvitoObject):
    """StatisticsCountersRootStats response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        contacts: __DEPRECATED (будет удалено в апреле 2021 г.).__ __Используйте поле uniqContacts.__ Запросы контактов объявления.
        date_: Дата (в формате YYYY-MM-DD), за которую посчитаны статистические счетчики. Для группировок по периодам - дата начала периода.
        favorites: __DEPRECATED (будет удалено в апреле 2021 г.).__ __Используйте поле uniqFavorites.__ Добавления объявления в избранное
        uniq_contacts: Уникальные пользователи, запрашивавшие контакты объявления
        uniq_favorites: Уникальные пользователи, добавившие объявление в избранное
        uniq_views: Уникальные пользователи, просматривавшие объявления
        views: __DEPRECATED (будет удалено в апреле 2021 г.).__ __Используйте поле uniqViews.__ Просмотры объявления.
    """

    contacts: int | None = None
    date_: date = Field(..., alias="date")
    favorites: int | None = None
    uniq_contacts: int | None = Field(None, alias="uniqContacts")
    uniq_favorites: int | None = Field(None, alias="uniqFavorites")
    uniq_views: int | None = Field(None, alias="uniqViews")
    views: int | None = None


class StatisticsResponse(AvitoObject):
    """StatisticsResponse response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        result: Статистические счетчики объявления
    """

    errors: dict[str, Any] | None = None
    result: StatisticsResponseResult | None = None


class StatisticsResponseResult(AvitoObject):
    """Статистические счетчики объявления

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    items: list[StatisticsCountersValue] | None = None


class StatisticsCountersValue(AvitoObject):
    """StatisticsCountersValue response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        item_id: Идентификатор объявления
    """

    item_id: int | None = Field(None, alias="itemId")
    stats: list[StatisticsCountersValueStats] | None = None


class StatisticsCountersValueStats(AvitoObject):
    """StatisticsCountersValueStats response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        contacts: __DEPRECATED (будет удалено в апреле 2021 г.).__ __Используйте поле uniqContacts.__ Запросы контактов объявления.
        date_: Дата (в формате YYYY-MM-DD), за которую посчитаны статистические счетчики. Для группировок по периодам - дата начала периода.
        favorites: __DEPRECATED (будет удалено в апреле 2021 г.).__ __Используйте поле uniqFavorites.__ Добавления объявления в избранное
        uniq_contacts: Уникальные пользователи, запрашивавшие контакты объявления
        uniq_favorites: Уникальные пользователи, добавившие объявление в избранное
        uniq_views: Уникальные пользователи, просматривавшие объявления
        views: __DEPRECATED (будет удалено в апреле 2021 г.).__ __Используйте поле uniqViews.__ Просмотры объявления.
    """

    contacts: int | None = None
    date_: date = Field(..., alias="date")
    favorites: int | None = None
    uniq_contacts: int | None = Field(None, alias="uniqContacts")
    uniq_favorites: int | None = Field(None, alias="uniqFavorites")
    uniq_views: int | None = Field(None, alias="uniqViews")
    views: int | None = None


class StatisticsShallowRequestBody(AvitoObject):
    """StatisticsShallowRequestBody response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    date_from: str = Field(..., alias="dateFrom")
    date_to: str = Field(..., alias="dateTo")
    fields: list[StatisticsFieldsValue] | None = None
    item_ids: list[int] = Field(..., alias="itemIds")
    period_grouping: StatisticsPeriodGrouping | None = Field(None, alias="periodGrouping")


class StickerResp(AvitoObject):
    """Информация о значках для переданного списка объявлений

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        description: Описание значка
        id: Идентификатор значка
        title: Название значка
    """

    description: str
    id: int
    title: str


class UpdatePriceRequest(AvitoObject):
    """UpdatePriceRequest response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        price: Цена
    """

    price: int


class UpdatePriceResponse(AvitoObject):
    """UpdatePriceResponse response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    result: UpdatePriceResponseResult


class UpdatePriceResponseResult(AvitoObject):
    """UpdatePriceResponseResult response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    success: bool | None = None


class VasAmountAvito(AvitoObject):
    """VasAmountAvito response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        amount: Сумма списания за применение услуги или пакета
    """

    amount: float | None = None


class VasApplyAvito(AvitoObject):
    """VasApplyAvito response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        amount: Сумма списания за применение услуги
    """

    amount: float | None = None
    vas: InfoVas | None = None


class VasResp(AvitoObject):
    """Информация об услугах и пакетах дополнительных услуг для переданного списка объявлений

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        price: Цена со скидкой
        price_old: Цена до применения скидки
        slug: Идентификатор услуги или пакета услуг
    """

    price: int
    price_old: int = Field(..., alias="priceOld")
    slug: str


class AuthError(AvitoObject):
    """AuthError response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    error: AvitoErrorBody | None = None


class BadRequestError(AvitoObject):
    """BadRequestError response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    error: AvitoErrorBody | None = None


class ItemIdsRequestBody(AvitoObject):
    """ItemIdsRequestBody response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        item_ids: Набор идентификаторов объявлений на сайте
    """

    item_ids: list[int]


class NotFoundError(AvitoObject):
    """NotFoundError response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    error: AvitoErrorBody | None = None


class PackageIdRequestBodyV2(AvitoObject):
    """PackageIdRequestBodyV2 response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        package_id: Идентификатор пакета услуг, возможные варианты значения: - `x2_1` - применение пакета До 2 раз больше просмотров на 1 день - `x2_7` - применение пакета До 2 раз больше просмотров на 7 дней - `x5_1` - применение пакета До 5 раз больше просмотров на 1 день - `x5_7` - применение пакета До 5 раз больше просмотров на 7 дней - `x10_1` - применение пакета До 10 раз больше просмотров на 1 день - `x10_7` - применение пакета До 10 раз больше просмотров на 7 дней В некоторых регионах и категориях также доступны дополнительные варианты: - `x15_1` - применение пакета До 15 раз больше просмотров на 1 день - `x15_7` - применение пакета До 15 раз больше просмотров на 7 дней - `x20_1` - применение пакета До 20 раз больше просмотров на 1 день - `x20_7` - применение пакета До 20 раз больше просмотров на 7 дней Если попытаться применить эти пакеты в недоступных для них регионе и категории, оплата не пройдёт.
    """

    package_id: PackageIdRequestBodyV2PackageId


class PricesItemIdsRequestBody(AvitoObject):
    """PricesItemIdsRequestBody response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        item_ids: Набор идентификаторов объявлений на сайте
    """

    item_ids: list[int] = Field(..., alias="itemIds")


class ServiceError(AvitoObject):
    """ServiceError response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    error: AvitoErrorBody | None = None


class ServiceUnavailableError(AvitoObject):
    """ServiceUnavailableError response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    error: AvitoErrorBody | None = None


class TooManyRequests(AvitoObject):
    """TooManyRequests response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """


class ValidatingError(AvitoObject):
    """ValidatingError response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """

    error: ValidatingErrorError | None = None


class ValidatingErrorError(AvitoObject):
    """ValidatingErrorError response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        code: Код ошибки
        fields: Информация об ошибке валидации параметров в формате ключ-значение
        message: Сообщение об ошибке
    """

    code: int
    fields: dict[str, Any] | None = None
    message: str


class VasIdRequestBody(AvitoObject):
    """VasIdRequestBody response model.

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        vas_id: Идентификатор услуги, возможные его варианты значения: - `highlight` — [выделение объявления](https://support.avito.ru/articles/200026858) - `xl` – [XL-объявление](https://support.avito.ru/articles/685)
    """

    vas_id: VasIdRequestBodyVasId


class ApplyVasResponse(AvitoObject):
    """ApplyVasResponse response model.

    See: https://developers.avito.ru/api-catalog/item/documentation
    """


class ItemAnalyticsFilter(AvitoObject):
    """Набор ограничений, по которым нужно отфильтровать данные

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        category_ids: Идентификаторы категорий [ Справочник идентификаторов категорий ](https://www.avito.st/s/openapi/catalog-categories.xml)
        employee_ids: Идентификаторы сотрудников [ Метод получения идентификаторов сотрудников ](https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation#operation/getEmployeesV1)
    """

    category_ids: list[int] | None = Field(None, alias="categoryIDs")
    employee_ids: list[int] | None = Field(None, alias="employeeIDs")


class ItemAnalyticsSort(AvitoObject):
    """Сортировка по заданному показателю

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        key: Показатель статистики, по которому нужно отсортировать;
        order: Порядок сортировки (asc, desc);
    """

    key: str
    order: ItemAnalyticsSortOrder


class AccountSpendingsFilter(AvitoObject):
    """Набор ограничений, по которым необходимо отфильтровать расходы

    See: https://developers.avito.ru/api-catalog/item/documentation

    Attributes:
        category_ids: Идентификаторы категорий [ Справочник идентификаторов категорий ](https://www.avito.st/s/openapi/catalog-categories.xml)
        item_ids: Идентификаторы объявлений
        location_ids: Идентификаторы населенных пунктов
    """

    category_ids: list[int] | None = Field(None, alias="categoryIDs")
    item_ids: list[int] | None = Field(None, alias="itemIDs")
    location_ids: list[int] | None = Field(None, alias="locationIDs")


class ErrorItemsVas(RootModel[list[int]]):
    """Root wrapper for a top-level ``list[int]`` response."""


class StatisticsCounters(RootModel[list[StatisticsCountersRoot]]):
    """Root wrapper for a top-level ``list[StatisticsCountersRoot]`` response."""


class StatisticsDateFrom(RootModel[str]):
    """Root wrapper for a top-level ``str`` response."""


class StatisticsDateTo(RootModel[str]):
    """Root wrapper for a top-level ``str`` response."""


class StatisticsFields(RootModel[list[StatisticsFieldsRoot]]):
    """Root wrapper for a top-level ``list[StatisticsFieldsRoot]`` response."""


class StatisticsItemIds(RootModel[list[int]]):
    """Root wrapper for a top-level ``list[int]`` response."""


class VasPricesResp(RootModel[list[ItemVasPricesResp]]):
    """Root wrapper for a top-level ``list[ItemVasPricesResp]`` response."""
