# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Продвижение — domain models (auto-generated from the Avito OpenAPI spec).

See: https://developers.avito.ru/api-catalog/promotion/documentation"""

from __future__ import annotations

from pydantic import Field, RootModel

from ..enums.promotion import CommonErrorDetailsSource, OrderServiceStatus, OrderStatus
from ._base import AvitoObject
from .common import TZDatetime


class BbipForecastByItemV1(AvitoObject):
    """Прогноз продвижения по объявлению

    Attributes:
        item_id: Идентификатор объявления
        max: Ожидаемый максимальный прирост просмотров
        min: Ожидаемый минимальный прирост просмотров
        total_old_price: Общая ценность продвижения за весь период до применения скидок и акций (в копейках)
        total_price: Общая стоимость продвижения за весь период (в копейках)
    """

    item_id: int = Field(..., alias="itemId")
    max: int
    min: int
    total_old_price: int = Field(..., alias="totalOldPrice")
    total_price: int = Field(..., alias="totalPrice")


class BbipForecastRequestByItemV1(AvitoObject):
    """BbipForecastRequestByItemV1 response model.

    Attributes:
        duration: Период в днях, для которого запрашивается прогноз
        item_id: Идентификатор объявления
        old_price: Общая ценность продвижения за один день (в копейках)
        price: Стоимость продвижения за один день (в копейках)
    """

    duration: int
    item_id: int = Field(..., alias="itemId")
    old_price: int = Field(..., alias="oldPrice")
    price: int


class BbipOrderByItemV1(AvitoObject):
    """Заявка на подключение услуг продвижения BBIP по объявлению

    Attributes:
        duration: Период действия продвижения в днях
        item_id: Идентификатор объявления
        old_price: Общая ценность продвижения за один день (в копейках)
        price: Стоимость продвижения за один день (в копейках)
    """

    duration: int
    item_id: int = Field(..., alias="itemId")
    old_price: int = Field(..., alias="oldPrice")
    price: int


class BbipSuggestBudgetV1(AvitoObject):
    """Объединённый вариант бюджета продвижения по набору объявлений

    Attributes:
        is_recommended: Рекомендуемый вариант бюджета
        old_price: Общая ценность продвижения за один день до применения скидок и акций (в копейках)
        price: Стоимость продвижения за один день (в копейках)
    """

    is_recommended: bool | None = Field(None, alias="isRecommended")
    old_price: int = Field(..., alias="oldPrice")
    price: int


class BbipSuggestByItemV1(AvitoObject):
    """Вариант бюджета продвижения по объявлению

    Attributes:
        item_id: Идентификатор объявления
    """

    budgets: list[BbipSuggestBudgetV1]
    duration: BbipSuggestDurationRangeV1
    item_id: int = Field(..., alias="itemId")


class BbipSuggestDurationRangeV1(AvitoObject):
    """Вилка доступных периодов для продвижения в днях

    Attributes:
        from_: Минимальное кол-во дней для продвижения
        recommended: Рекомендуемое кол-во дней для продвижения
        to: Максимальное кол-во дней для продвижения
    """

    from_: int = Field(..., alias="from")
    recommended: int | None = None
    to: int


class CommonError(AvitoObject):
    """CommonError response model.

    Attributes:
        details: Информация об ошибках в привязке к полям
        message: Сообщение об ошибке
    """

    details: list[CommonErrorDetails] | None = None
    message: str


class CommonErrorDetails(AvitoObject):
    """CommonErrorDetails response model.

    Attributes:
        message: Информация об ошибке
        path: Путь к полю
        source: Источник значения
        value: Значение поля в строковом представление
    """

    message: str
    path: str
    source: CommonErrorDetailsSource
    value: str | None = None


class ErrorByItemV1(AvitoObject):
    """Информация об ошибке выполнения операции по объявлению

    Attributes:
        error_code: Код ошибки
        error_text: Текст ошибки
        item_id: Идентификатор объявления
    """

    error_code: int = Field(..., alias="errorCode")
    error_text: str = Field(..., alias="errorText")
    item_id: int = Field(..., alias="itemId")


class GetBbipForecastByItemsV1Req(AvitoObject):
    """GetBbipForecastByItemsV1Req response model.

    Attributes:
        items: Данные по объявлениям для запроса прогноза
    """

    items: list[BbipForecastRequestByItemV1] = Field(..., min_length=1, max_length=100)


class GetBbipForecastByItemsV1Resp(AvitoObject):
    """GetBbipForecastByItemsV1Resp response model.

    Attributes:
        errors: Информация об ошибках по объявлениям
        items: Прогноз по каждому объявлению
        total_price: Общая стоимость по всем объявлениям (в копейках)
    """

    errors: list[ErrorByItemV1]
    items: list[BbipForecastByItemV1]
    total_price: int | None = Field(None, alias="totalPrice")


class GetBbipSuggestsV1Req(AvitoObject):
    """GetBbipSuggestsV1Req response model.

    Attributes:
        item_ids: Идентификаторы объявлений
    """

    item_ids: list[int] | None = Field(None, min_length=1, max_length=100, alias="itemIds")


class GetBbipSuggestsV1Resp(AvitoObject):
    """GetBbipSuggestsV1Resp response model.

    Attributes:
        errors: Информация об ошибках получения варианта бюджета
        items: Предлагаемые варианты бюджетов по каждому объявлению
    """

    errors: list[ErrorByItemV1]
    items: list[BbipSuggestByItemV1]


class GetOrderStatusV1Req(AvitoObject):
    """GetOrderStatusV1Req response model.

    Attributes:
        order_id: Идентификатор заявки на подключение услуг продвижения
    """

    order_id: str | None = Field(None, alias="orderId")


class GetOrderStatusV1Resp(AvitoObject):
    """GetOrderStatusV1Resp response model.

    Attributes:
        errors: Информация об ошибках получения данных по объявлениям
        items: Статус заявки на подключение услуги по объявлениям
        order_id: Идентификатор заявки на подключение услуг продвижения
        total_price: Общая стоимость заявки (в копейках)
    """

    errors: list[ErrorByItemV1] | None = None
    items: list[OrderStatusByItemV1] | None = None
    order_id: str | None = Field(None, alias="orderId")
    status: OrderStatus | None = None
    total_price: int | None = Field(None, alias="totalPrice")


class GetServicesByItemsV1Req(AvitoObject):
    """GetServicesByItemsV1Req response model.

    Attributes:
        item_ids: Идентификаторы объявлений
    """

    item_ids: list[int] | None = Field(None, min_length=1, max_length=100, alias="itemIds")


class GetServicesByItemsV1Resp(AvitoObject):
    """GetServicesByItemsV1Resp response model.

    Attributes:
        errors: Информация об ошибках получения варианта бюджета
        items: Информация об услугах продвижения по объявлениям
    """

    errors: list[ErrorByItemV1] | None = None
    items: list[ServicesByItemV1] | None = None


class ListOrdersByUserV1Req(AvitoObject):
    """ListOrdersByUserV1Req response model.

    Attributes:
        pagination: Данные для постраничного чтения
    """

    pagination: ListOrdersByUserV1ReqPagination | None = None


class ListOrdersByUserV1ReqPagination(AvitoObject):
    """Данные для постраничного чтения

    Attributes:
        page: Номер страницы
        per_page: Количество записей на странице
    """

    page: int = 1
    per_page: int = Field(20, ge=1, le=100, alias="perPage")


class ListOrdersByUserV1Resp(AvitoObject):
    """ListOrdersByUserV1Resp response model.

    Attributes:
        orders: Список заявок на подключение услуг продвижения по объявлениям
        pagination: Данные для постраничного чтения
    """

    orders: list[OrderBrief]
    pagination: ListOrdersByUserV1RespPagination


class ListOrdersByUserV1RespPagination(AvitoObject):
    """Данные для постраничного чтения

    Attributes:
        has_next_page: Признак наличия следующей страницы
    """

    has_next_page: bool = Field(..., alias="hasNextPage")


class OrderBbipForItemsV1Req(AvitoObject):
    """OrderBbipForItemsV1Req response model.

    Attributes:
        items: Заявки на подключение BBIP по отдельным объявлениям
    """

    items: list[BbipOrderByItemV1] = Field(..., min_length=1, max_length=100)


class OrderBbipForItemsV1Resp(AvitoObject):
    """OrderBbipForItemsV1Resp response model.

    Attributes:
        errors: Информация об ошибках по объявлениям
        order_id: Идентификатор созданной заявки на подключение услуг продвижения
    """

    errors: list[ErrorByItemV1]
    order_id: str | None = Field(None, alias="orderId")


class OrderBrief(AvitoObject):
    """Информация о заявке на подключение услуг продвижения

    Attributes:
        created_at: Дата создания заявки
        id: Идентификатор заявки
    """

    created_at: TZDatetime | None = Field(None, alias="createdAt")
    id: str | None = None
    status: OrderStatus | None = None


class OrderService(AvitoObject):
    """Информация об услуге в заявке

    Attributes:
        item_id: Идентификатор объявления
        price: Цена услуги на момент создания задачи (в копейках)
        slug: Тип услуги
    """

    item_id: int | None = Field(None, alias="itemId")
    price: int | None = None
    slug: str | None = None
    status_id: OrderServiceStatus | None = Field(None, alias="statusId")


class OrderStatusByItemV1(AvitoObject):
    """Информация об услуге продвижения внутри заявки на подключение

    Attributes:
        error_reason: Описание ошибки
        item_id: Идентификатор объявления
        price: Цена услуги на момент создания задачи (в копейках)
        slug: Тип услуги
    """

    error_reason: str | None = Field(None, alias="errorReason")
    item_id: int | None = Field(None, alias="itemId")
    price: int | None = None
    slug: str | None = None
    status: OrderStatus | None = None


class ServiceInfoV1(AvitoObject):
    """Информация об услуге продвижения

    Attributes:
        is_deprecated: Признак, что тип услуги устарел и более недоступен для подключения
        name: Наименование типа услуги
        slug: Идентификатор типа услуги
    """

    is_deprecated: bool | None = Field(None, alias="isDeprecated")
    name: str
    slug: str


class ServiceV1(AvitoObject):
    """Информация об услуге продвижения

    Attributes:
        end_date: Дата и время завершения продвижения
        name: Наименование услуги
        slug: Тип услуги
        start_date: Дата и время начала продвижения
    """

    end_date: TZDatetime | None = Field(None, alias="endDate")
    name: str | None = None
    slug: str | None = None
    start_date: TZDatetime | None = Field(None, alias="startDate")


class ServicesByItemV1(AvitoObject):
    """Информация об услуге продвижения

    Attributes:
        item_id: Идентификатор объявления
        services: Список услуг по объявлению
    """

    item_id: int | None = Field(None, alias="itemId")
    services: list[ServiceV1] | None = None


class ListOrdersByUserV1Pagination(AvitoObject):
    """Данные для постраничного чтения

    Attributes:
        page: Номер страницы
        per_page: Количество записей на странице
    """

    page: int = 1
    per_page: int = Field(20, ge=1, le=100, alias="perPage")


class GetDictOfServicesV1Resp(RootModel[list[ServiceInfoV1]]):
    """Root wrapper for a top-level ``list[ServiceInfoV1]`` response."""
