# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Аналитика по недвижимости — domain models (auto-generated from the Avito OpenAPI spec).

See: https://developers.avito.ru/api-catalog/realty-reports/documentation"""

from __future__ import annotations

from pydantic import Field

from ..enums.realty_reports import MarketPriceCorrespondenceV1ResponseCorrespondence
from ._base import AvitoObject
from ._shared import MessageResponse


class MarketPriceCorrespondenceV1Response(AvitoObject):
    """MarketPriceCorrespondenceV1Response response model.

    Attributes:
        correspondence: Признак соответствия рыночной цене - below - цена ниже рыночной - normal - цена соответствует рыночной - above - цена выше рыночной
    """

    correspondence: MarketPriceCorrespondenceV1ResponseCorrespondence | None = None
    error: MessageResponse | None = None


class CreateReportForClassifiedResponse(AvitoObject):
    """CreateReportForClassifiedResponse response model."""

    success: CreateReportForClassifiedResponseSuccess


class CreateReportForClassifiedResponseSuccess(AvitoObject):
    """CreateReportForClassifiedResponseSuccess response model."""

    errors: CreateReportForClassifiedResponseSuccessErrors | None = None
    success: CreateReportForClassifiedResponseSuccessSuccess | None = None


class CreateReportForClassifiedResponseSuccessErrors(AvitoObject):
    """CreateReportForClassifiedResponseSuccessErrors response model.

    Attributes:
        access_denied: Объект не принадлежит агенту
        feature_disabled: Фича получения отчета по API недоступна
        invalid_item: Неверный идентификатор объявления
        message: Сообщение об ошибке
    """

    access_denied: bool | None = Field(None, alias="accessDenied")
    feature_disabled: bool | None = Field(None, alias="featureDisabled")
    invalid_item: bool | None = Field(None, alias="invalidItem")
    message: str | None = None


class CreateReportForClassifiedResponseSuccessSuccess(AvitoObject):
    """CreateReportForClassifiedResponseSuccessSuccess response model.

    Attributes:
        report_link: Ссылка на аналитический отчет
    """

    report_link: str = Field(..., alias="reportLink")
