# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Рейтинги и отзывы — domain models (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ..enums.reviews import ReviewAnswerStatus, ReviewStage
from ._base import AvitoObject


class CreateAnswerRequestBody(AvitoObject):
    """CreateAnswerRequestBody response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        message: Текст ответа на отзыв
        review_id: ID отзыва
    """

    message: str
    review_id: int = Field(..., alias="reviewId")


class CreateAnswerResponse(AvitoObject):
    """CreateAnswerResponse response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        created_at: Timestamp создания ответа
        id: ID ответа
    """

    created_at: int = Field(..., alias="createdAt")
    id: int


class GetRatingInfoResponse(AvitoObject):
    """GetRatingInfoResponse response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        is_enabled: Включен ли рейтинг
    """

    is_enabled: bool = Field(..., alias="isEnabled")
    rating: Rating | None = None


class GetReviewsResponse(AvitoObject):
    """GetReviewsResponse response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        reviews: Список отзывов
        total: Количество всех отзывов
    """

    reviews: list[Review]
    total: int


class Rating(AvitoObject):
    """Rating response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        reviews_count: Общее количество активных отзывов
        reviews_with_score_count: Количество активных отзывов, влияющих на формирование рейтинга
        score: Оценка рейтинга
    """

    reviews_count: int = Field(..., alias="reviewsCount")
    reviews_with_score_count: int = Field(..., alias="reviewsWithScoreCount")
    score: float


class RejectReason(AvitoObject):
    """Причина отклонения отзыва

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        id: ID причины отклонения
        title: Заголовок причины отклонения
    """

    id: int
    title: str


class RemoveAnswerResponse(AvitoObject):
    """RemoveAnswerResponse response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        success: Статус успешности запроса
    """

    success: bool


class Review(AvitoObject):
    """Структура отзыва

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        can_answer: Можно ли оставить ответ на отзыв
        created_at: Unix TimeStamp создания отзыва
        extra_params: Дополнительные опциональные параметры отзыва
        id: ID отзыва
        score: Оценка
        stage: Стадия сделки: * `done` - Сделка состоялась * `fell_through` - Сделка сорвалсь * `not_agree` - Не договорились * `not_communicate` - Не общались
        text: Текст отзыва
        used_in_score: Участвует ли отзыв в формирование оценки
    """

    answer: ReviewAnswer | None = None
    can_answer: bool = Field(..., alias="canAnswer")
    created_at: int = Field(..., alias="createdAt")
    extra_params: ReviewExtraParams | None = Field(None, alias="extraParams")
    id: int
    images: list[ReviewImage] | None = None
    item: ReviewItem | None = None
    score: int
    sender: ReviewSender | None = None
    stage: ReviewStage
    text: str
    used_in_score: bool = Field(..., alias="usedInScore")


class ReviewExtraParams(AvitoObject):
    """Дополнительные опциональные параметры отзыва

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        vin: VIN-номер автомобиля в объявлении
    """

    vin: str | None = None


class ReviewAnswer(AvitoObject):
    """Структура ответа на отзыв

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        created_at: Unix TimeStamp создания ответа
        id: ID ответа
        reject_reasons: Список причин отклонения
        status: Статус ответа: * `moderation` - на модерации * `published` - опубликован * `rejected` - отклонен
        text: Текст ответа
    """

    created_at: int = Field(..., alias="createdAt")
    id: int
    reject_reasons: list[RejectReason] | None = None
    status: ReviewAnswerStatus
    text: str


class ReviewError(AvitoObject):
    """Ошибка Bad Request

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        code: Код ошибки
        message: Текст ошибки
    """

    code: str
    message: str


class ReviewImage(AvitoObject):
    """Структура изображения, приложенного к отзыву

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        number: Порядковый номер изображения
        sizes: Список размеров изображения
    """

    number: int
    sizes: list[ReviewImageSize]


class ReviewImageSize(AvitoObject):
    """Структура изображения определенного разрешения

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        size: Разрешение изображения в формате 100x100
        url: Ссылка на изображение
    """

    size: str
    url: str


class ReviewItem(AvitoObject):
    """Структура объявления

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        id: ID объявления
        title: Заголовок объявления
    """

    id: int | None = None
    title: str | None = None


class ReviewSender(AvitoObject):
    """Структура отправителя отзыва

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        name: Имя отправителя
    """

    name: str


class ForbiddenError(AvitoObject):
    """ForbiddenError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation
    """

    error: ForbiddenErrorError | None = None


class ForbiddenErrorError(AvitoObject):
    """ForbiddenErrorError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        code: Код ошибки
        message: Сообщение об ошибке
    """

    code: int
    message: str


class InternalError(AvitoObject):
    """InternalError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation
    """

    error: InternalErrorError | None = None


class InternalErrorError(AvitoObject):
    """InternalErrorError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        code: Код ошибки
        message: Сообщение об ошибке
    """

    code: int
    message: str


class NotFoundError(AvitoObject):
    """NotFoundError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation
    """

    error: NotFoundErrorError | None = None


class NotFoundErrorError(AvitoObject):
    """NotFoundErrorError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        code: Код ошибки
        message: Сообщение об ошибке
    """

    code: int
    message: str


class TooManyRequestsError(AvitoObject):
    """TooManyRequestsError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation
    """

    error: TooManyRequestsErrorError | None = None


class TooManyRequestsErrorError(AvitoObject):
    """TooManyRequestsErrorError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        code: Код ошибки
    """

    code: int


class ValidatingError(AvitoObject):
    """ValidatingError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation
    """

    error: ValidatingErrorError | None = None


class ValidatingErrorError(AvitoObject):
    """ValidatingErrorError response model.

    See: https://developers.avito.ru/api-catalog/ratings/documentation

    Attributes:
        code: Код ошибки
        fields: Информация об ошибке валидации параметров в формате ключ-значение
        message: Сообщение об ошибке
    """

    code: int
    fields: dict[str, Any] | None = None
    message: str
