# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Управление остатками — domain models (auto-generated from the Avito OpenAPI spec).

See: https://developers.avito.ru/api-catalog/stock-management/documentation"""

from __future__ import annotations

from ._base import AvitoObject


class StockEditResult(AvitoObject):
    """StockEditResult response model."""

    stocks: list[StockEditResultStocks] | None = None


class StockEditResultStocks(AvitoObject):
    """Остатки в объявлении

    Attributes:
        errors: Ошибки при обновлении остатка
        external_id: Идентификатор объявления во внешней системе
        item_id: Идентификатор объявления на сайте
        success: Успешно ли прошло обновление остатков
    """

    errors: list[str] | None = None
    external_id: str | None = None
    item_id: int
    success: bool


class StocksInfoResult(AvitoObject):
    """StocksInfoResult response model."""

    stocks: list[StocksInfoResultStocks] | None = None


class StocksInfoResultStocks(AvitoObject):
    """Информация по остаткам

    Attributes:
        is_multiple: Флаг с подачи или редактирования \"Несколько штук в наличии\"
        is_out_of_stock: Признак того, что у объявления закончилось доступное кол-во товара
        is_unlimited: Признак неограниченности стоков
        item_id: Идентификатор объявления на сайте
        quantity: Доступное количество товара (количество с подачи или редактирования минус бронь)
    """

    is_multiple: bool
    is_out_of_stock: bool
    is_unlimited: bool
    item_id: int
    quantity: int


class UnauthError(AvitoObject):
    """UnauthError response model.

    Attributes:
        message: Сообщение о том, что пользователь не авторизован. Если текст ошибки \"Unsupported flow for endpoint\", значит в авторизационном заголовке \"X-Oauth-Flow\" не передан \"authorization_code\"
    """

    message: str
