# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""TrxPromo — domain models (auto-generated from the Avito OpenAPI spec).

See: https://developers.avito.ru/api-catalog/trxpromo/documentation"""

from __future__ import annotations

from pydantic import Field

from ._base import AvitoObject
from ._shared import MessageResponse
from .common import AvitoErrorBody


class ApplyReq(AvitoObject):
    """ApplyReq response model."""

    items: list[ApplyReqItems]


class ApplyReqItems(AvitoObject):
    """ApplyReqItems response model.

    Attributes:
        commission: Комиссия за продвижение в сотых долях 1500 - 15%
        date_from: Дата начала продвижения
        date_to: Дата окончания продвижения
    """

    commission: int
    date_from: str = Field(..., alias="dateFrom")
    date_to: str | None = Field(None, alias="dateTo")
    item_id: int = Field(..., alias="itemID")


class ApplyResponse(AvitoObject):
    """ApplyResponse response model."""

    success: ApplyResponseSuccess


class ApplyResponseSuccess(AvitoObject):
    """ApplyResponseSuccess response model."""

    result: list[ApplyResponseSuccessResult]


class ApplyResponseSuccessResult(AvitoObject):
    """ApplyResponseSuccessResult response model."""

    error: AvitoErrorBody | None = None
    item_id: int = Field(..., alias="itemID")
    success: bool
    valid_commission_range: ApplyResponseSuccessResultValidCommissionRange | None = Field(
        None, alias="validCommissionRange"
    )


class ApplyResponseSuccessResultValidCommissionRange(AvitoObject):
    """ApplyResponseSuccessResultValidCommissionRange response model.

    Attributes:
        step: Шаг изменения комиссии в сотых долях 100 - 1%
        value_max: Максимальный размер комиссии в сотых долях 100 - 1%
        value_min: Минимальный размер комиссии в сотых долях 100 - 1%
    """

    step: int
    value_max: int = Field(..., alias="valueMax")
    value_min: int = Field(..., alias="valueMin")


class CancelResponse(AvitoObject):
    """CancelResponse response model."""

    success: CancelResponseSuccess


class CancelResponseSuccess(AvitoObject):
    """CancelResponseSuccess response model."""

    result: list[CancelResponseSuccessResult]


class CancelResponseSuccessResult(AvitoObject):
    """CancelResponseSuccessResult response model."""

    error: AvitoErrorBody | None = None
    item_id: int = Field(..., alias="itemID")
    success: bool


class CommissionResponse(AvitoObject):
    """CommissionResponse response model."""

    success: CommissionResponseSuccess


class CommissionResponseSuccess(AvitoObject):
    """CommissionResponseSuccess response model."""

    result: list[CommissionResponseSuccessResult]


class CommissionResponseSuccessResult(AvitoObject):
    """CommissionResponseSuccessResult response model.

    Attributes:
        promo_available: Флаг доступности промо
        settings: Доступные настройки продвижения
    """

    error: AvitoErrorBody | None = None
    item_id: int = Field(..., alias="itemID")
    promo_available: bool = Field(..., alias="promoAvailable")
    settings: CommissionResponseSuccessResultSettings


class CommissionResponseSuccessResultSettings(AvitoObject):
    """Доступные настройки продвижения

    Attributes:
        step: Шаг изменения процента в сотых долях 100 - 1%
        value_max: Максимальный процент в сотых долях 100 - 1%
        value_min: Минимальный процент в сотых долях 100 - 1%
    """

    step: int
    value_max: int = Field(..., alias="valueMax")
    value_min: int = Field(..., alias="valueMin")


class ApiV3error400(AvitoObject):
    """ApiV3error400 response model."""

    bad_request: MessageResponse = Field(..., alias="bad-request")


class ApiV3error401(AvitoObject):
    """ApiV3error401 response model."""

    unauthenticated: MessageResponse


class ApiV3error403(AvitoObject):
    """ApiV3error403 response model."""

    forbidden: MessageResponse


class ApiV3error500(AvitoObject):
    """ApiV3error500 response model."""

    internal_error: MessageResponse = Field(..., alias="internal-error")


class ApiTrxPromoOpenApiApplyItems(AvitoObject):
    """ApiTrxPromoOpenApiApplyItems response model.

    Attributes:
        commission: Комиссия за продвижение в сотых долях 1500 - 15%
        date_from: Дата начала продвижения
        date_to: Дата окончания продвижения
    """

    commission: int
    date_from: str = Field(..., alias="dateFrom")
    date_to: str | None = Field(None, alias="dateTo")
    item_id: int = Field(..., alias="itemID")
