# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Информация о пользователе — domain models (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from pydantic import Field

from ..enums.user import (
    ResponseOperationsHistoryItemOperationType,
    ResponseOperationsHistoryItemServiceType,
)
from ._base import AvitoObject
from .common import TZDatetime


class Balance(AvitoObject):
    """Balance response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        bonus: Сумма бонусных средств
        real: Сумма реальных денежных средств
    """

    bonus: float | None = None
    real: float | None = None


class RequestOperationsHistory(AvitoObject):
    """RequestOperationsHistory response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        date_time_from: Время выборки от. Не далее одного года в прошлое от текущего момента.
        date_time_to: Время выборки до (диапазон между dateTimeFrom и dateTimeTo должен быть не более одной недели)
    """

    date_time_from: TZDatetime = Field(..., alias="dateTimeFrom")
    date_time_to: TZDatetime = Field(..., alias="dateTimeTo")


class ResponseOperationsHistory(AvitoObject):
    """ResponseOperationsHistory response model.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    result: ResponseOperationsHistoryResult | None = None


class ResponseOperationsHistoryResult(AvitoObject):
    """ResponseOperationsHistoryResult response model.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    operations: list[ResponseOperationsHistoryItem] | None = None


class ResponseOperationsHistoryItem(AvitoObject):
    """ResponseOperationsHistoryItem response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        amount_bonus: Сумма бонусов
        amount_rub: Сумма реальных денег
        amount_total: Сумма операции всего
        item_id: ID объявления
        operation_name: Название операции
        operation_type: Тип операции
        paid_at: Дата/время оплаты операции
        service_id: Код типа услуги
        service_name: Название конкретного типа услуги
        service_type: Тип услуги
        updated_at: Дата/время совершения операции
    """

    amount_bonus: float | None = Field(None, alias="amountBonus")
    amount_rub: float | None = Field(None, alias="amountRub")
    amount_total: float | None = Field(None, alias="amountTotal")
    item_id: int | None = Field(None, alias="itemId")
    operation_name: str | None = Field(None, alias="operationName")
    operation_type: ResponseOperationsHistoryItemOperationType | None = Field(
        None, alias="operationType"
    )
    paid_at: str | None = Field(None, alias="paidAt")
    service_id: int | None = Field(None, alias="serviceId")
    service_name: str | None = Field(None, alias="serviceName")
    service_type: ResponseOperationsHistoryItemServiceType | None = Field(None, alias="serviceType")
    updated_at: str | None = Field(None, alias="updatedAt")


class UserInfoSelf(AvitoObject):
    """UserInfoSelf response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        email: Email пользователя
        id: Идентификатор пользователя
        name: Имя пользователя
        phone: первый верифицированный телефон пользователя
        phones: все верифицированные номера телефонов
        profile_url: Ссылка на профиль пользователя
    """

    email: str | None = None
    id: int | None = None
    name: str | None = None
    phone: str | None = None
    phones: list[str] | None = None
    profile_url: str | None = None


class AuthError(AvitoObject):
    """AuthError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    error: AuthErrorError | None = None


class AuthErrorError(AvitoObject):
    """AuthErrorError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        code: Код ошибки
        message: Сообщение об ошибке
    """

    code: int
    message: str


class ForbiddenError(AvitoObject):
    """ForbiddenError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    error: ForbiddenErrorError | None = None


class ForbiddenErrorError(AvitoObject):
    """ForbiddenErrorError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        code: Код ошибки
        message: Сообщение об ошибке
    """

    code: int
    message: str


class NotFoundError(AvitoObject):
    """NotFoundError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    error: NotFoundErrorError | None = None


class NotFoundErrorError(AvitoObject):
    """NotFoundErrorError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        code: Код ошибки
        message: Сообщение об ошибке
    """

    code: int
    message: str


class ServiceError(AvitoObject):
    """ServiceError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    error: ServiceErrorError | None = None


class ServiceErrorError(AvitoObject):
    """ServiceErrorError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        code: Код ошибки
        message: Описание ошибки
    """

    code: int
    message: str


class ServiceUnavailableError(AvitoObject):
    """ServiceUnavailableError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    error: ServiceUnavailableErrorError | None = None


class ServiceUnavailableErrorError(AvitoObject):
    """ServiceUnavailableErrorError response model.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Attributes:
        code: Код ошибки
        message: Описание ошибки
    """

    code: int
    message: str
