# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Иерархия Аккаунтов — domain endpoints (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.accounts_hierarchy import (
    CheckAhUserV1Response,
    CheckAhUserV2Response,
    CompanyPhonesResult,
    GetAhInfoV1Response,
    GetEmployeesResult,
    ListItemsByEmployeeIdResult,
)
from ._base import BaseMethod


class CheckAhUserV1(BaseMethod[CheckAhUserV1Response]):
    """Получение информации о статусе пользователя в ИА via ``GET /checkAhUserV1``.

    See: https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/checkAhUserV1"


class CheckAhUserV2(BaseMethod[CheckAhUserV2Response]):
    """Получение информации о статусе пользователя в ИА via ``GET /checkAhUserV2``.

    See: https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/checkAhUserV2"


class GetAhInfoV1(BaseMethod[GetAhInfoV1Response]):
    """Получение полной информации о статусе пользователя в ИА via ``GET /getAhInfoV1``.

    See: https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/getAhInfoV1"


class GetEmployeesV1(BaseMethod[GetEmployeesResult]):
    """Получение списка сотрудников иерархии via ``GET /getEmployeesV1``.

    See: https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/getEmployeesV1"


class LinkItemsV1(BaseMethod[None]):
    """Прикрепление сотрудника иерархии к объявлениям, перезакрепление объявлений между сотрудниками иерархии via ``POST /linkItemsV1``.

    See: https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation

    Args:
        employee_id: Идентификатор сотрудника, к которому прилинкуются объявления
        item_ids: Список идентификаторов объявлений для линковки (max 50)
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/linkItemsV1"

    employee_id: int = Field(..., ge=1, alias="employeeId")
    item_ids: list[int] = Field(..., min_length=1, max_length=50, alias="itemIds")


class ListCompanyPhonesV1(BaseMethod[CompanyPhonesResult]):
    """Получение списка телефонов компании via ``GET /listCompanyPhonesV1``.

    See: https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation

    Args:
        cursor: Курсор для получения следующей страницы. Передается из предыдущего ответа.
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/listCompanyPhonesV1"

    cursor: str | None = None


class ListItemsByEmployeeIdV1(BaseMethod[ListItemsByEmployeeIdResult]):
    """Получение списка объявлений по сотруднику via ``POST /listItemsByEmployeeIdV1``.

    See: https://developers.avito.ru/api-catalog/accounts-hierarchy/documentation

    Args:
        category_id: Идентификатор категории объявления
        employee_id: Идентификатор сотрудника, к которому прилинкованы объявления
        last_item_id: Идентификатор объявления для пагинации по курсору
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/listItemsByEmployeeIdV1"

    category_id: int = Field(..., ge=1, alias="categoryId")
    employee_id: int = Field(..., ge=1, alias="employeeId")
    last_item_id: int | None = Field(None, ge=1, alias="lastItemId")
