# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""CPA-аукцион — domain endpoints (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.auction import GetUserBidsResponse, SaveItemBidsItems
from ._base import BaseMethod


class GetUserBids(BaseMethod[GetUserBidsResponse]):
    """Получение информации о действующих и доступных ставках via ``GET /auction/1/bids``.

    See: https://developers.avito.ru/api-catalog/auction/documentation

    Args:
        from_item_id: Идентификатор последнего объявления в предыдущей пачке (по умолчанию 0)
        batch_size: Кол-во объявлений в пачке (максимум 200)
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/auction/1/bids"

    from_item_id: int = Field(0, ge=0, alias="fromItemID")
    batch_size: int = Field(200, ge=1, le=200, alias="batchSize")


class SaveItemBids(BaseMethod[None]):
    """Сохранение новых ставок via ``POST /auction/1/bids``.

    See: https://developers.avito.ru/api-catalog/auction/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/auction/1/bids"

    items: list[SaveItemBidsItems] = Field(..., min_length=1, max_length=200)
