# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Автозагрузка — domain endpoints (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.autoload import (
    ApiCategoryTreeOut,
    ApiFieldsOut,
    ExportScheduleValue,
    FeedsDataValue,
    GetAdIdsByAvitoIdsResponse,
    GetAutoloadItemsInfoV2Response,
    GetAvitoIdsByAdIdsResponse,
    GetCurrentUploadItemsResponse,
    GetLastSuccessfulUploadItemsResponse,
    GetProfileResponse,
    GetProfileV2Response,
    GetReportItemsByIdResponse,
    GetReportItemsFeesByIdResponse,
    GetReportsV2Response,
    GetUploadsResponse,
    ReportAutoloadV2,
    ReportAutoloadV3,
    UploadAutoloadV4,
)
from ..models.common import TZDatetime
from ._base import BaseMethod


class GetProfile(BaseMethod[GetProfileResponse]):
    """Получение профиля пользователя автозагрузки (deprecated) via ``GET /autoload/v1/profile``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v1/profile"


class CreateOrUpdateProfile(BaseMethod[None]):
    """Создание/редактирование настроек профиля пользователя автозагрузки (deprecated) via ``POST /autoload/v1/profile``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        agreement: Согласие с [правилами](https://support.avito.ru/articles/203867776) использования Авито Автозагрузки. Обязательно, если профиль еще не существует.
        autoload_enabled: Статус автозагрузки (вкл/выкл)
        report_email: Почта, на которую будут приходить отчеты о выгрузках
        upload_url: URL-адрес фида, для которого настроены регулярные выгрузки. Должен начинаться с http или https.
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/autoload/v1/profile"

    agreement: bool | None = None
    autoload_enabled: bool
    report_email: str
    schedule: list[ExportScheduleValue]
    upload_url: str


class Upload(BaseMethod[None]):
    """Загрузка файла по ссылке via ``POST /autoload/v1/upload``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/autoload/v1/upload"


class UserDocsNodeFields(BaseMethod[ApiFieldsOut]):
    """Получения полей категории via ``GET /autoload/v1/user-docs/node/{node_slug}/fields``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        node_slug: slug узла дерева категории
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v1/user-docs/node/{node_slug}/fields"

    node_slug: str


class UserDocsTree(BaseMethod[ApiCategoryTreeOut]):
    """Получение дерева категорий via ``GET /autoload/v1/user-docs/tree``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v1/user-docs/tree"


class GetAdIdsByAvitoIds(BaseMethod[GetAdIdsByAvitoIdsResponse]):
    """ID объявлений из файла via ``GET /autoload/v2/items/ad_ids``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        query: Список ID объявлений. Формат значения: строка с идентификаторами объявлений на Авито, перечисленными через «,» или «|».
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/items/ad_ids"

    query: str


class GetAvitoIdsByAdIds(BaseMethod[GetAvitoIdsByAdIdsResponse]):
    """ID объявлений на Авито via ``GET /autoload/v2/items/avito_ids``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        query: Список ID объявлений. Формат значения: строка с [идентификаторами объявлений из файла](https://autoload.avito.ru/format/realty/#Id), перечисленными через «,» или «|»
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/items/avito_ids"

    query: str


class GetProfileV2(BaseMethod[GetProfileV2Response]):
    """Получение профиля пользователя автозагрузки via ``GET /autoload/v2/profile``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/profile"


class CreateOrUpdateProfileV2(BaseMethod[None]):
    """Создание/редактирование настроек профиля пользователя автозагрузки via ``POST /autoload/v2/profile``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        agreement: Согласие с [правилами](https://support.avito.ru/articles/203867776) использования Авито Автозагрузки. Обязательно, если профиль еще не существует.
        autoload_enabled: Статус автозагрузки (вкл/выкл)
        report_email: Почта, на которую будут приходить отчеты о выгрузках
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/autoload/v2/profile"

    agreement: bool | None = None
    autoload_enabled: bool
    feeds_data: list[FeedsDataValue]
    report_email: str
    schedule: list[ExportScheduleValue]


class GetReportsV2(BaseMethod[GetReportsV2Response]):
    """Список отчётов автозагрузки (deprecated) via ``GET /autoload/v2/reports``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        per_page: Количество отчётов на странице: целое число больше 0 и меньше или равно 200.
        page: Номер страницы: целое число больше или равно 0.
        date_from: Фильтр по дате создания отчёта «от» (от такой-то даты). Формат значения: RFC3339
        date_to: Фильтр по дате создания отчёта «до» (до такой-то даты). Формат значения: RFC3339
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/reports"

    per_page: int = 50
    page: int = 0
    date_from: TZDatetime | None = None
    date_to: TZDatetime | None = None


class GetAutoloadItemsInfoV2(BaseMethod[GetAutoloadItemsInfoV2Response]):
    """Объявления по ID в автозагрузке (deprecated) via ``GET /autoload/v2/reports/items``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        query: Идентификаторы объявлений из файла ([параметр Id](https://autoload.avito.ru/format/realty/#Id)). Формат значения: строка, содержащая от 1 до 100 идентификаторов, перечисленных через «,» или «|».
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/reports/items"

    query: str


class GetLastCompletedReport(BaseMethod[ReportAutoloadV2]):
    """Статистика по последней выгрузке (deprecated) via ``GET /autoload/v2/reports/last_completed_report``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/reports/last_completed_report"


class GetReportByIdV2(BaseMethod[ReportAutoloadV2]):
    """Статистика по конкретной выгрузке (deprecated) via ``GET /autoload/v2/reports/{report_id}``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        report_id: Идентификатор отчёта (ID)
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/reports/{report_id}"

    report_id: int


class GetReportItemsById(BaseMethod[GetReportItemsByIdResponse]):
    """Все объявления из конкретной выгрузки (deprecated) via ``GET /autoload/v2/reports/{report_id}/items``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        report_id: Идентификатор отчёта (ID)
        per_page: Количество объявлений на странице: целое число больше 0 и меньше или равно 200
        page: Номер страницы: целое число больше или равно 0
        query: Фильтр по ID объявления. Формат значения: строка с [идентификаторами объявлений из файла](https://autoload.avito.ru/format/realty/#Id) или идентификаторами объявлений на Авито, перечисленными через «,» или «|».
        sections: Фильтр объявлений по разделам. Формат значения: строка с идентификаторами разделов, перечисленными через «,» или «|». Получить список разделов для конкретного отчёта можно с помощью метода [Статистика по конкретной выгрузке](https://developers.avito.ru/api-catalog/autoload/documentation#operation/getReportByIdV3).
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/reports/{report_id}/items"

    report_id: int
    per_page: int = 50
    page: int = 0
    query: str | None = None
    sections: str | None = None


class GetReportItemsFeesById(BaseMethod[GetReportItemsFeesByIdResponse]):
    """Списания за объявления в конкретной выгрузке (deprecated) via ``GET /autoload/v2/reports/{report_id}/items/fees``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        report_id: Идентификатор отчёта (ID)
        per_page: Количество объявлений на странице: целое число больше 0 и меньше или равно 200
        page: Номер страницы: целое число больше или равно 0
        ad_ids: Фильтр по ID объявления. Формат значения: строка с [идентификаторами объявлений из файла](https://autoload.avito.ru/format/realty/#Id), перечисленными через «,» или «|».
        avito_ids: Фильтр по AvitoID объявления. Формат значения: строка с идентификаторами объявлений на Авито, перечисленными через «,» или «|».
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v2/reports/{report_id}/items/fees"

    report_id: int
    per_page: int = 100
    page: int = 0
    ad_ids: str | None = None
    avito_ids: str | None = None


class GetLastCompletedReportV3(BaseMethod[ReportAutoloadV3]):
    """Статистика по последней выгрузке (deprecated) via ``GET /autoload/v3/reports/last_completed_report``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v3/reports/last_completed_report"


class GetReportByIdV3(BaseMethod[ReportAutoloadV3]):
    """Статистика по конкретной выгрузке (deprecated) via ``GET /autoload/v3/reports/{report_id}``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        report_id: Идентификатор отчёта (ID)
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v3/reports/{report_id}"

    report_id: int


class GetUploads(BaseMethod[GetUploadsResponse]):
    """История загрузок via ``GET /autoload/v4/uploads``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        per_page: Количество загрузок на странице
        page: Номер страницы
        date_from: Фильтр по дате загрузки «от» (от такой-то даты). Формат значения: RFC3339
        date_to: Фильтр по дате загрузки «до» (до такой-то даты). Формат значения: RFC3339
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v4/uploads"

    per_page: int = Field(10, ge=1, le=50, alias="perPage")
    page: int = Field(1, ge=1)
    date_from: TZDatetime | None = Field(None, alias="dateFrom")
    date_to: TZDatetime | None = Field(None, alias="dateTo")


class GetCurrentUpload(BaseMethod[UploadAutoloadV4]):
    """Текущая загрузка via ``GET /autoload/v4/uploads/current``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v4/uploads/current"


class GetCurrentUploadItems(BaseMethod[GetCurrentUploadItemsResponse]):
    """Объявления текущей загрузки via ``GET /autoload/v4/uploads/current/items``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        query: Поиск по одному или нескольким [идентификаторам объявлений из файла](https://www.avito.ru/autoload/documentation/templates/66940?fileFormat=xml#field-Id), перечисленным через «,» или «|». Без параметра — возвращаются все объявления с пагинацией.
        sections: Фильтр по разделам отчёта. Формат значения: строка со slug разделов, перечисленными через запятую.
        per_page: Количество объявлений на странице
        page: Номер страницы
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v4/uploads/current/items"

    query: str | None = None
    sections: str | None = None
    per_page: int = Field(20, ge=1, le=100, alias="perPage")
    page: int = Field(1, ge=1)


class GetLastSuccessfulUpload(BaseMethod[UploadAutoloadV4]):
    """Последняя успешно завершённая загрузка via ``GET /autoload/v4/uploads/last_successful``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v4/uploads/last_successful"


class GetLastSuccessfulUploadItems(BaseMethod[GetLastSuccessfulUploadItemsResponse]):
    """Объявления последней успешно завершённой загрузки via ``GET /autoload/v4/uploads/last_successful/items``.

    See: https://developers.avito.ru/api-catalog/autoload/documentation

    Args:
        query: Поиск по одному или нескольким [идентификаторам объявлений из файла](https://www.avito.ru/autoload/documentation/templates/66940?fileFormat=xml#field-Id), перечисленным через «,» или «|». Без параметра — возвращаются все объявления с пагинацией.
        sections: Фильтр по разделам отчёта. Формат значения: строка со slug разделов, перечисленными через запятую.
        per_page: Количество объявлений на странице
        page: Номер страницы
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/autoload/v4/uploads/last_successful/items"

    query: str | None = None
    sections: str | None = None
    per_page: int = Field(20, ge=1, le=100, alias="perPage")
    page: int = Field(1, ge=1)
