# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Авито Promo — domain endpoints (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from datetime import date
from typing import ClassVar

from pydantic import Field

from ..enums.avito_promo import (
    LinkType,
    StatsAccountsSpendingsSpendingTypes,
    StatsMetric,
    StatsMetricsGrouping,
    StatsSpendingsGrouping,
)
from ..models.avito_promo import (
    AgencyBalanceResponse,
    AgencyClientsExtra,
    AgencyClientsResponse,
    AgencyClientsTargetCreateResponse,
    AgencyClientsTargetResultResponse,
    AgencyFinancesBalanceResponse,
    AgencyFinancesTransactionsHistoryResponse,
    AgencyTransactionResponse,
    AgencyTransactionsResponse,
    AgencyUsersInviteSendResponse,
    AgencyUsersInviteStatusResponse,
    AgencyUsersVerificationStatusResponse,
    StatsAccountsItemsFilter,
    StatsAccountsItemsResponse,
    StatsAccountsItemsSort,
    StatsAccountsSpendingsFilter,
    StatsAccountsSpendingsResponse,
)
from ..models.common import TZDatetime
from ._base import BaseMethod


class AgencyBalance(BaseMethod[AgencyBalanceResponse]):
    """Перевод средств на счёт клиента via ``POST /agency/balance``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation

    Args:
        amount: Сумма в рублях
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/agency/balance"

    amount: int = Field(..., ge=1)
    user_id: int = Field(..., alias="userId")


class AgencyTransactions(BaseMethod[AgencyTransactionsResponse]):
    """Получение списка незавершённых транзакций via ``GET /agency/transactions``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/agency/transactions"


class AgencyTransaction(BaseMethod[AgencyTransactionResponse]):
    """Получение информации о транзакции via ``GET /agency/transactions/{transaction_id}``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation

    Args:
        transaction_id: Идентификатор транзакции
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/agency/transactions/{transaction_id}"

    transaction_id: str


class AgencyClients(BaseMethod[AgencyClientsResponse]):
    """Получение списка клиентов via ``POST /api/1/agency/clients``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation

    Args:
        extra: Настройка дополнительной информации о клиентах
        limit: Ограничение количества сущностей в выборке
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/api/1/agency/clients"

    extra: AgencyClientsExtra | None = None
    limit: int = Field(..., ge=1, le=100)
    offset: int | None = None


class AgencyClientsTargetCreate(BaseMethod[AgencyClientsTargetCreateResponse]):
    """Создание задачи на проверку ИНН клиентов via ``POST /api/1/agency/clients/target/create``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation

    Args:
        inn_list: Список ИНН
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/api/1/agency/clients/target/create"

    inn_list: list[str] = Field(..., min_length=1, max_length=100, alias="innList")


class AgencyClientsTargetResult(BaseMethod[AgencyClientsTargetResultResponse]):
    """Получение результата проверки ИНН клиентов via ``POST /api/1/agency/clients/target/result``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/api/1/agency/clients/target/result"

    task_id: int = Field(..., alias="taskId")


class AgencyFinancesBalance(BaseMethod[AgencyFinancesBalanceResponse]):
    """Получение баланса агентства via ``GET /api/1/agency/finances/balance``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/api/1/agency/finances/balance"


class AgencyFinancesTransactionsHistory(BaseMethod[AgencyFinancesTransactionsHistoryResponse]):
    """Получение всех операций с балансом агентства via ``POST /api/1/agency/finances/transactionsHistory``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/api/1/agency/finances/transactionsHistory"

    date_from: TZDatetime = Field(..., alias="dateFrom")
    date_to: TZDatetime = Field(..., alias="dateTo")
    limit: int
    offset: int


class AgencyUsersInviteSend(BaseMethod[AgencyUsersInviteSendResponse]):
    """Отправка приглашения нового клиента via ``POST /api/1/agency/users/invite/send``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/api/1/agency/users/invite/send"

    type_: LinkType = Field(..., alias="type")
    user_id: int = Field(..., alias="userId")


class AgencyUsersInviteStatus(BaseMethod[AgencyUsersInviteStatusResponse]):
    """Получение статуса приглашения нового клиента via ``POST /api/1/agency/users/invite/status``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/api/1/agency/users/invite/status"

    invite_id: int = Field(..., alias="inviteId")


class AgencyUsersVerificationStatus(BaseMethod[AgencyUsersVerificationStatusResponse]):
    """Получение статуса верификации нового клиента via ``POST /api/1/agency/users/verificationStatus``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/api/1/agency/users/verificationStatus"

    invite_id: int = Field(..., alias="inviteId")


class StatsAccountsItems(BaseMethod[StatsAccountsItemsResponse]):
    """Получение статистических показателей клиента via ``POST /stats/v2/accounts/{user_id}/items``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation

    Args:
        user_id: Идентификатор пользователя клиента
        filter: Набор ограничений, по которым будут отфильтрованы данные статистики
        metrics: Набор показателей, которые должны быть в статистике
        sort: Сортировка данных статистики
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/stats/v2/accounts/{user_id}/items"

    user_id: int
    date_from: date = Field(..., alias="dateFrom")
    date_to: date = Field(..., alias="dateTo")
    filter: StatsAccountsItemsFilter | None = None
    grouping: StatsMetricsGrouping
    limit: int | None = None
    metrics: list[StatsMetric] = Field(..., min_length=1)
    offset: int | None = None
    sort: StatsAccountsItemsSort | None = None


class StatsAccountsSpendings(BaseMethod[StatsAccountsSpendingsResponse]):
    """Получение статистики расходов клиента via ``POST /stats/v2/accounts/{user_id}/spendings``.

    See: https://developers.avito.ru/api-catalog/avito-promo/documentation

    Args:
        user_id: Идентификатор пользователя клиента
        filter: Набор ограничений, по которым будут отфильтрованы данные статистики
        spending_types: Набор категорий расходов клиента
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/stats/v2/accounts/{user_id}/spendings"

    user_id: int
    date_from: date = Field(..., alias="dateFrom")
    date_to: date = Field(..., alias="dateTo")
    filter: StatsAccountsSpendingsFilter | None = None
    grouping: StatsSpendingsGrouping
    spending_types: list[StatsAccountsSpendingsSpendingTypes] = Field(..., alias="spendingTypes")
