# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Доставка — domain endpoints (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import Any, ClassVar

from pydantic import Field

from ..enums.delivery import (
    AddTariffSandboxV2TariffType,
    CancelAnnouncement3PlReason,
    CancelParcelActor,
    ChangeParcelResultStatus,
    ChangeParcelsType,
    CreateAnnouncement3PlAnnouncementType,
    CreateAnnouncementAnnouncementType,
    TrackAnnouncementEvent,
    V1changeParcelType,
    V1createAnnouncementAnnouncementType,
)
from ..models._shared import StorageExtendedToResponse
from ..models.common import TZDatetime
from ..models.delivery import (
    AddTariffReply,
    AddTaskReply,
    AddTerminalsReply,
    AnnouncementsSuccessResponse,
    CancelParcelReply,
    CancelSandboxParcelOptions,
    CancelSandboxParcelReply,
    ChangeParcelReply,
    ChangeParcelRequestApplication,
    ChangeParcelRequestOptions,
    ChangeParcelResultReply,
    ChangeParcelsApplication,
    ChangeParcelsResponse,
    CheckConfirmationCodeReply,
    CreateParcelClient,
    CreateParcelItem,
    CreateParcelOptions,
    CreateParcelPackage,
    CreateParcelPayment,
    CreateParcelReply,
    CreateParcelResponse,
    CreateSandboxParcelItem,
    CreateSandboxParcelV22Receiver,
    CreateSandboxParcelV22Sender,
    CreateSandboxV2Options,
    DeliveryParams,
    DeliverySetOrderPropertiesReply,
    DeliverySetStatusReply,
    DirectionV2,
    GetChangeParcelInfoReply,
    GetRegisteredParcelIdReply,
    GetSandboxParcelInfoReply,
    GetTaskReply,
    ProhibitOrderAcceptanceReply,
    SandboxCancelAnnouncementOptions,
    SandboxCancelAnnouncementReply,
    SandboxCreateAnnouncementOptions,
    SandboxCreateAnnouncementPackage,
    SandboxCreateAnnouncementParticipant,
    SandboxCreateAnnouncementReply,
    SandboxGetAnnouncementEventReply,
    SetOrderRealAddressAddress,
    SortingCenterGet,
    TariffZone,
    TermsZone,
    TrackingOptions,
    UpdateTermsReply,
)
from ._base import BaseMethod


class CancelAnnouncement3Pl(BaseMethod[AnnouncementsSuccessResponse]):
    """Отмена анонса в СД via ``POST /cancelAnnouncement``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        reason: Причина омены анонса
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/cancelAnnouncement"

    announcement_id: str = Field(..., alias="announcementID")
    reason: CancelAnnouncement3PlReason | None = None


class CreateAnnouncement3Pl(BaseMethod[AnnouncementsSuccessResponse]):
    """Создание анонса в СД via ``POST /createAnnouncement``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        announcement_type: Тип анонса
        barcode: Уникальный ШК анонса. Должен быть напечатан на бумажных сопроводительных документах (акте приема передачи). Данный ШК необходимо использовать для установки соответствия принимаемой партии грузомест/посылок с анонсом переданным в электронном виде через инфообмен.
        date_: Дата и время создания анонса в формате RFC 3339 в UTC
        packages: Список грузомест
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/createAnnouncement"

    announcement_id: str = Field(..., alias="announcementID")
    announcement_type: CreateAnnouncement3PlAnnouncementType = Field(..., alias="announcementType")
    barcode: str
    date_: Any = Field(..., alias="date")
    packages: list[Any]
    receiver: Any
    sender: Any


class CreateParcel(BaseMethod[CreateParcelResponse]):
    """Создание посылки via ``POST /createParcel``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        barcodes: Штрихкоды посылки.
        direct_order_id: Идентификатор прямого заказа Avito.
        items: Список товаров, которые поедут в посылке. Содержит полное описание каждого отдельно взятого товара.
        order_id: Идентификатор заказа Avito.
        parcel_id: Идентификатор посылки Avito.
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/createParcel"

    barcodes: list[str] | None = None
    direct_order_id: str | None = Field(None, alias="directOrderID")
    items: list[CreateParcelItem]
    options: CreateParcelOptions | None = None
    order_id: str = Field(..., alias="orderID")
    package: CreateParcelPackage | None = None
    parcel_id: str = Field(..., alias="parcelID")
    payment: CreateParcelPayment
    receiver: CreateParcelClient
    sender: CreateParcelClient


class CreateAnnouncement(BaseMethod[AnnouncementsSuccessResponse]):
    """Создание анонса в Avito via ``POST /delivery-sandbox/announcements/create``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        announcement_type: Тип анонса
        barcode: Уникальный ШК анонса. Должен быть напечатан на бумажных сопроводительных документах (акте приема передачи). Данный ШК необходимо использовать для установки соответствия принимаемой партии грузомест/посылок с анонсом переданным в электронном виде через инфообмен
        date_: Дата и время создания анонса в формате RFC 3339 в UTC
        packages: Список грузомест
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/announcements/create"

    announcement_id: str = Field(..., alias="announcementID")
    announcement_type: CreateAnnouncementAnnouncementType = Field(..., alias="announcementType")
    barcode: str
    date_: Any = Field(..., alias="date")
    packages: list[Any]
    receiver: Any
    sender: Any


class TrackAnnouncement(BaseMethod[AnnouncementsSuccessResponse]):
    """Трекинг анонсов via ``POST /delivery-sandbox/announcements/track``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        date_: Дата события
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/announcements/track"

    announcement_id: str = Field(..., alias="announcementID")
    date_: Any = Field(..., alias="date")
    event: TrackAnnouncementEvent


class CustomAreaSchedule(BaseMethod[AddTaskReply]):
    """Установка графика работы на определённый день via ``POST /delivery-sandbox/areas/custom-schedule``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/areas/custom-schedule"


class CancelParcel(BaseMethod[CancelParcelReply]):
    """Отмена посылки via ``POST /delivery-sandbox/cancelParcel``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        actor: Кто отменяет посылку
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/cancelParcel"

    actor: CancelParcelActor
    parcel_id: str = Field(..., alias="parcelID")


class CheckConfirmationCode(BaseMethod[CheckConfirmationCodeReply]):
    """Проверка кода подтверждения via ``POST /delivery-sandbox/order/checkConfirmationCode``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/order/checkConfirmationCode"

    confirm_code: str = Field(..., alias="confirmCode")
    parcel_id: str = Field(..., alias="parcelID")


class SetOrderProperties(BaseMethod[DeliverySetOrderPropertiesReply]):
    """Добавление / изменение параметров доставки посылки via ``POST /delivery-sandbox/order/properties``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/order/properties"

    order_id: str = Field(..., alias="orderId")
    properties: DeliveryParams


class SetOrderRealAddress(BaseMethod[DeliverySetOrderPropertiesReply]):
    """Фактический адрес приёма / возврата посылки via ``POST /delivery-sandbox/order/realAddress``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/order/realAddress"

    address: SetOrderRealAddressAddress
    order_id: str = Field(..., alias="orderId")


class Tracking(BaseMethod[DeliverySetStatusReply]):
    """Трекинг via ``POST /delivery-sandbox/order/tracking``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        avito_event_type: Описание статусов см. [здесь](https://developers.avito.ru/api-catalog/delivery-sandbox/documentation#info/mehanika_raboty_trekinga).
        avito_status: Описание статусов см. [здесь](https://developers.avito.ru/api-catalog/delivery-sandbox/documentation#info/mehanika_raboty_trekinga).
        comment: Комментарий к статусу.
        location: Локация в которой произошло событие (населённый пункт в именительном падеже).
        options: Дополнительные опции к статусу. На данный момент в опциях поддержана передача штрихкода посылки и возвратных номеров. Если номера `returnTrackingNumber` и `returnDispatchNumber` совпадают, то нужно присылать в них одинаковые значения.
        provider_event_code: Код события по версии службы доставки.
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/order/tracking"

    avito_event_type: str = Field(..., alias="avitoEventType")
    avito_status: Any = Field(..., alias="avitoStatus")
    comment: str | None = None
    date_: str = Field(..., alias="date")
    location: str
    options: TrackingOptions | None = None
    order_id: str = Field(..., alias="orderId")
    provider_event_code: str = Field(..., alias="providerEventCode")


class ProhibitOrderAcceptance(BaseMethod[ProhibitOrderAcceptanceReply]):
    """Запрет приёма посылки от отправителя via ``POST /delivery-sandbox/prohibitOrderAcceptance``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/prohibitOrderAcceptance"

    order_id: str = Field(..., alias="orderId")


class GetSortingCenter(BaseMethod[SortingCenterGet]):
    """Получить список сортировочных центров via ``GET /delivery-sandbox/sorting-center``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        delivery_providers: Список кодов служб доставки, сортировочные центры которых необходимо вернуть
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/sorting-center"

    delivery_providers: str = Field(..., alias="deliveryProviders")


class AddSortingCenter(BaseMethod[AddTaskReply]):
    """Загрузить сортировочные центры via ``POST /delivery-sandbox/tariffs/sorting-center``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/tariffs/sorting-center"


class AddAreasSandbox(BaseMethod[AddTariffReply]):
    """Загрузить области доставки via ``POST /delivery-sandbox/tariffs/{tariff_id}/areas``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        tariff_id: id тарифа, к которому должны быть прикреплены добавляемые области
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/tariffs/{tariff_id}/areas"

    tariff_id: int


class AddTagsToSortingCenter(BaseMethod[AddTaskReply]):
    """Установка тэгов своим и/или чужим сортировочным центрам via ``POST /delivery-sandbox/tariffs/{tariff_id}/tagged-sorting-centers``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        tariff_id: id своего тарифа, теги которого будут установлены для сортировочных центров
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/tariffs/{tariff_id}/tagged-sorting-centers"

    tariff_id: int


class AddTerminalsSandbox(BaseMethod[AddTerminalsReply]):
    """Загрузить терминалы via ``POST /delivery-sandbox/tariffs/{tariff_id}/terminals``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        tariff_id: id тарифа, к которому должны быть прикреплены добавляемые терминалы
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/tariffs/{tariff_id}/terminals"

    tariff_id: int


class UpdateTerms(BaseMethod[UpdateTermsReply]):
    """Обновить сроки по тарифу via ``POST /delivery-sandbox/tariffs/{tariff_id}/terms``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        tariff_id: id тарифа, к которому должны быть прикреплены добавляемые области
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/tariffs/{tariff_id}/terms"

    tariff_id: int


class AddTariffSandboxV2(BaseMethod[AddTaskReply]):
    """Загрузить новый тариф v2 via ``POST /delivery-sandbox/tariffsV2``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        delivery_provider_tariff_id: Идентификатор тарифного плана на стороне службы доставки - должен быть уникален.
        directions: Список направлений доставки в тарифном плане
        name: Человекопонятное название тарифного плана
        tariff_type: Тип разделения тарифа по габаритам товаров. - MGT - малогабаритные товары - KGT - крупногабаритные товары Если поле не указано, то тариф должен содержать оба типа разделения (для обратной совместимости со старыми тарифами).
        tariff_zones: Список тарифных зон
        terms_zones: Список зон сроков
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/tariffsV2"

    delivery_provider_tariff_id: str = Field(..., alias="deliveryProviderTariffId")
    directions: list[DirectionV2]
    name: str
    tariff_type: AddTariffSandboxV2TariffType | None = Field(None, alias="tariffType")
    tariff_zones: list[TariffZone] = Field(..., alias="tariffZones")
    terms_zones: list[TermsZone] = Field(..., alias="termsZones")


class GetTask(BaseMethod[GetTaskReply]):
    """Получение информации по задаче via ``GET /delivery-sandbox/tasks/{task_id}``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/tasks/{task_id}"

    task_id: int


class V1cancelAnnouncement(BaseMethod[SandboxCancelAnnouncementReply]):
    """Отправка события об отмене тестового анонса via ``POST /delivery-sandbox/v1/cancelAnnouncement``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        announcement_id: Уникальный идентификатор анонса UUID V4.
        date_: Дата события
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/cancelAnnouncement"

    announcement_id: str = Field(..., alias="announcementID")
    date_: TZDatetime = Field(..., alias="date")
    options: SandboxCancelAnnouncementOptions


class V1CancelParcel(BaseMethod[CancelSandboxParcelReply]):
    """Отмена тестовой посылки via ``POST /delivery-sandbox/v1/cancelParcel``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/cancelParcel"

    options: CancelSandboxParcelOptions | None = None
    parcel_id: str = Field(..., alias="parcelID")


class V1changeParcel(BaseMethod[ChangeParcelReply]):
    """Создание заявки на изменение данных тестовой посылки via ``POST /delivery-sandbox/v1/changeParcel``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        parcel_id: Идентификатор посылки.
        type_: Тип заявки, которую необходимо зарегистрировать.
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/changeParcel"

    application: ChangeParcelRequestApplication | None = None
    options: ChangeParcelRequestOptions | None = None
    parcel_id: str = Field(..., alias="parcelID")
    type_: V1changeParcelType = Field(..., alias="type")


class V1createAnnouncement(BaseMethod[SandboxCreateAnnouncementReply]):
    """Создание тестового анонса via ``POST /delivery-sandbox/v1/createAnnouncement``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        announcement_id: Уникальный идентификатор анонса UUID V4.
        announcement_type: Тип анонса.
        barcode: Штрихкод анонса.
        date_: Дата и время создания анонса (UTC).
        packages: Список грузомест.
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/createAnnouncement"

    announcement_id: str = Field(..., alias="announcementID")
    announcement_type: V1createAnnouncementAnnouncementType = Field(..., alias="announcementType")
    barcode: str
    date_: TZDatetime = Field(..., alias="date")
    options: SandboxCreateAnnouncementOptions
    packages: list[SandboxCreateAnnouncementPackage]
    receiver: SandboxCreateAnnouncementParticipant
    sender: SandboxCreateAnnouncementParticipant


class V1getAnnouncementEvent(BaseMethod[SandboxGetAnnouncementEventReply]):
    """Получение последнего события тестового анонса via ``POST /delivery-sandbox/v1/getAnnouncementEvent``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        announcement_id: Уникальный идентификатор анонса UUID V4.
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/getAnnouncementEvent"

    announcement_id: str = Field(..., alias="announcementID")


class V1getChangeParcelInfo(BaseMethod[GetChangeParcelInfoReply]):
    """Получение информации об изменении тестовой посылки via ``POST /delivery-sandbox/v1/getChangeParcelInfo``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        application_id: Идентификатор заявки на изменение данных посылки
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/getChangeParcelInfo"

    application_id: str = Field(..., alias="applicationID")


class V1getParcelInfo(BaseMethod[GetSandboxParcelInfoReply]):
    """Получение информации о тестовой посылке via ``POST /delivery-sandbox/v1/getParcelInfo``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/getParcelInfo"

    parcel_id: str = Field(..., alias="parcelID")


class V1getRegisteredParcelId(BaseMethod[GetRegisteredParcelIdReply]):
    """Получение ID зарегистрированной тестовой посылки via ``POST /delivery-sandbox/v1/getRegisteredParcelID``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v1/getRegisteredParcelID"

    order_id: str = Field(..., alias="orderID")


class CreateSandboxParcelV22(BaseMethod[CreateParcelReply]):
    """Создание тестовой посылки via ``POST /delivery-sandbox/v2/createParcel``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery-sandbox/v2/createParcel"

    items: list[CreateSandboxParcelItem] | None = None
    options: CreateSandboxV2Options | None = None
    receiver: CreateSandboxParcelV22Receiver | None = None
    sender: CreateSandboxParcelV22Sender | None = None
    tags: list[str] | None = None


class ChangeParcelResult(BaseMethod[ChangeParcelResultReply]):
    """Отправка результата исполнения заявки via ``POST /delivery/order/changeParcelResult``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        id: Идентификатор заявки на изменение посылки
        reason: Причина отклонения заявки (заполняется в случае отклонения).
        status: Статус обработки заявки
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/delivery/order/changeParcelResult"

    id: str
    options: StorageExtendedToResponse | None = None
    reason: str | None = None
    status: ChangeParcelResultStatus


class ChangeParcels(BaseMethod[ChangeParcelsResponse]):
    """Обновление свойств посылок via ``POST /sandbox/changeParcels``.

    See: https://developers.avito.ru/api-catalog/delivery-sandbox/documentation

    Args:
        type_: Тип заявки. Заявки могут быть следующих типов: - `changeReceiver` - обновить данные о получателе посылки. - `extendParcelStorage` - продлить срок хранения посылки. - `prohibitParcelReceive` - запретить выдачу посылки на ПВЗ вручения. - `prohibitParcelAcceptance` - запретить прием посылки на ПВЗ отправки (в разработке). - `changeReceiverTerminalOnConfirmed` - обновить ПВЗ вручения.
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/sandbox/changeParcels"

    applications: list[ChangeParcelsApplication]
    type_: ChangeParcelsType = Field(..., alias="type")
