# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""TrxPromo — domain endpoints (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.trxpromo import (
    ApiTrxPromoOpenApiApplyItems,
    ApplyResponse,
    CancelResponse,
    CommissionResponse,
)
from ._base import BaseMethod


class ApiTrxPromoOpenApiApply(BaseMethod[ApplyResponse]):
    """Запуск продвижения via ``POST /trx-promo/1/apply``.

    See: https://developers.avito.ru/api-catalog/trxpromo/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/trx-promo/1/apply"

    items: list[ApiTrxPromoOpenApiApplyItems]


class ApiTrxPromoOpenApiCancel(BaseMethod[CancelResponse]):
    """Остановка продвижения via ``POST /trx-promo/1/cancel``.

    See: https://developers.avito.ru/api-catalog/trxpromo/documentation
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/trx-promo/1/cancel"

    item_ids: list[int] = Field(..., alias="itemIDs")


class ApiTrxPromoOpenApiCommissions(BaseMethod[CommissionResponse]):
    """Проверка доступности продвижения и размера комиссий via ``GET /trx-promo/1/commissions``.

    See: https://developers.avito.ru/api-catalog/trxpromo/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/trx-promo/1/commissions"

    item_ids: list[int] = Field(..., alias="itemIDs")
