# AUTO-GENERATED by avitoapi.codegen — regenerate, do not hand-edit.
"""Информация о пользователе — domain endpoints (auto-generated from the Avito OpenAPI spec)."""

from __future__ import annotations

from typing import ClassVar

from pydantic import Field

from ..models.common import TZDatetime
from ..models.user import Balance, ResponseOperationsHistory, UserInfoSelf
from ._base import BaseMethod


class PostOperationsHistory(BaseMethod[ResponseOperationsHistory]):
    """Получение истории операций пользователя via ``POST /core/v1/accounts/operations_history/``.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Args:
        date_time_from: Время выборки от. Не далее одного года в прошлое от текущего момента.
        date_time_to: Время выборки до (диапазон между dateTimeFrom и dateTimeTo должен быть не более одной недели)
    """

    __http_method__: ClassVar[str] = "POST"
    __endpoint__: ClassVar[str] = "/core/v1/accounts/operations_history/"

    date_time_from: TZDatetime = Field(..., alias="dateTimeFrom")
    date_time_to: TZDatetime = Field(..., alias="dateTimeTo")


class GetUserInfoSelf(BaseMethod[UserInfoSelf]):
    """Получение информации об авторизованном пользователе via ``GET /core/v1/accounts/self``.

    See: https://developers.avito.ru/api-catalog/user/documentation
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/core/v1/accounts/self"


class GetUserBalance(BaseMethod[Balance]):
    """Получение баланса кошелька пользователя via ``GET /core/v1/accounts/{user_id}/balance/``.

    See: https://developers.avito.ru/api-catalog/user/documentation

    Args:
        user_id: Идентификатор пользователя (клиента)
    """

    __http_method__: ClassVar[str] = "GET"
    __endpoint__: ClassVar[str] = "/core/v1/accounts/{user_id}/balance/"

    user_id: int
