"""avitoapi — aiogram-style async SDK over the Avito Partner API."""
from __future__ import annotations

from . import events, exceptions, routers
from .client import Client
from .config import ClientConfig
from .events import (
    AnnouncementTracked,
    AuthFailed,
    AutoloadFailed,
    AutoloadReportReady,
    BalanceChanged,
    BalanceLow,
    BalanceToppedUp,
    BaseEvent,
    BonusReceived,
    CallEnded,
    CallReceived,
    CallRecordingReady,
    ChatArchived,
    ChatBlacklisted,
    ItemArchived,
    ItemBlocked,
    ItemPublished,
    ItemSold,
    ItemStatusChanged,
    ItemUnblocked,
    MessageRead,
    NewMessage,
    OrderCancelled,
    OrderCompleted,
    OrderConfirmed,
    OrderCreated,
    OrderDelivered,
    OrderRefunded,
    OrderShipped,
    OrderStatusChanged,
    ParcelDelivered,
    ParcelHandedOver,
    ParcelReturned,
    ParcelStatusChanged,
    PollError,
    ReviewAnswered,
    ReviewReceived,
    Shutdown,
    Startup,
    TokenRefreshed,
    VoiceFileResolved,
    WebhookError,
)
from .exceptions import (
    AuthError,
    ForbiddenError,
    HTTPError,
    MethodNotBoundError,
    NotFoundError,
    RateLimitedError,
    RunawayPagination,
    SDKError,
    ServerError,
    UnauthorizedError,
    ValidationFailed,
)
from .methods._base import BaseMethod
from .methods.accounts import GetSelf
from .models.accounts import Account
from .models.balance import (
    Balance,
    BalanceBonus,
    Operation,
    OperationType,
)
from .models.common import AvitoErrorBody, Currency, Money, Page
from .models.items import Item, ItemStatus, VasService
from .pagination import IndexPaginator, TimeWindowPaginator
from .routers import (
    AutoloadRouter,
    BalanceRouter,
    CalltrackingRouter,
    DeliveryRouter,
    EventObserver,
    ItemsRouter,
    LifecycleRouter,
    MessengerRouter,
    OrdersRouter,
    ReviewsRouter,
    Router,
)
from .types import HealthState, HealthStatus, HostKey

__version__ = "0.1.0"

__all__ = [
    "Account",
    "AnnouncementTracked",
    "AuthError",
    "AuthFailed",
    "AutoloadFailed",
    "AutoloadReportReady",
    "AutoloadRouter",
    "AvitoErrorBody",
    "Balance",
    "BalanceBonus",
    "BalanceChanged",
    "BalanceLow",
    "BalanceRouter",
    "BalanceToppedUp",
    "BaseEvent",
    "BaseMethod",
    "BonusReceived",
    "CallEnded",
    "CallReceived",
    "CallRecordingReady",
    "CalltrackingRouter",
    "ChatArchived",
    "ChatBlacklisted",
    "Client",
    "ClientConfig",
    "Currency",
    "DeliveryRouter",
    "EventObserver",
    "ForbiddenError",
    "GetSelf",
    "HTTPError",
    "HealthState",
    "HealthStatus",
    "HostKey",
    "IndexPaginator",
    "Item",
    "ItemArchived",
    "ItemBlocked",
    "ItemPublished",
    "ItemSold",
    "ItemStatus",
    "ItemStatusChanged",
    "ItemUnblocked",
    "ItemsRouter",
    "LifecycleRouter",
    "MessageRead",
    "MessengerRouter",
    "MethodNotBoundError",
    "Money",
    "NewMessage",
    "NotFoundError",
    "Operation",
    "OperationType",
    "OrderCancelled",
    "OrderCompleted",
    "OrderConfirmed",
    "OrderCreated",
    "OrderDelivered",
    "OrderRefunded",
    "OrderShipped",
    "OrderStatusChanged",
    "OrdersRouter",
    "Page",
    "ParcelDelivered",
    "ParcelHandedOver",
    "ParcelReturned",
    "ParcelStatusChanged",
    "PollError",
    "RateLimitedError",
    "ReviewAnswered",
    "ReviewReceived",
    "ReviewsRouter",
    "Router",
    "RunawayPagination",
    "SDKError",
    "ServerError",
    "Shutdown",
    "Startup",
    "TimeWindowPaginator",
    "TokenRefreshed",
    "UnauthorizedError",
    "ValidationFailed",
    "VasService",
    "VoiceFileResolved",
    "WebhookError",
    "__version__",
    "events",
    "exceptions",
    "routers",
]
