"""avitoapi — aiogram-style async SDK over the Avito Partner API."""
from __future__ import annotations

from . import events, exceptions, routers
from .client import Client
from .config import ClientConfig
from .dispatcher import Dispatcher, make_dispatcher
from .events import (
    AnnouncementTracked,
    AuthFailed,
    AutoloadFailed,
    AutoloadReportReady,
    BalanceChanged,
    BalanceLow,
    BalanceToppedUp,
    BaseEvent,
    BonusReceived,
    CallEnded,
    CallReceived,
    CallRecordingReady,
    ChatArchived,
    ChatBlacklisted,
    ItemArchived,
    ItemBlocked,
    ItemPublished,
    ItemSold,
    ItemStatusChanged,
    ItemUnblocked,
    MessageRead,
    NewMessage,
    OrderCancelled,
    OrderCompleted,
    OrderConfirmed,
    OrderCreated,
    OrderDelivered,
    OrderRefunded,
    OrderShipped,
    OrderStatusChanged,
    ParcelDelivered,
    ParcelHandedOver,
    ParcelReturned,
    ParcelStatusChanged,
    PollError,
    ReviewAnswered,
    ReviewReceived,
    Shutdown,
    Startup,
    TokenRefreshed,
    VoiceFileResolved,
    WebhookError,
)
from .exceptions import (
    AuthError,
    ForbiddenError,
    HTTPError,
    MethodNotBoundError,
    NotFoundError,
    ProxyAuthError,
    ProxyBanned,
    ProxyConnectionError,
    ProxyError,
    ProxyExhausted,
    ProxyParseError,
    ProxyTimeoutError,
    ProxyTLSError,
    RateLimitedError,
    RunawayPagination,
    SDKError,
    ServerError,
    UnauthorizedError,
    ValidationFailed,
)
from .sessions.proxy_middleware import ProxyErrorMiddleware, RetryMiddleware
from .filters import F, MagicFilter
from .persistent_queue import (
    BaseEventQueue,
    EventQueue,
    EventSerializer,
    PickleSerializer,
    QueuedEvent,
)
from .pipeline import (
    BaseStage,
    Pipeline,
    PipelineCheckpoint,
    PipelineRouter,
    PipelineRunner,
    PipelineStageError,
    Stage,
    pipeline_stage,
    stage_name_of,
)
from .routers import BaseMiddleware, CtxPipeline, CtxQueue, EventContext, HandlerType, MiddlewareChain
from .utils.proxy import (
    KEEP,
    BaseProxyTransport,
    CallbackProxyTransport,
    ListProxyTransport,
    NoProxyTransport,
    Proxy,
    ProxyAcquireContext,
    ProxyCallback,
    ProxyCheckResult,
    ProxyContext,
    ProxyValidator,
    RotationStrategy,
    parse_proxy,
    parse_proxy_list,
)
from .methods._base import BaseMethod
from .methods.accounts import GetSelf
from .models.accounts import Account
from .models.balance import (
    Balance,
    BalanceBonus,
    Operation,
    OperationType,
)
from .models.common import AvitoErrorBody, Currency, Money, Page
from .models.items import Item, ItemStatus, VasService
from .pagination import (
    MethodPaginator,
    OffsetMethod,
    PageMethod,
    PaginatedMethod,
)
from .routers import EventObserver, Router
from .types import HealthState, HealthStatus, HostKey

__version__ = "0.1.0"

__all__ = [
    "KEEP",
    "Account",
    "AnnouncementTracked",
    "AuthError",
    "AuthFailed",
    "AutoloadFailed",
    "AutoloadReportReady",
    "AvitoErrorBody",
    "BaseMiddleware",
    "Balance",
    "BalanceBonus",
    "BalanceChanged",
    "BalanceLow",
    "BalanceToppedUp",
    "BaseEvent",
    "BaseMethod",
    "BaseProxyTransport",
    "BaseStage",
    "BonusReceived",
    "CallEnded",
    "CallReceived",
    "CallRecordingReady",
    "CallbackProxyTransport",
    "BaseEventQueue",
    "ChatArchived",
    "ChatBlacklisted",
    "Client",
    "ClientConfig",
    "CtxPipeline",
    "CtxQueue",
    "Currency",
    "Dispatcher",
    "EventContext",
    "EventObserver",
    "EventQueue",
    "EventSerializer",
    "F",
    "ForbiddenError",
    "HandlerType",
    "GetSelf",
    "HTTPError",
    "HealthState",
    "HealthStatus",
    "HostKey",
    "Item",
    "ItemArchived",
    "ItemBlocked",
    "ItemPublished",
    "ItemSold",
    "ItemStatus",
    "ItemStatusChanged",
    "ItemUnblocked",
    "ListProxyTransport",
    "MagicFilter",
    "MessageRead",
    "MethodNotBoundError",
    "MiddlewareChain",
    "MethodPaginator",
    "Money",
    "NewMessage",
    "NoProxyTransport",
    "NotFoundError",
    "OffsetMethod",
    "Operation",
    "OperationType",
    "OrderCancelled",
    "OrderCompleted",
    "OrderConfirmed",
    "OrderCreated",
    "OrderDelivered",
    "OrderRefunded",
    "OrderShipped",
    "OrderStatusChanged",
    "Page",
    "PageMethod",
    "PaginatedMethod",
    "ParcelDelivered",
    "PickleSerializer",
    "Pipeline",
    "PipelineCheckpoint",
    "PipelineRouter",
    "PipelineRunner",
    "PipelineStageError",
    "ParcelHandedOver",
    "ParcelReturned",
    "ParcelStatusChanged",
    "PollError",
    "Proxy",
    "ProxyAcquireContext",
    "ProxyAuthError",
    "ProxyBanned",
    "ProxyCallback",
    "ProxyCheckResult",
    "ProxyConnectionError",
    "ProxyContext",
    "ProxyError",
    "ProxyErrorMiddleware",
    "ProxyExhausted",
    "ProxyParseError",
    "ProxyTLSError",
    "ProxyTimeoutError",
    "ProxyValidator",
    "QueuedEvent",
    "RateLimitedError",
    "RetryMiddleware",
    "ReviewAnswered",
    "ReviewReceived",
    "RotationStrategy",
    "Router",
    "Stage",
    "RunawayPagination",
    "SDKError",
    "ServerError",
    "Shutdown",
    "Startup",
    "TokenRefreshed",
    "UnauthorizedError",
    "ValidationFailed",
    "VasService",
    "VoiceFileResolved",
    "WebhookError",
    "__version__",
    "events",
    "exceptions",
    "make_dispatcher",
    "parse_proxy",
    "parse_proxy_list",
    "pipeline_stage",
    "routers",
    "stage_name_of",
]
